web/templates/alerts.html
This fixes https://github.com/prometheus/alertmanager/issues/21
Otherwise, sending an alert with a missing `GeneratorURL` payload
property would cause the template rendering to crash:
Error executing template: template: alerts.html:51:76: executing "content" at <.Alert.Payload.Gener...>: invalid value; expected string
=> Treat `GeneratorURL` as optional in Alerts page.

Dockerfile
This fixes the docker build which broke since we removed the 'build'
target from the Makefile.
=> Run make in Dockerfile without explicit target

Makefile.INCLUDE
When building a Debian package with `debuild`, which uses fakeroot, Make doesn't have `$(PWD)` for some reason. Apparently this is a shell-dependent thing. For that reason, the `touch` command gets the wrong path in `$@`:
```
make[1]: Entering directory `/tmp/d20150222-20503-whiv4g/prometheus-alertmanager_0.0git942cd35'
mkdir -p .deps
curl -o .deps/go1.4.1.linux-amd64.tar.gz -L https://golang.org/dl/go1.4.1.linux-amd64.tar.gz
tar -C .deps -xzf .deps/go1.4.1.linux-amd64.tar.gz
touch /.deps/go/bin/go
touch: cannot touch ‘/.deps/go/bin/go’: No such file or directory
make[1]: *** [/.deps/go/bin/go] Error 1
```
(The makefile in `node_exporter` is correct, by the way.)
=> Makefile: Use $(CURDIR) instead of $(PWD), which is more dependable

manager/notifier.go
I'm trying out alertmanager in Amazon EC2, and the easiest delivery of notifications I could think of is through Amazon's email sending service. It requires auth, though, so I threw this change together.
=> Add -smtpAuth for mail servers that require authentication

manager/notifier.go, manager/notifier_test.go
This code feels a lot cleaner in its own function, which now has 100% test coverage.
=> Separate out SMTP auth logic and test it.

Dockerfile
=> docker: run alertmanager as nobody

manager/notifier.go, manager/notifier_test.go
Computer said no:
Missing required header field: "Date"
Delivery of the email was stopped!
=> Add date header to please strict mail servers

manager/notifier.go
Put the alert title in bold to make it visually more pleasing
=> Visually distinguish alertname and summary

config/config.proto, config/fixtures/sample.conf.input, config/generated/config.pb.go, manager/manager.go, manager/notifier.go, manager/notifier_test.go
Instead of relying on prometheus to send notifications for resolved alerts, this change adds support to send resolve notification once an alert expired.
=> Add support to notify for resolved alerts

Makefile
This was accidentally removed in
https://github.com/prometheus/alertmanager/pull/55
=> Re-add config Makefile target.

.gitignore, README.md, config/config.go, config/config.proto, config/fixtures/sample.conf.input, config/generated/config.pb.go, manager/notifier.go
Like the HipChat one, here a simple implementation for Slack notifications.
@juliusv
=> Add simple support for Slack notifications

main.go, web/alerts.go, web/api/api.go, web/silences.go, web/status.go, web/templates/_base.html, web/templates/alerts.html, web/templates/silences.html, web/web.go
Same as https://github.com/prometheus/prometheus/pull/614 and https://github.com/prometheus/promdash/pull/369
Using this code my AlertManager receives alerts from my Prometheus (after changing the API URL in Prometheus) and nothing in the interface is obviously broken.
One thing to note: there was a peculiar check inside `web/web.go`:
```python
// The "/" pattern matches everything, so we need to check
// that we're at the root here.
if req.URL.Path != "/" {
http.NotFound(rw, req)
return
}
```
Prometheus doesn't have something like this, and after moving the root handler to the bottom of that functions thing seem to work okay without it.
=> Path prefix to support reverse proxies

README.md, config/config.go, config/config.proto, config/fixtures/sample.conf.input, config/generated/config.pb.go, manager/notifier.go
Hi, I wrote a Flowdock notifier.
I did it a bit different way than the HipChat and Slack notifiers, I didn't want to duplicate code in e.g. serializing to JSON, and posting to HTTP URL.
There is quite a lot of duplicated code in manager/notifier.go. I was thinking I could rewite it in similar manner in another pull-request. Would you be interested in that?
I didn't write any tests, it wasn't straightforward to mock the config and the alert. Maybe it would be easier after the refactoring I suggest.
=> Flowdock notifications

manager/notifier.go
assume that the summary is the message, and that the alertname is a very short concise name for the alert
=> add status to pushover title

web/web.go
Previously we redirected any non-existent path to the root (or path
prefix).
The new behavior:
With no path prefix:
- "" -> "/"
- "/biz" -> 404
With path prefix of "/foo/bar":
- "" -> "/foo/bar/"
- "/" -> "/foo/bar/"
- "/foo/bar" -> "/foo/bar/"
- "/biz" -> /foo/bar/biz"
(anything not starting with the path prefix gets the prefix prepended)
- "/foo/bar/biz" -> 404
This fixes https://github.com/prometheus/alertmanager/issues/66
=> Improve web redirection and 404 behavior.

config/watcher.go
Probably ought to update to v1.x of fsnotify at some point as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/prometheus/alertmanager/69)
=> Update fsnotify to its new source location

README.md, config/config.proto, config/generated/config.pb.go, main.go, manager/alert.go, manager/manager.go, manager/notifier.go, manager/notifier_test.go, web/api/api.go, web/silences.go
This allows for use cases such as kicking off shell scripts,
logging notifications, or anything else the alertmanager doesn't
directly support.
@juliusv 
Is there a better way to test this? This seems kinda clunky.
=> Add a generic webhook notifier.

config/config.proto, config/generated/config.pb.go, manager/notifier.go
Hi! So I was planning to pester my fellow co-workers with HipChat notifications, whenever Prometheus fires alerts. In order to do so, I needed a way to add `@all` or `@somename` to the message body. (I know there is a notify flag, but that didn't seem to work as well and doesn't allow to target specific people or groups like `all` or `here`.) 
The alertmanager sends HipChat notifications in HTML format. This opens the door for nicely formatted messages, but also has the consequence, that @mentions don't work. (For some strange reason, that only Atlassian knows...)
Here is an excerpt from the `message_format` section of the HipChat documentation:
> * html - Message is rendered as HTML and receives no special treatment. Must be valid HTML and entities must be escaped (e.g.: '&amp;' instead …
=> Added support for @mentions in HipChat notifications

Dockerfile
This fix the `Error saving silences to file: open silences.json: permission denied` error when using `prom/alertmanager` docker image.
@juliusv @discordianfish
=> Fix silences.json permission error with docker image

manager/notifier.go
The email body writer function had it's parameters in the wrong order, leading to the insertion of the email address of the sender rather then the actual status field.
I can confirm from testing that this pull request fixes the problem.
=> Fix email template body writer being called with parameters in wrong order

web/api/alert.go, web/api/api.go
This is a tiny change which extends the /api/alerts function to write JSON formatted AlertAggregates when polled with a GET request.
This allows integrating the alertmanager with existing dashboard/notification walls which either want to poll the alerts output or get an initial scan of the current alert state.
=> Add a GET api to /api/alerts which pulls JSON formatted AlertAggregates.

main.go, manager/alert.go, manager/notifier.go, manager/notifier_test.go, web/web.go
I don't have a way to test all the other notification mechanisms, which
is something we should fix in general. For now, only PagerDuty and email
have the new runbook and alertmanager URL information.
Not very happy with the overall cleanliness of this, and the codebase
overall, of course, but since we need this urgently tomorrow, I hope
this is fine for now.
=> Add runbook and alertmanager URLs to PD+email notifications.

manager/notifier.go
Currently a failure is logged as:
msg="Sent Slack notification: 17555453829685976206: HTTP 500: Invalid channel specified"
Add the actual channel in there to aid in debugging.
=> Slack notification: add channel

main.go
Allows setting the full external URL for accessing Alertmanager, takes
precedence over web.hostname.
Fixes #95
I left the old flags there so we don't break any existing users, but they should
probably be dropped at some point.
=> Add web.external-url flag

manager/notifier.go
Apparently there are cases when 5 seconds is not enough.
=> Made slack timeout configurable

config/config.proto, config/generated/config.pb.go, manager/notifier.go, manager/notifier_test.go
This adds notifications to OpsGenie. It is using the webhook api. The
notification_config should look like
opsgenie_config {
api_key: "bliep"
teams: "team-one"
send_resolved: true
}
It further sets the alert fingerprint in Alias and adds all the
alert labels into the Details field.
See https://www.opsgenie.com/docs/web-api/alert-api#createAlertRequest
for the details.
It can also close the alert by using the Alias field again. See
https://www.opsgenie.com/docs/web-api/alert-api#closeAlertRequest
=> Alertmanager: Add OpsGenie Webhook notification.

README.md, config/config.go, config/config.proto, config/fixtures/sample.conf.input, config/generated/config.pb.go, manager/notifier.go
Add support for sending alert notifications to an Amazon SNS topic.
Modified README to include information on notifier.
Modified config.go to add in configuration validation for SNS configs.
Modified config.proto to add in appropriate protobuf generation
Modified sample.conf.input for config example
Modified notifier.go to add in sending of alerts to configured topic ARN
=> Add Amazon SNS Notifier

web/templates/_base.html
Using email addresses provides a unique identifier with a defined
format. It will reduce the amount of different and ambigious identifiers
used (first, last, full, initials, different case used, etc.) while
still allowing others to use a different format.
I could also imagine making an email address mandatory.
@juliusv @matthiasr
=> Suggest to use email address as silence creator

manager/notifier.go, manager/notifier_test.go
Closing OpsGenie alerts requires that the close request is POSTed to an endpoint ending with /close but otherwise identical to the alert creation endpoint. Update notifier.go to reflect this and add a test.
Reference: https://www.opsgenie.com/docs/web-api/alert-api#closeAlertRequest ("Sample Request")
=> Minor fix: Post OpsGenie alert close requests to /v1/json/alert/close endpoint

manager/notifier.go
This caught me out, and I would have appreciated being made aware of it when running `alertmanager -h` instead of finding out when I saw `level=error msg="Error sending email notification: dial tcp: missing port in address` in my alertmanager.log
@juliusv - Hoping I save someone else the trouble.
=> Adding documentation to make clear that port is required

manager/manager.go
This bug has been around since at least July, and multiple people have reported it in #82, #122 and #131. I hope that pulling this despite the rewrite is easier than closing yet another duplicate.
=> manager: Guard agg.Rule against dereferencing when nil.

Makefile
There are issues with changing timestamps for unmodified files
in go-bindata+git.
@beorn7
=> Remove 'assets' from default target

notify/impl.go, template/default.tmpl
This adds the number of alerts in the grouping. Helpful information for few characters.
Currently this is the total number. We might want to provide an easy way to separate resolved and firing alerts in the templating.
Fixes a mis-placed `)`.
Adds label name for everything but "alertname". By default that seems more sensible.
Before:
`[firing] ManyOpenConnections dd bazooka ()))critical)`
After:
` [firing:3] ManyOpenConnections cluster=dd service=bazooka (severity=critical)`
Longer but still fits into a single PagerDuty notification. If being truncated, mostly the additional common labels would be affected, which is okay.
@brian-brazil 
Added so that "alertname" is always at the first position of `data.GroupLabelnames`.
=> Improve default subject template

notify/impl.go, notify/notify.go, template/default.tmpl, template/template.go
I was about to do some templating and gave it another iteration. Data structures moved into `template/`.
Added some functions I consider necessary. `pairs` being a way for ordered iteration that I think is understandable to everyone and simplifies our data structure and also the usage for simple ordered iteration (no use of `index` function and reference to parent scope).
I want a first round of feedback before continuing with templates themselves.
@brian-brazil @beorn7
=> Iterate over templating

api.go, config/config.go, config/notifies.go, dispatch.go, main.go, notify/impl.go, notify/notify.go, template/default.tmpl, template/template.go
WIP on some nits.
@brian-brazil thoughts on that as a default level of information?
This stuff a string list of alerts into a single field. Having full JSON objects might be an option too. But more complicated and not generally supported by clients (e.g. OpsGenie).
=> Improve PagerDuty templating

template/template.go
It turns out that 'title case' is a thing in unicode,
in the same way upper/lower case is.
What our users will want is the first character of a word
being titlecased, which `title` will do.
@fabxc 
I don't think we should expose `toTitle`, as I'd expect most users are actually looking for `title` and this would just cause confusion.
=> Use title rather than toTitle.

template/default.tmpl, template/template.go
Thinking a bit, having type specific functions might not be the easiest to understand for users. This is another approach using dedicated types (based on strings only).
I expect the case of excluding certain labels etc. to be frequent enough to add a `Without` method and `strings.Join`. For the default subject this simplifies the previous conditional with scoping issues into 
`{{ with .CommonLabels.Without .GroupLabels.Names }}{{ join .Values " " }}{{ end }}`
Also reduces the need for another conditional to remove the trailing space.
@brian-brazil
=> Transfer template functions into types+methods

manager/notifier.go, manager/notifier_test.go
Some servers (notably smtp.gmail.com) require you to use STARTTLS before
they will even list PLAIN authentication. This commit makes using gmail
for smtp notifications work.
Aside from STARTTLS being required for authentication, it’s of course
also a good idea to just use STARTTLS whenever possible, regardless of
the authentication requirements :).
=> smtp: STARTTLS before querying auth mechanisms

notify/impl.go
As we've a new data format the version number needs a bump.
Also make alerts with no annotations easier to handle for
users on the receiving end.
@fabxc
=> Update webhook for new alertmanager.

config/notifiers.go
Slack is a general chat system, it has no notion
of resolved messages. Default it to false to avoid
spamming people as we do with all other such systems.
@fabxc
=> Don't send resolved to Slack by default

config/notifiers.go
I found a bug, if you configure a global `hipchat_auth_token`, then it doesnt start and print the message `missing auth token in Hipchat config`. So in the global configuration is the handling implemented which overrides the token.
=> remove checking auth token in config/notifiers.go

README.md
Since our default templates are now compiled into the binary, this is only
relevant to advanced users and will cause trouble when running a derivative
of the example config within the repository directory.
@RichiH @brian-brazil
=> Remove template section from example config

notify/notify.go, notify/notify_test.go, test/acceptance/send_test.go
This commit changes the notification grouping behavior
to simply send all alerts of a group as soon as a single
one of them needs updating.
This fixes a critical bug which caused erroneous resolved
notifications to be sent.
@brian-brazil
=> Simplify and fix notification grouping.

notify/impl.go
OpsGenie receiver has a source option:
```
[ source: <tmpl_string> | default = '{{ template "opsgenie.default.source" . }}' ]
```
Which sets a field in OpsGenie alarm definition. `OpsGenieConfig` struct is correctly populated but the field was missing when creating a new message.
=> OpsGenie: include missing source option

api.go, types/types.go, types/types_test.go
Fixes #231 
This only happened with the changed Integration in the upcoming Prometheus version. So with Prometheus clients 0.16.2 and earlier it didn't cause issues.
@juliusv can you verify?
=> Fix disappearing alerts

template/template.go
We have defined the option above, but it doesn't seem to propagate through cloning.
@brian-brazil
=> Use missingkey=zero option in templates

notify/impl.go
In #207, I speculated that the golang json encoder was overescaping the values sent to slack, but slack's API handles the escaped json fine. The real culprit is the html template call that is being used for text which is turning `<` into `&lt;`.
Using alertmanager with this patch, I can use the following configuration:
```
receivers:
- name: 'debug-slack'
slack_configs:
- api_url: "https://hooks.slack.com/services/crypto/crypto"
username: "{{ .GroupLabels.instance }}"
channel: "#prometheus-debug"
text: "{{ range .Alerts }}*{{ .Annotations.description }}* <{{ .Annotations.generatorURL }}|View in Prometheus>\n{{ end }}"
```
and then running:
```
curl -XPOST http://localhost:9093/api/v1/alerts -d '[{"labels": {
"alertname": "DMcLain Testing",
"severity": "warning",
"instance": …
```
=> Slack: Use the text template processor for the text field

notify/impl.go, template/template.go, test/mock.go
We basically want the same info for webhook integrations as for templating.
This will also make maintenance easier since we don't have two separate formats we have to version.
@brian-brazil
=> Upgrade webhook protocol

config/notifiers.go, notify/impl.go, template/default.tmpl
As it may be useful to quickly identify notifications in a channel stream, we needed support for "icon_emoji" in the slack receiver configuration.
Configuration look like this :
```
slack_configs:
- send_resolved: true
username: 'Prometheus'
channel: '#monitoring'
icon_emoji: ':prometheus:'
api_url: 'https://hooks.slack.com/services/<token>'
```
@fabxc, is this small addition ok for you ? Thanks in advance for your feedback.
=> Adding support for slack icon_emoji in slack receiver config.

config/config.go, config/notifiers.go, notify/impl.go, template/default.tmpl
This feature was dropped during the rewrite, but I use and like
Pushover.
The resulting notification looks like this:
=> Re-implement pushover notifications

config/notifiers.go, notify/impl.go
@fabxc
This PR exposes some extra settings available in the OpsGenie alert creation API. Teams and LabelsToTags used to be available on a previous version but have since been removed.
OpsGenieConfig now has the following extra settings:
- Teams: Templated comma-separated string of teams  that this alert should be assigned to.
- Tags: Templated comma-separated string of tags that should be set on alert.
(Create Alert Api)[https://www.opsgenie.com/docs/web-api/alert-api#createAlertRequest]
=> OpsGenie notifier: Add support for tags, teams, and using labels as tags.

config/notifiers.go, notify/impl.go
This was not ported over with the rewrite.
=> Re-do #163: smtp: STARTTLS before querying auth mechanisms

README.md, doc/examples/simple.yml
Wasn't initially clear to me what was needed to authenticate with e.g. Mandrill, Mailgun, etc..
Seems some others likely had [similar issues](https://github.com/prometheus/alertmanager/issues/275)
=> Clarify SMTP authentication in the docs

main.go
Other than by consulting the source code or looking at the suggested nginx proxy configuration [the default port isn't really documented anywhere](https://github.com/prometheus/alertmanager/search?utf8=%E2%9C%93&q=9093). As a newbie, when I started the service, I wasn't exactly sure what port it was running on. This could be helpful for some people.
=> Provide feedback in console about port

notify/impl.go
thanks to @Merovius for helping me with this solution and writing the patch.
@fabxc 
The Problem was, that I got this error when running the alertmanager:
```
alertmanager, version  (branch: , revision: )
build user:       
build date:       
go version:       go1.6
time="2016-04-09T22:11:13+02:00" level=info msg="Loading configuration file" file="/etc/alertmanager/alertmanager.yml" source="main.go:150" 
panic: runtime error: slice bounds out of range
goroutine 135 [running]:
panic(0xa27780, 0xc82000e0b0)
/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/prometheus/alertmanager/notify.(*Pushover).Notify(0xc8201ab090, 0x7f84c84d7230, 0xc8205ecd50, 0xc82051e4b0, 0x1, 0x1, 0x0, 0x0)
/home/user/gocode/src/github.com/prometheus/alertmanager/notify/impl.go:756 +0x1dd2 …
```
=> Fixing Pushover issue with message length

README.md, config/config.go, config/notifiers.go, doc/examples/simple.yml, notify/impl.go
Implements enhancement proposed in #306.
Note: I have left support for environment variables as a fallback since we probably don't want people's alerts to break if they pull down master and don't move their credentials from env variables to the config file.
Documentation additionally updated to reflect the fact that the config file is the preferred place to store creds.
=> Move SMTP auth to the config file

.promu.yml
With the sqlite to boltdb move, we can now cross-build alertmanager on almost all platforms supported by promu.
Missing platforms are `linux/mips64` and `linux/mips64le`, builds breaks with the following error:
```
/go/src/github.com/prometheus/alertmanager/vendor/github.com/boltdb/bolt/db.go:98: undefined: maxMapSize
/go/src/github.com/prometheus/alertmanager/vendor/github.com/boltdb/bolt/db.go:98: invalid array bound maxMapSize
[2] /go/src/github.com/prometheus/alertmanager/vendor/github.com/boltdb/bolt/db.go:98: invalid array bound maxMapSize
```
=> Support more cross-build platforms

test/acceptance.go, test/mock.go
Previously, the tests would listen on all available interfaces.
Instead, have the tests use localhost only; using all available
interfaces is unnecessary.
On Mac OS X with the builtin firewall enabled, it triggers annoying
prompts to allow the tests to listen on all interfaces.
=> Use localhost for tests

inhibit.go, inhibit_test.go, main.go
This change adds an inhibition cache. New alerts are checked against all
inhibition rules' source matchers. At notification time, we only have to
check the target matchers against the notified alerts. If there are
alerts in the source cache, we only have to verify the equal labels
against these.
=> inhibit: reduce O(n^2) complexity problem

config/config.go, config/config_test.go, route_test.go
This is useful when you're using a label to determine the receiver but
want to override other options such as `group_by`. Currently you'd have
to duplicate the matchers for the receivers to be able to do this.
`checkReceiver()` now returns no error if a receiver is empty and we add
a check to ensure that the root route has a receiver defined. I've added
a test for this.
This brings the `receiver` option into line with the other options
(`group_by`, `group_wait`, etc) in the sense that routes can now inherit
the receiver from the parent node.
From https://prometheus.io/docs/alerting/configuration/:
> A route block defines a node in a routing tree and its children. Its
> optional configuration parameters are inherited from its parent node
> if not set.
Also, add tests for:
- inheriting a …
=> Allow route receiver to be inherited

api.go, provider/boltmem/boltmem.go
@beorn7 @mattbostock 
This addresses the next iteration of too-much-serialization issues by simply adding an in-memory cache.
For the future, where we'll be looking at thousands of silences, we'll want to index silences in a smarter way.
We were also decoding all silences twice by accident – oops.
=> Add silence cache in front of BoltDB

provider/mesh/state.go, provider/mesh/state_test.go
This changes the end timestamp for unstarted silences to the
start timestamp so the silence remains valid by not having the end
time before the start time.
@beorn7 @brian-brazil
=> provider/mesh: fix end timestamp for unstarted silences

config/notifiers.go
Going over the notifier's code noticed that the config name was set to slack in the webhook unmarshaler function.
=> Updated webhook notifier config name in UnmarshalYAML.

main.go, provider/mesh/peer.go, provider/mesh/peer_test.go, provider/mesh/state.go, provider/mesh/state_test.go
This change adds snapshotting to the silences and notification infos
providers. Snapshots are created periodically and on shutdown. They are
loaded into memory on startup.
Periodic snapshotting is run right after garbage collection.
@beorn7
=> provider/mesh: implement snapshotting

provider/boltmem/boltmem.go, test/acceptance/send_test.go
Initial testing has shown BoltDB in plain usage to be a bottleneck
at a few thousand alerts or more (especially JSON decoding.
This commit actually makes them purely memory as a temporary solution.
@mattbostock reopened
=> provider/boltmem: make alerts purely in-memory.

circle.yml
I have also updated docker images `latest` tags to match the `v0.3.0`.
@fabxc
=> circleci : fix missing regex update for v-prefiexed tags

notify/notify.go
This addresses the misleading error messages reported in #282
Explanation: https://github.com/prometheus/alertmanager/issues/282#issuecomment-237784895
Fixes #282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prometheus/alertmanager/446)
=> notify: always check context before retrying

notify/impl.go
Hi:
I found a bug in v0.3.0 when i testing. 
When AM send mail it always log "unexpected server challenge".
I think fromServer sometime like "username:", but the code compare like this "Username:"
Maybe password the same issue.
Testing mail server: "smtp.163.com:25"
Am i correct?
```
gofile: impl.go 
line: 949 
switch string(fromServer) {
case "Username:"
return []byte(a.username), nil
case "Password:"
return []byte(a.password), nil
default:
return nil, errors.New("unexpected server challenge")
}
```
see #450
=> Modify SMTP login auth bug.

.promu.yml, api/api.go, cmd/alertmanager/main.go, dispatch/dispatch.go, dispatch/dispatch_test.go, dispatch/route.go, dispatch/route_test.go, inhibit/inhibit.go, inhibit/inhibit_test.go, ui/web.go
This commit packages up individual modules and removes the top-level
main package.
Aligns the rough structure with Prometheus and first step to allow us running several AMs in the same binary for better e2e tests.
=> *: restructure package tree

cmd/alertmanager/main.go, dispatch/dispatch.go, inhibit/inhibit.go, notify/impl.go, notify/notify.go, notify/notify_test.go
Move hard to read backwards declared pipeline approach to a more 
_in order_ approach with more detailed interfaces. Initially proposed by
@fabxc in #382.
Goal of this refactor is to have notification providers (pagerduty, slack, 
etc.) return errors that won't recover (eg. wrong api token) and the retry
functionality to stop trying completely as the error won't recover unless
the config is changed.
There is still a bunch of things to be moved, renamed and other cleanup,
comments, etc., but I wanted to get some early feedback, whether this
is the sort of direction we want to go into. All comments welcome 😃
=> refactor notification pipeline

dispatch/dispatch.go, notify/notify.go, notify/notify_test.go
This adds context.Context to the return arguments of a Stage.
This is necessary to propagate modified contexts.
@brancz
depends on #463
=> notify: include context in Stage interface

dispatch/dispatch.go, dispatch/dispatch_test.go, nflog/nflog.go, notify/impl.go, notify/notify.go, notify/notify_test.go
@brancz 
This uses the first object of the new `nflog` package (separate PR which is the base of this one). As we built the pipeline per receiver on configuration load, there's no need to make these runtime dependencies.
After all, `context.Context` should not be used as a disguise for `interface{}` (or Python kwargs).
As a consequence, the fanout stage is now truly just executing stages in parallel, without knowledge about integrations.
Thought about where to draw the boundary. There are other values in the context too. We could also build a static pipeline as a new aggregation group gets created in the dispatcher. I figured a reasonably boundary would be that we build the pipeline on configuration load time and build static pipelines only based on the information we have at this point …
=> Reduce runtime context dependencies

cmd/alertmanager/main.go, nflog/nflog.go, notify/notify.go, notify/notify_test.go, test/acceptance/send_test.go, test/acceptance/silence_test.go
This commit replaces the previous NotifyInfo provider with the new
nflog package. It needs adjustments in the behavior of the deduping
stage.
The nflog stores notification digests per receiver per alert aggregation
group rather than one entry for alert per receiver. This drastically
reduces the number of entries and removes interference
across aggregation groups.
@brancz
=> *: integrate nflog

cmd/alertmanager/main.go, dispatch/dispatch.go, dispatch/dispatch_test.go
This adds the peer wait duration to the standard timeout to avoid
terminating a notification prematurely while being in failover
wait status.
Fixes #488 
@brancz @beorn7
=> *: consider mesh wait in notification timeouts

circle.yml
Reverts prometheus/alertmanager#496
Should have merge it in release-0.4 first and then merge release-0.4 into master.
=> Revert "Use golang-builder base image for tests in CircleCI"

notify/notify.go, silence/silence.go, silence/silence_test.go
compiling regex silence matchers on every query is expensive, therefore
caching them as soon as they are gossiped through the mesh
@fabxc 
a microbenchmark showed roughly a 80x improvement for precompiled regex vs. compiled on every use
=> silence: add cache for silence matchers

README.md
Removed the vendor experiment flag (it's obsolete now) and added the proper path to the main binary.
=> Fixed the go install command

cmd/alertmanager/main.go, silence/silence.go, silence/silence_test.go
This adds metrics for querying as it is done internally and critical. The create/modification actions are basically covered by the API handler instrumentation and would just bloat here.
@discordianfish
=> silence: add metrics

notify/impl.go, notify/notify.go, notify/notify_test.go, test/acceptance/send_test.go
notify: move resolved alert filtering to integration
Resolved alerts, even when filtered, have to end up in the
SetNotifiesStage, otherwise when an alert fires again it is ambiguous
whether it was resolved in between or not.
fixes #523
@fabxc @johto
=> notify: move resolved alert filtering to integration

inhibit/inhibit.go
There's a typo in InhibitRule.set, the defer keyword is missing.  Found with a -race build.
=> inhibitrule: defer Unlock to fix race

api/api.go
Previously errors would look like:
ERRO[0008] api error: {bad_data 0xc4201caae0}
source=api.go:534
Now they look like:
ERRO[0001] api error: bad_data: json: cannot unmarshal object into Go
value of type []*types.Alert  source=api.go:534
=> Improve logging of API errors.

config/notifiers.go, silence/silence.go, template/internal/deftmpl/bindata.go, ui/bindata.go
This fixes #559 by removing concurrent map writes to the matcher cache.
The cache was guarded by the Silence's main lock, which only used a
read-lock on queries.
The cache's get methods lazily loads data into the cache and thus
causing concurrent writes.
We just change the main lock to always write-lock, as we don't expect
high lock contention at this point and would have it in a dedicated
cache lock anyway.
@brancz
=> silences: fix concurrent cache writes

dispatch/dispatch.go
Discussion started at #574 
Add the `groupKey` information to the `alerts/groups` endpoint.
When having configured a webhook receiver it contains the `groupKey`. Adding the `groupKey` to the overview of alertgroups makes it possible to match the incoming webhook with groups reported back from the API.
=> add groupKey to alerts/groups API endpoint

notify/impl.go, notify/notify_test.go, test/acceptance/send_test.go
Fixes #591 
We we're actually testing the `len(res) == 0` condition in the tests so we didn't notice the problem, as we always filtered all alerts in the tests.
@fabxc @brian-brazil @alexsomesan
@ddewaele you mentioned in #591 that you would volunteer to test a fix. I'm pretty confident it works correctly now, but won't hurt to try in your environment.
=> notify: replace unfiltered with filtered alerts

test/acceptance.go
This fixes problems when running the acceptance tests in slow or CPU-starved
machines, as mentioned in #472.
=> Wait for test server to be ready before running tests

config/config.go
This fixes broken regexp rendering in the routing tree UI.
@beorn7
=> Add proper JSON marshaling of config regexps.

api/api.go, cmd/alertmanager/main.go
Prevent Alertmanager from panicking when the configuration cannot be
loaded.
Spotted in version 0.4.2:
INFO[0000] Starting alertmanager (version=0.4.2, branch=HEAD, revision=9a5ab2fa63dd7951f4f202b0846d4f4d8e9615b0)  source=main.go:84
INFO[0000] Build context (go=go1.7.3, user=root@45f28166fed1, date=20170117-13:50:50)  source=main.go:85
INFO[0000] Loading configuration file                    file=alertmanager.yml source=main.go:156
ERRO[0000] error: yaml: line 64: could not find expected ':'  source=api.go:115
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x401adb]
goroutine 1 [running]:
panic(0x83e240, 0xc42000e020)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*API).Update(0xc4200b20f0, …
=> Prevent panic on failed config load

Procfile, README.md, cmd/alertmanager/main.go, test/acceptance.go
Defaulting to the machine's MAC address fails
sometimes fails and causes a panic. Allow the user to
specify custom address to skip this so they can
run AlertManager.
Addresses #582 
@beorn7 @brancz @fabxc this is more or less a quick fix so that users can manually enter something while we decide how to handle this.
=> Only find MAC address if no command-line flag value given

template/template.go
This allows for using string replace inside templates.
e.g.:
```
{{ replace .GroupLabels.alertname "_" " " -1 }}
```
=> template: Add reReplaceAll function

api/api.go, cmd/alertmanager/main.go
The weaveworks mesh package reveals information about the current status
of the mesh network between alertmanager instances. This commit exposes
the current address and connection status of each instance connected to
the targeted alertmanager instance via the /status API endpoint.
=> api: Expose mesh status

dispatch/dispatch.go, dispatch/dispatch_test.go, dispatch/route.go, nflog/nflog.go, nflog/nflog_test.go, nflog/nflogpb/nflog.proto, notify/impl.go, notify/notify.go, notify/notify_test.go, types/match.go
Turn the GroupKey into a string that is composed of the matchers if the
path in the routing tree and the grouping labels.
Only hash it at the very end to ensure we don't exceed size limits of
integration APIs.
As described in #718 
@brian-brazil
=> *: switch group key to matcher serialization

cli/alert.go, cli/silence.go, cli/silence_add.go, cli/silence_expire.go, cli/silence_query.go, cli/utils.go
I was using the RunE method of cobra.Command which does things with an
error returned from a function. I doesn't seem possible to keep it from
printing usage every time, so I've make a wrapper to use the other
function.
=> Add command wrapper to handle printing errors for any subcommands Fixes #721

cmd/alertmanager/main.go
=> cmd: fix panic on empty peer string

test/acceptance/send_test.go, test/mock.go
This test reloads the Alertmanager to verify, that it properly keeps
state and sends notifications correctly across reloads.
=> test: add reload test

.promu.yml
golang.org/x/sys/unix is failing for the various
arm builds.
tested locally, once this succeeds on circleci I'm going to go ahead and merge it
=> Remove openbsd/arm builds

dispatch/dispatch.go
AlertStatus doesn't have json tag with the field name, so it's serialized into 'Status', and it's the only uppercase field in the alert object. Tag it with 'status' name for consistency
=> Serialize AlertStatus as 'status'

api/api.go
When there are no alerts to return the api endpoint `/alerts` should
return:
```
{
"status": "success",
"data": []
}
```
instead of
```
{
"status": "success",
"data": null
}
```
=> Init result slice to prevent /alerts returning `null`

config/config.go
In relation to #356. 
`Continue` was incorrectly used in the Alertmanger configuration's root route. 
The lack of error here is misleading as `continue` is not inherited by the sibling routes.
=> Throw error when continue in route root of Alertmanager config

types/types.go
Read locks are used, which will cause panics @fabxc @stuartnelson3 
```
fatal error: concurrent map read and map write
goroutine 58 [running]:
runtime.throw(0x9fdd14, 0x21)
/home/lukasz/usr/go/src/runtime/panic.go:596 +0x95 fp=0xc42058e730 sp=0xc42058e710
runtime.mapaccess2_fast64(0x946e20, 0xc4201472f0, 0x24e4121619386f95, 0xffffffffffffffff, 0xc42058e798)
/home/lukasz/usr/go/src/runtime/hashmap_fast.go:168 +0x1b2 fp=0xc42058e758 sp=0xc42058e730
github.com/prometheus/alertmanager/types.(*memMarker).SetSilenced(0xc42014cb80, 0x24e4121619386f95, 0x0, 0x0, 0x0)
/home/lukasz/work/go/src/github.com/prometheus/alertmanager/types/types.go:115 +0x92 fp=0xc42058e7a8 sp=0xc42058e758
github.com/prometheus/alertmanager/notify.(*SilenceStage).Exec(0xc4201d8620, 0xc7a360, 0xc4200f3bf0, 0xc4200caf40, …
```
=> Use proper locks when modifying alert status

types/match.go
When user creates a new silence with regex match it's left to the user to anchor it, which is not consistent with Prometheus regex handling (promql/functions.go#L818).
CC @stuartnelson3
=> Anchor silence regex rules

ui/web.go
The commit [1] introduced the `cache-control` header field with the value `no-cache`. This enforces any cache to revalidate. Apparently this does not prohibit *FireFox* from caching the assets. `no-cache, no-store, must-revalidate` does by prohibiting to even save anything of the request.
[1] c3850708c1f31aad1db9cda355698ecdd4755e39
@stuartnelson3 @w0rm Did you had any issues with this on Chrome, Safari, Opera, Netscape, ...?
=> Update cache control for web assets

.travis.yml, cmd/alertmanager/main.go, vendor/github.com/weaveworks/mesh/connection.go, vendor/github.com/weaveworks/mesh/connection_maker.go, vendor/github.com/weaveworks/mesh/lint, vendor/github.com/weaveworks/mesh/local_peer.go, vendor/github.com/weaveworks/mesh/overlay.go, vendor/github.com/weaveworks/mesh/peer_name_hash.go, vendor/github.com/weaveworks/mesh/peer_name_mac.go, vendor/github.com/weaveworks/mesh/router.go, vendor/github.com/weaveworks/mesh/status.go, vendor/github.com/weaveworks/mesh/surrogate_gossiper.go, vendor/github.com/weaveworks/mesh/token_bucket.go, vendor/vendor.json
A general update that's probably in order. Also mesh logs are now emitted at the debug level.
=> Update mesh and add it to debug logging

vendor/github.com/Sirupsen/logrus/CHANGELOG.md, vendor/github.com/Sirupsen/logrus/README.md, vendor/github.com/Sirupsen/logrus/alt_exit.go, vendor/github.com/Sirupsen/logrus/doc.go, vendor/github.com/Sirupsen/logrus/entry.go, vendor/github.com/Sirupsen/logrus/exported.go, vendor/github.com/Sirupsen/logrus/formatter.go, vendor/github.com/Sirupsen/logrus/json_formatter.go, vendor/github.com/Sirupsen/logrus/logger.go, vendor/github.com/Sirupsen/logrus/logrus.go, vendor/github.com/Sirupsen/logrus/terminal_appengine.go, vendor/github.com/Sirupsen/logrus/terminal_bsd.go, vendor/github.com/Sirupsen/logrus/terminal_linux.go, vendor/github.com/Sirupsen/logrus/terminal_notwindows.go, vendor/github.com/Sirupsen/logrus/terminal_solaris.go, vendor/github.com/Sirupsen/logrus/terminal_windows.go, vendor/github.com/Sirupsen/logrus/text_formatter.go, vendor/github.com/Sirupsen/logrus/writer.go, vendor/vendor.json
Same deal as https://github.com/prometheus/prometheus/pull/2733 but for alertmanager this time.
=> updated logrus so alertmanager can build on Solaris/Illumos

cli/root.go
`alertmanger` => `alertmanager`
=> Fixing a typo in amtool help text

README.md
Instead of targeting the latest build, which could be any PR, we should target current master results.
=> Update build status to target master

api/api.go, notify/notify.go
Do not expose resolved alerts on the /alerts endpoint. Do not send
resolved alerts to receivers if the alerts have never been fired before.
This is related to #815, but does not resolve the specified issue.
=> Do not expose resolved alerts & do not send resolved if never firing

silence/silence.go, silence/silence_test.go
Instead of setting endsAt to startsAt we can set both to now. Thereby
the Silence will get the expired state by default.
Fixes #783.
=> Expire pending silence and move to expired state

config/config.go, config/config_test.go, config/notifiers.go, config/testdata/conf.empty-fields.yml
=> Omit empty config fields and show regex upon re-marshalling to elide secrets

dispatch/dispatch_test.go, dispatch/route.go, dispatch/route_test.go, types/types_test.go
This fixes https://github.com/prometheus/alertmanager/issues/881
Also add some unit tests
=> Make sure Matchers are always ordered

.travis.yml, Makefile, ui/app/CONTRIBUTING.md, ui/app/Makefile
Instead of checking in binaries like `ui/bindata.go` and
`template/internal/deftmpl/bindata.go` into git, we generate them
whenever `make build` is run. If they already exist, we only regenerate
them if they are outdated.
For folks that only want to make back-end changes `ui/app/script.js` is
checked in, so they do not have to build the front-end.
`make build` will use Docker to build the front-end. If someone prefers
to install all the dev dependencies on their local machine instead, one
can add the `NO_DOCKER=true` flag.
Happy for any feedback, especially `GNU Make` specific.
I will rebase this PR once #789 is merged into Master.
=> Improve front-end build process

notify/impl.go
Using https://github.com/prometheus/prometheus/pull/2447/files as an example, this adds a user agent for Webhook requests.
This is the first time I've written code in go, so please let me know what I can fix up.
It's likely that the same user agent could be used for the other notifiers but for now I have only added this to the webhook notifier.
@stuartnelson3
=> Add User-Agent for webhook requests

config/config.go, config/config_test.go, config/notifiers.go, config/testdata/conf.victorops-default-apikey.yml, config/testdata/conf.victorops-no-apikey.yml
If the idea is to setup one victorops_receiver per team or something like that, this would allow the user to not repeat the API key for each of them.
Since the API key is the same for all integrations, this seemed like a good idea.
I didn't added a test for that because there is none already, but I can add new tests if you want :)
Thanks for the awesome tools btw 🍻
=> Added possibility to have a global victorops api_key

config/config.go, config/config_test.go, config/notifiers.go, config/testdata/conf.empty-fields.yml, config/testdata/conf.good.yml, notify/impl.go
Some MTAs insist that they be greeted with a fully qualified domain
name. The default provided by the net/smtp library, "HELLO localhost",
is not sufficient and will result in rejected messages.
This changeset adds a new configuration option that allows the
alertmanager to do its job in such an environment.
Considering that this is a rather trivial PR, I am following the guidelines for contributing by addressing @stuartnelson3.
=> Support for custom SMTP hello string

cmd/alertmanager/main.go, template/internal/deftmpl/bindata.go
This adds a check for `meshListen != ""` around the waitFunc code as we
have around the other mesh-related code parts above.
Fixes https://github.com/prometheus/alertmanager/issues/914
=> Fix crash when no mesh router is configured

config/notifiers.go, notify/impl.go
Hi.
Thank you for your effort.
I use Alertmanager with Slack.
When I received messages, I wanna use this option for slack.
**link_names**
You can check this option what is.
https://api.slack.com/methods/chat.postMessage
I updated some codes a little bit.
**Usage**
```yaml
slack_configs: 
link_names: true
```
I think this options is so important for alerting. 
I think most people want to notify them to their owners when they receive messages on Slack.
Thanks.
=> When I notify alert to slack, I want to use this option.

examples/webhook/echo.go
This is just a small addition for better debugging of notifications send
by Alertmanager.
=> Add current time to go webhook standard output

api/api.go, dispatch/dispatch.go
Alert fingerprint is already provided as the value of status.inhibitedBy[] attribute that inhibited alerts have, but there's no way to get back to the alert that's inhibiting it as the fingerprint is not exposed.
I'm not sure if using fingerprints is desirable, but that's currently the value of `inhibitedBy` @stuartnelson3 
The goal here is to be able to link back from inhibited to inhibiting alert based on the API response, which isn't currently doable.
=> Expose alert fingerprint in the API

README.md
Amtool has been bundled with alertmanager for a while now. It's probably
far past the acceptable time to add information to the readme
=> Provide README information for amtool

cmd/alertmanager/main.go
Rather than creating a new logger for sub components, start with the base logger.  The preserves logging options passed in on the CLI.
=> Use logging options consistently for all components #967

ui/app/Makefile
=> macOS requires the template to be at the end

api/api.go
addresses #812 
@fabxc @brancz @mxinden opinion on using `Fingerprint`?
=> Sort alerts by their fingerprint

Makefile, README.md
While working on promtool and prometheus I often went back and forth commenting out binaries in the `.promu.yml` file in order to only rebuild the binary I wanted to rebuild. The alertmanager repo also builds two binaries. 
In this pr: https://github.com/prometheus/promu/pull/77 I added the option to pass a binary name to promu's build function. This is controlled by setting the `BINARIES` var.
For example: 
```
$make build BINARIES=amtool
>> building binaries
>   amtool
```
In this PR we simply pass `BINARIES` to promu. If it's not set, promu will build all binaries from the YAML file as normal.
```
$make build
>> building binaries
>   alertmanager
>   amtool
```
=> allow a binary name to be passed to make build

silence/silence.go, silence/silence_test.go
Calling gossip.GossipBroadcast() will cause a deadlock if
there is a currently executing OnBroadcast* function.
See #982
=> silences: avoid deadlock

silence/silence.go, silence/silence_test.go
This will fix the bug of resync deleted silences due to the state of other peers. More context on https://github.com/prometheus/alertmanager/issues/996
=> Ignore expired silences OnGossip

notify/impl.go
* Don't send parts with empty templates.
* Add a MIME-Version: 1.0 header.
* Place text/html part last, as parts are supposed to be in increasing preference order.
This is a follow-up fix to #934.
=> Fix multipart email implementation

cli/check_config.go
Not sure if it's just me, but i had to look into the code to understand that check-config:
1) is used to validate alertmanager config files, and not validate amtool config files. It became clear after running `amtool check-config -h`, but it was not clear when I executed `amtool -h`, so I've changed the short description.
2) that I had to pass the config file as a cmd argument, and that it could be one or more. Changed the Use text to give more context on that.
what you think @stuartnelson3 ?
=> Improve amtool check-config use and description text

dispatch/dispatch_test.go
This fixes one of the (many) race conditions in the dispatch tests. As there are quite a few I was going to tackle them one by one. This one was a fairly obvious one.
@stuartnelson3 @fabxc
=> dispatch: fix race condition in dispatch test

cmd/alertmanager/main.go, silence/silence.go, silence/silence_test.go, types/types.go
This adds metrics that look like this:
```
alertmanager_alerts_count{state="active"} 6
alertmanager_alerts_count{state="suppressed"} 0
alertmanager_silences_count{state="active"} 1
alertmanager_silences_count{state="expired"} 1
alertmanager_silences_count{state="pending"} 0
```
This can be used to monitor alertmanager's usage and validate that
alertmanagers in a mesh have a similar number of silences and alerts.
=> silence|alerts: add metrics about current silences and alerts

cmd/alertmanager/main.go
The metric that this PR introduces is helpful in order to understand which position in the mesh an Alertmanager instance believes to be in. If a number is non unique, that means that there is a problem with the peers connections in the mesh.
@stuartnelson3 @fabxc
=> add metric of alertmanager position in mesh

notify/notify.go
Closes #928 
This works but perhaps we could add a utility method of some kind to avoid duplication?
=> Initialise notifications_total and notifications_failed_total

inhibit/inhibit.go, vendor/github.com/oklog/oklog/LICENSE, vendor/github.com/oklog/oklog/pkg/group/group.go, vendor/vendor.json
Fixes #1014
@fabxc @stuartnelson3
=> Fix inhibit race

cli/silence_add.go
I had a system where amtool would segfault on startup because of
that.
=> cli/silence_add: don't ingore errors when getting current user

CONTRIBUTING.md
Usage questions should not be discussed via GitHub issues but instead in
the Prometheus users Google group. Redirecting users from GitHub issues
to the Prometheus users Google group is happening quite often. To make
things easier for maintainers and users this patch adds a note to
CONTRIBUTING.md in the repo. When opening up a new issue in GitHub,
there is a link to the CONTRIBUTING.md file at the top of the dialog.
@stuartnelson3 what do you think?
=> Add usage question note to CONTRIBUTING.md

notify/notify.go, notify/notify_test.go, types/types.go
This fixes the race condition reported in #1013.
As I was fixing this, I noticed, that I couldn't find where or if this is actually used anywhere, as it's not rendered in the json response, and otherwise not used at all either. If we can confirm this we can probably remove it entirely. I know there was some work around this relatively recently, but don't remember exactly anymore what.
Fixes #1013
@stuartnelson3 @fabxc @mxinden
=> Remove .WasInhibited and .WasSilenced fields of Alert type

notify/impl.go
successfully tested with:
```yaml
receivers:
- name: victorops-test
victorops_configs:
- routing_key: somekey
message_type: "{{ .CommonLabels.severity | toUpper }}"
```
fixes #1018
=> Allow template in victorops message_type field

api/api.go
refs #1034
I feel like it would be better to rename the form parameter to something else, since it's not only silenced alerts anymore... what do you folks think?
=> also hide inhibited alerts

notify/impl.go
Couple things fixed
- title was added as a parameter before the truncation
- title limit was wrong, it is 250 characters
- message limit was wrong, it is 1024 characters
- url has a limit of 512 and was not truncated
Limits can be checked at https://pushover.net/api#limits
I've created a pushover account to do an end to end test, and truncation worked perfectly.
=> Fix pushover limits (title, message, url)

notify/impl.go
[OpsGenie API](https://docs.opsgenie.com/docs/alert-api-deprecated) has a limit of 130 characters to a message.
=> Add limit to OpsGenie message

notify/impl.go
Logging truncation to help to debug, also be consistent that all other truncations do log.
=> Add logging to stateMessage truncation

notify/impl.go
Closes #902
The [OpsGenie Web API](https://docs.opsgenie.com/docs/web-api) (referred to as 'old' below) is deprecated.
This upgrades Alertmanager to the [OpsGenie REST Alert API](https://docs.opsgenie.com/docs/alert-api) (referred to as 'new' below).
----
* Use new paths.
* Use new auth header.
* Adjust response code logic.
* [Docs](https://docs.opsgenie.com/docs/response#section-response-codes)
* Expand retry to include new "429 - Too Many Requests" throttling.
* We no longer need to handle closing an already closed alert, as such a request is now asynchronous.
* No changes in config.
* New integration still uses alert alias, so it is backwards compatible.
* i.e. you can open a request on the old API and close it on the new API.
* Open an alert with Alertmanager, then close with …
=> Upgrade OpsGenie notifier to v2 API

notify/notify.go, test/acceptance/send_test.go
Fixes https://github.com/prometheus/alertmanager/issues/1063
=> Fix notifications for flapping alerts

cmd/alertmanager/main.go
Similar to [Prometheus](https://github.com/prometheus/prometheus/blob/bf6db1bc3b6715a61f0485bcb973ecd76e6b0ce8/cmd/prometheus/main.go#L74-L75) it's often useful to enable mutex profiling in load and correctness testing. I'm open to other methods of enabling it, but thought it makes sense to do it consistently with Prometheus.
@stuartnelson3 @juliusv @josedonizetti
=> Allow enabling mutex and block profiles

notify/impl.go
@stuartnelson3 
Similar to #1038 
Makes the VictorOps `routing_key` field templatable. My use case involves using a label in the alert common labels to configure the VictorOps routing key. Ideally, this allows a single receiver to route all VictorOps bound alerts, as opposed to the one receiver per routing key (team?) that is required today.
```yaml
receivers:
- name: victorops-test
victorops_configs:
- routing_key: "{{ .CommonLabels.team }}"
```
=> Allow template in victorops routing_key field

api/api.go, notify/notify.go, silence/silence.go, silence/silence_test.go
Clean up silence constants duplicated; I chose to keep the ones declared inside the types package because it's where the silence struct is also declared. 
@stuartnelson3 @brancz
=> Refactor silence constants

cli/silence_add.go
The time.ParseDuration function refused to parse them with [the reason](https://github.com/golang/go/issues/11473#issuecomment-116964364) is that a day
can be shorter or longer than 24 hours. But they are already [accepted in
Prometheus range query](https://github.com/prometheus/prometheus/blob/master/promql/parse.go#L1131-L1140) and a custom parser is included in Prometheus
common package so there's no reason amtool cannot use that.
This will be handy in cases you need to create silence for longer periods,
which are unfortunately common.
=> amtool - Allow 'd', 'w', 'y' to be specified at time suffix when creating silence

config/config.go, config/config_test.go, config/notifiers.go, config/testdata/conf.empty-fields.yml, config/testdata/conf.good.yml, doc/examples/simple.yml, notify/impl.go
This PR renames configuration from 3 different notifiers to make it consistent with others. Basically, global configurations will be named `<notifier>_api_url`, and local configurations per notifier `api_url`. 
This are **breaking changes**.
Fixes https://github.com/prometheus/alertmanager/issues/680 and https://github.com/prometheus/alertmanager/issues/875
@stuartnelson3 @brancz @brian-brazil @juliusv
=> Fix config name inconsistency

types/types.go
The `(silence) Delete()` method was added at this commit https://github.com/prometheus/alertmanager/commit/c0103dd8c61a9e9e57a3c888a9ae579e24a09b8d a code related to the old silence provider, that was deleted at this commit https://github.com/prometheus/alertmanager/commit/3b5dfa8aba9db19c4c175360d69cce8f0c3d9b74, and now it not used anymore.
But more importantly for me is that the semantically now this method should be called `Expired()` https://github.com/prometheus/alertmanager/blob/master/silence/silence.go#L493, maybe instead of removing I should just rename it.
what do you think?
@stuartnelson3 @brancz
=> Remove old silence code

notify/impl.go, notify/impl_test.go
Adding tests to retry logic. To extract the retry logic from Pushover, VictorOps, and OpsGenie I've removed some debug logging messages, but the idea is to add it back in a next PR and make it consistent through notifiers, right now some notifiers log in case a diff status was returned and some don't.
@stuartnelson3
=> Add tests to retries

config/notifiers.go, notify/impl.go
Now that Alertmanager is on the OpsGenie v2 API we can use the "Priority" field.
This is a non-mandatory field [described as follows](https://docs.opsgenie.com/docs/alert-api#section-create-alert):
> Priority level of the alert. Possible values are P1, P2, P3, P4 and P5. Default value is P3.
Further information about this field can be found [here](https://docs.opsgenie.com/docs/priority-field), including information on validation:
> If an unknown value is assigned or the tool does not carry a priority information, the alert will have the default priority value, P3.
With the above in mind, this PR does not validate the value for this field. Though I could add validation if so desired.
=> Support OpsGenie Priority field

api/api.go, api/api_test.go
We changed the alerting filtering logic to be consistent with prometheus https://github.com/prometheus/alertmanager/issues/1060. 
This PR makes the same change to the silence filtering, and extract the filtering logic which is equal no matter if an alert, or silence. This way is easier for a new change to be effective cross alertmanager, without having to change two different places.
=> Fix silences negative filtering

notify/impl.go
#1061 broke the OpsGenie Teams field.
The structure of this field has in fact changed between v1 and v2.
[OpsGenie Documentation](https://docs.opsgenie.com/docs/alert-api#section-create-alert)
* No team config set. ✓
* One team value set. ✓
* Multiple team values set. ✓
----
I apologise for missing this in #1061.
=> Fix OpsGenie Teams field

notify/impl.go
#1061 broke the OpsGenie Tags field.
The structure of this field has in fact changed between v1 and v2.
[OpsGenie Documentation](https://docs.opsgenie.com/docs/alert-api#section-create-alert)
I have used strings.Split to preserve functionality without changing config.
* No tag config set. ✓
* One tag value set. ✓
* Multiple tags set. ✓
----
I apologise for missing this in #1061.
=> Fix OpsGenie Tags field

README.md
It is `comment_required` in code:
https://github.com/prometheus/alertmanager/blob/master/cli/silence_add.go#L118
=> amtool - fix typo in README for comment_required config

notify/impl.go
From the documentation at
https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2
```
payload.source: required string
The unique location of the affected system, preferably a hostname or FQDN.
```
Sending the generatorURL isn't technically the
affected system, but an event sent to PD can
encompass multiple alerts. The generatorURL seems
like the correct way to help users debug this.
addresses #1116
=> Send the prom gen url as alert source

inhibit/inhibit.go
The race detector has discovered a race:
```
WARNING: DATA RACE
Read at 0x00c42016fd40 by goroutine 96:
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).Stop()
/home/brancz/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:132 +0x4d
main.main.func8()
/home/brancz/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:323 +0x5ae
main.main.func9()
/home/brancz/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:386 +0x68
Previous write at 0x00c42016fd40 by goroutine 53:
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).Run()
/home/brancz/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:106 +0xd9
Goroutine 96 (running) created at:
main.main()
/home/brancz/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:379 …
```
=> inhibit: Fix race in stopping inhibitor

Dockerfile, circle.yml
=> package amtool in docker container

cli/silence.go, cli/silence_add.go, cli/silence_import.go
This command read silences data from a query JSON output and import to
alertmanager. It allows `amtool` to be used as a backup/restore tool for
silences, i.e. fix #1000
Backup / export:
```
amtool silence -o json > silences.json
```
Restore / import:
```
amtool silence import silences.json
```
This adds new silence one by one and will be slow if you have thousands of silences but alertmanager API doesn't allow multiple silences in POST so ¯\\_(ツ)_/¯
=> [amtool] - Add a new `silence import` command

config/notifiers.go, config/notifiers_test.go
Since alertmanager will fail silently when trying to send to a schemaless URL, provide a way to check that a URL is properly formatted in alertmanager
=> Adding check for webhook's URL formatting

notify/impl.go
The PagerDuty Events API (v1), used by integrations with monitoring tools, will continue to be supported. There are currently no plans to deprecate, end support for or sunset it.
The end-of-support notice cited in the log message removed applies only to the *REST API* version 1, which PagerDuty will no longer support as of February 2018, but which Prometheus does not use.
=> Removed incorrect end-of-support warning

nflog/nflog.go, nflog/nflog_test.go
It's very hard to prove, but I think this may fix #1037. Even if not, this makes it a lot easier to reason about the modification of `gossipData`, as it is not modified in place, but rather copied and then modified, and then the entire variable is replaced. That way we can be sure that nothing within the `Merge` and `mergeDelta` functions modify the receiver itself.
What I do not know is how this may impact performance of the system. Fundamentally we don't know what Alertmanager can handle today, so it's hard to tell how much worse this is.
I have tried to reproduce the race originally reported in #1037, but haven't been able to. It's questionable what this means, as it was not easy to reproduce it even without this patch.
@stuartnelson3 @grobie @fabxc
=> nflog: Copy and replace gossipData instead of modifying it in place

cli/silence.go, cli/silence_update.go
This adds a new command, `update` (and also its alias, `extend`), to update
existing silence in Alertmanager. User can use this command to update the
expiration or comment on existing silences. The API already support this
so I only expose the same functionality to amtool.
Don't allow update CreatedBy field as it is "Created" not "Updated", so
we should keep the original author.
Sample usage:
```
$ ./amtool silence add -e 2h -c test foo=bar
2c9ff0c4-9133-4c82-b4a1-01806c3a6673
$ ./amtool silence query foo=bar
ID                                    Matchers  Ends At                  Created By  Comment
2c9ff0c4-9133-4c82-b4a1-01806c3a6673  foo=bar   2017-11-27 08:49:04 UTC  @binh       test
$ ./amtool silence extend -e 4h -c 'updated test' 2c9ff0c4-9133-4c82-b4a1-01806c3a6673
ID …
```
=> [amtool] - Add new command to update silence

cli/silence_query.go
As part of our workflow we find it quite useful to be able to query alerts that will expire soon, so that we can investigate whether they should stay silenced or be extended before we get a flood of alerts. 
This PR adds such functionality to amtool so that a user can do something like:
```
amtool silence query --within 8h
```
which will give all the silences that expire within the next 8h.
=> Added ability to query for silences that will expire soon

cmd/alertmanager/main.go
Found while troubleshooting my setup, no information regarding the mesh was logged. This has probably felt through the cracks when fixing #1040.
=> Fix logging for the mesh component

notify/notify.go, notify/notify_test.go
- `BuildPipeline` does not use the `*Inhibitor` fully. Only cares about the fact that it implements a `Muter`.
- `marker` is not used inside the `InhibitStage` anymore
=> Refactor inhibit stage

config/notifiers.go, notify/impl.go
Had a go at implementing https://github.com/prometheus/alertmanager/issues/731
> The Slack notification API has added a fields parameter that allows for some additional formatting [1]. It looks like the work was started to add this additional parameter [2], but the feature was never finished so that it was available.
>[1] https://api.slack.com/docs/message-attachments#fields
>[2] https://github.com/prometheus/alertmanager/blob/v0.5.1/notify/impl.go#L485-L490
=> Add Slack additional "fields" to notifications 

ui/web.go
This partially addresses #991. Regarding the readiness probe, I'm not sure that we can reliably evaluate whether the mesh is ready or not. Thoughts?
=> Add /-/healthy endpoint

notify/impl.go
The tmpl() call was removed when migrating to
support pd v2 events api.
=> Template secret keys for pagerduty notifier (#1168)

cli/silence_add.go
The expanded duration parsing (support for w/d/y) was removed in the migration to kingpin. This adds it back.
Fixes #1183
=> Re-introduce prometheus durations in amtool silence creation

cli/silence_update.go
Possibly another regression introduced by #976 . We use the wrong
variable to update comments in the `amtool silence update` command
which causes us to fail silently. This fixes that.
=> Fix updating silence comments

dispatch/dispatch.go, test/acceptance/send_test.go
Fix for #427.
This change decreases the repeat_interval parameter from 5s to 4.9s to
make sure that the alerts are effectively sent after 5 seconds.
The workflow is:
- The dispatcher flushes the alerts at t0, sends the notification and
marks the notification log at t0+epsilon.
- The dispatcher flushes the alerts at t1, t2, t3 and t4 and doesn't
send the notifications as expected.
- At t5, the dispatcher flushes the alerts because current_time - (t0+epsilon)
is less then repeat_interval.
If repeat_interval is exactly 5s, there is a little chance that it is
greater than current_time - (t0+epsilon).
=> Fix flaky TestBatching acceptance test

dispatch/dispatch.go, nflog/nflog.go, notify/notify.go, notify/notify_test.go
=>  Don't notify resolved alerts if none were firing 

provider/mem/mem_test.go
@stuartnelson3 Take a special look into `TestAlertsSubscribe` as it involves concurrency. Think I was able to validate the behavior well without writing a flap test.
Thanks.
=> Add tests to memory provider

api/api.go, types/types.go, types/types_test.go
At first, I wanted to validate if a silence is expired on https://github.com/prometheus/alertmanager/blob/master/silence/silence.go#L347, but expired silences are part of the internal logic https://github.com/prometheus/alertmanager/blob/master/silence/silence.go#L492, so I've just added a validation to the set silences API. I don't think it's useful for someone to create an expired silence from the UI/amtool.
=> Add expired silence validation

nflog/nflogpb/set.go, nflog/nflogpb/set_test.go, notify/notify.go, notify/notify_test.go, test/acceptance/send_test.go, test/collector.go
After the initial notification has been sent, AlertManager shouldn't notify the
receiver again when no new alerts have been added to the group during
group_interval.
This change also modifies the acceptance test framework to assert that no
notification has been received in a given interval.
Fixes #1195.
cc @brian-brazil, @stuartnelson3, @brancz. Since https://github.com/prometheus/alertmanager/pull/703 (meaning 0.6.0), AlertManager sends notifications either when a new alert is firing or when a new alert gets resolved. Brian suggested in #1195 that it shouldn't in the latter case.
=> Notify only when new firing alerts are added

notify/notify.go
I am getting errors like this:
```
level=error ts=2018-01-25T11:14:09.509893874Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"victorops\" due to unrecoverable error: unexpected status code 404"
level=error ts=2018-01-25T11:14:11.027745774Z caller=notify.go:302 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"victorops\" due to unrecoverable error: unexpected status code 404"
level=error ts=2018-01-25T11:14:11.027791108Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"victorops\" due to unrecoverable error: unexpected status code 404"
level=error ts=2018-01-25T11:14:11.038292052Z caller=notify.go:302 …
```
=> improved error when victorops fails

cmd/alertmanager/main.go
This change adds 2 new metrics for the mesh:
* alertmanager_peer_connection, state of the connection between the
Alertmanager instance and a peer.
* alertmanager_peer_terminations_total, total number of terminated
connection.
It also moves the gathering of the alertmanager_peer_position metric
outside of the meshWait() function so that the metric is computed
accurately even when no alerting group fires.
Fixes #1219.
=> Add mesh metrics

notify/impl.go, notify/impl_test.go
See #1223, looks like OpsGenie now sometimes returns a 422 when you
don't specify a team. This change cleans up the JSON output and
add a few unit tests.
=> Fix OpsGenie notifier and add unit tests

api/api.go
As far as I can tell Prometheus may send a time stamp in the future for the end time of an alert meaning AM shouldn't automatically mark this alert.
=> Fixes AM wrongly counting alerts with EndTimes in the future as resolved

config/config.go, config/config_test.go, test/acceptance/send_test.go, test/acceptance/silence_test.go
Setting one of these parameters to a zero value doesn't make sense
semantically and causes high CPU usage.
Fixes #1114.
=> Forbid 0 value for group_interval and repeat_interval

config/config.go, config/notifiers.go, config/notifiers_test.go, notify/impl.go, notify/impl_test.go
For issue #1218
Changes:
1. change `weChatCreateMessage` and `weChatCloseMessage ` to  `weChatMessage `
2. cache WeChat AccessToken with` accessTokenAt`
3. code refactor & format.
Test config:
```
global:
resolve_timeout: 5m
wechat_api_secret: 'xxxx'
route:
group_by: ['alertname']
receiver: 'wechat'
receivers:
- name: 'wechat'
wechat_configs:
- corp_id: 'xxxx'
to_party: '1'
agent_id: 'xxx'
```
Work with this config.
=> Fix WeChat issue

cmd/alertmanager/main.go
This code was used for to get the logs from the mesh library.
=> cmd: remove unused code

cmd/alertmanager/main.go
These functions were used with weaveworks/mesh,
but are no longer needed with memberlist.
=> Remove unused functions for mesh

silence/silence.go, silence/silence_test.go
TestStateMerge() was skipped because of a typo. Fixing the name revealed
that the test itself needed to be updated following the switch to the
memberlist library.
=> silence: fix skipped test

cluster/cluster.go, cmd/alertmanager/main.go
This was already changed in #1225 but dropped when migrating from the mesh library to memberlist.
=> cluster: gather alertmanager_peer_position all the time

Makefile, dispatch/dispatch_test.go, test/acceptance.go, test/collector.go, test/mock.go
This change enables race detection when running the tests. It also fixes
a couple of existing race conditions.
Inspired by https://github.com/prometheus/prometheus/pull/3884 from @krasi-georgiev :smile:
=> test: enable race detection

cli/utils.go
Sets User object in alertmanager url to enable amtool to work with basic auth for use with proxies. Fixes #1028.
=> Set User object in alertmanager url.

config/config.go
Following feedback from https://github.com/prometheus/docs/pull/988.
=> config: set global SMTP hello to "localhost" by default

config/config.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x95057e]
goroutine 174 [running]:
github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/config.NewHTTPClientFromConfig(0x0, 0xc04207f560, 0xc042025df0, 0xc0421b29a0)
/go/src/github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/config/http_config.go:121 +0x3e
github.com/prometheus/alertmanager/notify.(*Wechat).Notify(0xc0423ff900, 0xbe3000, 0xc042469cb0, 0xc042004b48, 0x1, 0x1, 0xc0425f1b00, 0x0, 0x0)
/go/src/github.com/prometheus/alertmanager/notify/impl.go:874 +0x380
github.com/prometheus/alertmanager/notify.(*Integration).Notify(0xc0425f1ce0, 0xbe3000, 0xc042469cb0, 0xc042004b48, 0x1, 0x1, 0x1, 0x1, 0x0) …
```
=> fix panic cased by Wechat notifier

cluster/cluster.go, cmd/alertmanager/main.go, nflog/nflog.go, silence/silence.go, silence/silence_test.go
Fixes #1282.
The code could be refactored (in particular `marshalMeshEntry()` can be shared between silence and nflog) but I felt it could be done later.
I've also added new cluster metrics that were helpful when troubleshooting the issue.
cc @fabxc @stuartnelson3
=> Fix for #1282

dispatch/dispatch.go
Sort dispatched alert slice by `job` and `instance` labels, then rest. Addresses https://github.com/prometheus/alertmanager/issues/1178#issuecomment-362008207
No idea how to write a good test for this, sorry.
=> Sort dispatched alerts by job+instance then rest by default (#1178)

Makefile, api/api.go, cmd/alertmanager/main.go, ui/web.go, vendor/github.com/prometheus/client_golang/prometheus/counter.go, vendor/github.com/prometheus/client_golang/prometheus/desc.go, vendor/github.com/prometheus/client_golang/prometheus/doc.go, vendor/github.com/prometheus/client_golang/prometheus/gauge.go, vendor/github.com/prometheus/client_golang/prometheus/go_collector.go, vendor/github.com/prometheus/client_golang/prometheus/histogram.go, vendor/github.com/prometheus/client_golang/prometheus/http.go, vendor/github.com/prometheus/client_golang/prometheus/labels.go, vendor/github.com/prometheus/client_golang/prometheus/metric.go, vendor/github.com/prometheus/client_golang/prometheus/observer.go, vendor/github.com/prometheus/client_golang/prometheus/process_collector.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/registry.go, vendor/github.com/prometheus/client_golang/prometheus/summary.go, vendor/github.com/prometheus/client_golang/prometheus/timer.go, vendor/github.com/prometheus/client_golang/prometheus/untyped.go, vendor/github.com/prometheus/client_golang/prometheus/value.go, vendor/github.com/prometheus/client_golang/prometheus/vec.go, vendor/github.com/prometheus/common/route/route.go, vendor/vendor.json
This change is similar to https://github.com/prometheus/prometheus/pull/3862. It should probably wait for v0.15.0 to be out.
The following metrics are removed:
* http_request_duration_microseconds (Summary).
* http_request_size_bytes (Summary).
* http_requests_total (Counter).
And the following metrics are added instead:
* alertmanager_http_request_duration_seconds (Histogram).
* alertmanager_http_response_size_bytes (Histogram).
* promhttp_metric_handler_requests_in_flight (Gauge).
* promhttp_metric_handler_requests_total (Counter).
=> ui: replace deprecated InstrumentHandler()

cli/silence_add.go, cli/silence_update.go
- Change --expires/-e to --duration/-d
- Change --expires-on to --end
- Add --start
- `silence update` has no default duration value
- `silence update` now returns the ID of the newly created silence, instead of printing the ID for the old silence.
=> [amtool] update silence add and update flags

nflog/nflog.go, nflog/nflog_test.go, silence/silence.go, silence/silence_test.go
I've experienced the panics while investigating #1282: at that time, the data being passed to the decoder wasn't valid (good fuzz testing!). In normal conditions it shouldn't happen but I guess that it is still better to catch those nil pointers.
=> Fix potential panic in decodeState()

cli/silence_expire.go, client/client.go, client/client_test.go
Within alertmanager, expire is the term used,
since silences still "exist" but aren't in effect.
=> Rename silence API Delete() -> Expire()

inhibit/inhibit.go, inhibit/inhibit_test.go, provider/mem/mem.go, test/acceptance/inhibit_test.go
Update old alert with result of merge with new
On ingest, alerts with matching fingerprints are
merged if the new alert's start and end times
overlap with the old alert's.
The merge creates a new alert, which is then
updated in the internal alert store.
The original alert is not updated (because merge
creates a copy), so it is never marked as resolved
in the inhibitor's reference to it.
The code within the inhibitor relies on skipping
over resolved alerts, but because the old alert is
never updated it is never marked as resolved. Thus
it continues to inhibit other alerts until it is
cleaned up by the internal GC.
This commit updates the struct of the old alert
with the result of the merge with the new alert.
An alternative would be to always update the
inhibitor's internal cache of alerts …
=> Fix resolved alerts still inhibiting

.github/ISSUE_TEMPLATE.md
`-version` doesn't work as of 0.15-rc.1 so users should run `alertmanager  --version`
=> tell users opening issues to use alertmanager  --version

config/notifiers.go, config/notifiers_test.go, notify/impl.go
Resolves the comments on the PR [#1002](https://github.com/prometheus/docs/pull/1002) to update the documentation for Slack fields. Currently, any arbitrary key/value pairs can be defined; however, per the Slack documentation for defining fields [[1](https://api.slack.com/docs/message-attachments#fields)] only the properties `title`, `value`, and `short` can be defined with the first two being required for each field. This updates the Slack field configuration to only allow the aforementioned three properties as well as validates that both a title and value are defined for each property in the `yaml.Unmarshaler` interface. Moreover, this allows the value for `short` to be defined on a per-field basis.
=> Validate Slack field config and only allow the necessary input

notify/impl_test.go
=> notify: remove wechat unit test

cli/alert.go
- rename `expired` to `inhibited`
- order for `silenced` and `inhibited` was reversed (cf. https://github.com/prometheus/alertmanager/blob/master/client/client.go#L155-L160)
the API is not properly filtering responses, but that's for a different PR.
@simonpasquier
=> Update alerts argument order, rename expired to inhibited

api/api.go, cmd/alertmanager/main.go
With prometheus/prometheus commit
e114ce0ff7a1ae06b24fdc479ffc7422074c1ebe [1] Prometheus switches from
using `api/alerts` to `api/v1/alerts`. This commit is included starting
from Prometheus v0.17.0. As discussed on the prometheus-developers
mailing list [2] the deprecation period is long over.
[1] github.com/prometheus/prometheus/commit/e114ce0ff7a1ae06b24fdc479ffc7422074c1ebe
[2]
https://groups.google.com/d/msg/prometheus-developers/2CCuFTMbmAg/Qg58rvyzAQAJ
//CC @stuartnelson3  @brian-brazil
=> api: Deprecate `api/alerts` endpoint

api/api.go, api/api_test.go
Fixes #1359.
This change adds 2 new query filters to the /api/v1/alerts endpoint.
- active, filter out active alerts when set to 'false' (default: 'true').
- unprocessed, filter out unprocessed alerts when set to 'false'
(default: 'true').
The default values ensure that the API behavior remains the same as
before when the query filters aren't provided.
cc @stuartnelson3
=> api: support more query filters

config/config_test.go
Note that #1338 will allow to block incorrect formatting.
=> config: fix Go formatting

cli/alert.go, client/client.go, client/client_test.go
Support the new filter options in the alerts api
endpoint introduced by https://github.com/prometheus/alertmanager/pull/1366
Signed-off-by: stuart nelson <stuartnelson3@gmail.com>
requested in #1369 
@simonpasquier
=> cli alert query: Expose --active and --unprocessed

config/notifiers.go, notify/impl.go, notify/impl_test.go
This PR adds the Slack action parameters according to the Slack documentation available at https://api.slack.com/docs/message-buttons.
The action buttons can be added as follows:
```yaml 
actions:
- type: "button"
text: 'Test'
url: 'http://example.com'
style: 'danger'
```
=> [Request] Add Slack actions to notifications

cli/check_config.go
Not everything about a config was printed before. 
Example output:
```
$ amtool check-config alertmanager.yaml
Checking 'alertmanager.yaml'  SUCCESS
Found:
- global config
- route
- 0 inhibit rules
- 13 receivers
- 0 templates
```
=> cli: print more config details

cluster/cluster.go, cluster/cluster_test.go, cluster/delegate.go, cmd/alertmanager/main.go
add reconnection support for dead peers
todo:
edit:
I also included the `logWriter{}` wrapper I was using to expose memberlist logging. It's very verbose, and doesn't really conform to how we've been logging, so I'm not sure how best to expose it (or if I should just remove it from this PR).
=> memberlist reconnect

cluster/advertise.go, cluster/cluster.go
While testing #1384 I found that the address advertised by memberlist isn't valid when the bind address is empty. cc @stuartnelson3
=> cluster: advertise explicitly for empty addresses

nflog/nflogpb/set.go, nflog/nflogpb/set_test.go, notify/impl.go, notify/notify.go, notify/notify_test.go, test/acceptance/send_test.go
Closes #1403.
I've described the change in the commit message but I feel that an update to the docs would be helpful too. I'm still testing it locally to explore with different alert scenarios.
=> notify: notify resolved alerts properly

cluster/cluster.go, cluster/cluster_test.go
initially failed peers weren't being set correctly, which caused a panic (!) and prevented them from being removed.
@simonpasquier
=> fix set initial failed peers

cluster/cluster.go
When setting initially failing peers, if we don't
have a value for the advertise address, use the
bindAddr.
the current code results in adding a failed peer that cannot be reconnected to if advertiseAddr isn't set, but bindAddr is a full IP addr. This results in a lot of `full_state` syncs because of the attempted reconnects to a node that cannot be reconnected to.
@simonpasquier
=> Check for advertise host when setting failed peers

cluster/cluster.go, cluster/cluster_test.go
When `resolvePeers()` can't resolve some of the peers' addresses, `setInitialFailed()` can get passed textual addresses. Those need to be filtered out.
cc @stuartnelson3
=> cluster: don't track FQDN addresses as inital peers

cluster/channel.go, cluster/channel_test.go, cluster/cluster.go, cluster/delegate.go, cmd/alertmanager/main.go, nflog/nflog.go, silence/silence.go
fixes #1412
Over a certain number of bytes (in this case, half of the allowed packet size, 700), send messages via `memberlist.SendReliable()`, which uses the TCP transport. These messages are still sent to the same interface func on our `delegate`, `delegate.NotifyMsg()`. Since we're sending the large messages to all peers by default, there's no need to gossip any received large message further (cf. the implementation for `Merge()` for `nflog` and `silence`)
@grobie @brancz @mxinden @simonpasquier
=> gossip large messages via SendReliable

CHANGELOG.md
As pointed out by @roman-vynar [here](https://github.com/prometheus/alertmanager/pull/1430#issuecomment-399429259) I was missing two change details in the CHANGELOG.md for the v0.15.0 release:
- Add entry for working dir change in Alertmanager Docker image
- Indicate cluster flag changes
=> CHANGELOG.md: Improve [CHANGE] section of v0.15.0 release

template/template.go
@stuartnelson3 For more complex templates it is sometimes required to check whether a string contains only specific parts. Therefore I added strings.Contains/strings.ContainsAny to the FuncMap
=> Lookup parts in strings using regexp.MatchString

Dockerfile
Fixes #1433 
This PR fixes breaking change in chande in dockerfile WORKDIR.
Since `0.15.0` if user overridden the `cmd` and did not specify the `storage.path` data were stored by default to `/etc/alertmanager/data`
=> fix: reverted change of dockerfile entrypoint

CHANGELOG.md
To ensure we include the breaking change notice in the next release
notes, this patch adds a 'Next release' section mentioning the breaking
change of the working directory of the Alertmanager Dockerfile.
See https://github.com/prometheus/alertmanager/pull/1435#pullrequestreview-134278203
=> CHANGELOG.md: Add 'Next release' section with docker working dir change

cluster/advertise.go, cluster/advertise_test.go
=> cluster: fail when no private address can be found

cluster/cluster.go, cluster/cluster_test.go, cluster/delegate.go, cmd/alertmanager/main.go
During the join, memberlist initiates a pushPull to get initial data.
Unfortunately, at this point the nflog and silence listener have not
been registered yet, so the first data arrives only after one pushPull
cycle (1min by default !).
=> cluster: make sure we don't miss the first pushPull

dispatch/dispatch.go
There is no lock when adding aggrGroup to group map. If another goroutine call Dispatcher.Groups or Dispatcher.run clear up aggrGroups, alertmanager will be panic.
=> fix concurrent read and wirte group error

cluster/cluster.go, cmd/alertmanager/main.go
Alertmanager is exiting with a non-zero exit code if the initial cluster
join fails. This behavior could be not wanted because:
- As Alertmanager is a critical component with an at-least-once
guarantee, failing on joining the cluster is unnecessary as
Alertmanager still functions by itself.
- In an environment like Kubernetes discovering peers via DNS, peers
might roll out one-by-one, leaving the DNS entries unpopulated for the
first peer of a set. Failing on initial join prevents a roll-out.
Instead of failing on the initial join this patch only logs the failure.
The cluster can be later joined via the `handleReconnect`.
This is a regression introduced in PR #1456 [1].
[1] https://github.com/prometheus/alertmanager/pull/1456
//CC @stuartnelson3 @simonpasquier @brancz
=> cluster: Do not exit when failing to join cluster

cli/alert.go, cli/alert_add.go, cli/alert_query.go, cli/utils.go
Closes #1417
cc @stuartnelson3
=> Add support for adding alerts using amtool

cli/alert_add.go, cli/alert_query.go, cli/config.go, cli/root.go, cli/silence.go, cli/silence_add.go, cli/silence_expire.go, cli/silence_import.go, cli/silence_query.go, cli/silence_update.go, cli/utils.go
implements https://github.com/prometheus/alertmanager/issues/1464
the whole global `timeout` and `execWithTimeout` are because I don't know how to parse a global variable and then access it from or pass it in to the different subcommand actions. I'm not too upset about having a global timeout variable since it will only affect one command per execution, but I would prefer to pass it in explicitly instead of doing this lame closure thing in `execWithTimeout`.
so, if you're more familiar with kingpin's api and know how to do this, I'm all ears :)
=> [amtool] Add timeout support to amtool commands

notify/impl.go
I noticed that I was unable to template the room_id field of hipchat_config, upon reviewing the code I found that tmplText was never being called on room_id despite it being declared as a tmpl_string in the documentation at https://prometheus.io/docs/alerting/configuration/#%3Chipchat_config%3E
This PR simply calls tmplText on RoomID before passing it into the url Sprintf
=> enable templating of hipchat room_id

notify/impl.go, notify/impl_test.go
- `tmplText` and `tmplHTML` are using a monad-style error handling [1].
This reduces the verbosity of the error logic, but introduces the risk
of forgetting the final error check. This patch does not remove this
coding-style, but ensures proper error checking in the Email and
PagerDuty notifier.
- Ensure to handle errors returned by `multipartWriter.Close()` and
`wc.Write(buffer.Bytes())` in `Email.Notify()`.
[1] https://www.innoq.com/en/blog/golang-errors-monads/
Follow up to https://github.com/prometheus/alertmanager/pull/1436#issuecomment-402711826
=> notify: Improve error handling

template/email.html
@stuartnelson3 
Emails that contain no firing alerts should not be red. This makes them green.
#859 was a past (never merged) attempt to do something similar, but this is simpler
=> Email is green if no firing alerts

config/config.go, config/config_test.go, config/notifiers.go, config/notifiers_test.go, config/testdata/conf.good.yml, notify/impl.go, notify/impl_test.go
=> config: validate URLs at config load time

config/config_test.go
`honnef.co/go/tools/cmd/staticcheck` complains with
`config/config_test.go:260:32: regular expression does not contain any
meta characters (SA6004)`. Instead of using a RegEx this patch simply
switches to using Golangs `strings.Count` function.
This patch fixes our current CI failures, e.g. seen in https://github.com/prometheus/alertmanager/pull/1482.
=> config/test: Count `<secret>` occurrences via golang strings

notify/impl.go
This adds compatiblity with PagerDuty's Event rules feature, allowing resolve events to be routed based on attributes
Fixes #1440
=> fix: Update PagerDuty API V2 to send full details on resolve

provider/mem/mem.go, provider/mem/mem_test.go
TestAlertsSubscribePutStarvation tests starvation of `iterator.Close` and
`alerts.Put`. Both `Subscribe` and `Put` use the Alerts.mtx lock. `Subscribe`
needs it to subscribe and more importantly unsubscribe `Alerts.listeners`.
`Put` uses the lock to add additional alerts and iterate the `Alerts.listeners`
map.  If the channel of a listener is at its limit, `alerts.Lock` is blocked,
whereby a listener can not unsubscribe as the lock is hold by `alerts.Lock`.
This test will succeed once https://github.com/prometheus/alertmanager/pull/1482 is merged.
//CC @waterdrink @s-urbaniak @simonpasquier @stuartnelson3
=> provider/mem: Add `Put` `Subscribe` starvation test

notify/impl.go
In moving from a plain string to url.URL, we
incorrectly were setting the query string via the
path. The `?` signaling the start of the query
string would then be escaped when the URL was
turned into a string.
@mxinden @simonpasquier I would classify this as extremely important, we should get a release out as soon as this is merged IMO. I'm guessing hipchat, wechat, and opsgenie are all broken?
Fixes #1515
=> Correctly encode query strings in notifiers

CHANGELOG.md, README.md, cli/config.go, cli/routing.go, cli/test_routing.go, cli/test_routing_test.go, cli/testdata/conf.routing-reverted.yml, cli/testdata/conf.routing.yml, cli/utils.go, doc/examples/simple.yml, vendor/github.com/xlab/treeprint/LICENSE, vendor/github.com/xlab/treeprint/README.md, vendor/github.com/xlab/treeprint/helpers.go, vendor/github.com/xlab/treeprint/struct.go, vendor/github.com/xlab/treeprint/treeprint.go, vendor/vendor.json
Hi @stuartnelson3, we talked for a while at the PromCon about multi-tenancy of Alertmanager and increasing complexity of routing configuration.
So I thought some testing would be useful to avoid misconfiguration.
This PR adds `routing-test` command to the `amtool` which accepts label definition of an alert and returns all receivers which the alert resolves to. It allows to load Alertmanager config from file or remotely 
example usage is 
```
$ ./amtool routing-test --config.file=doc/examples/simple.yml  service=database
team-DB-pager
```
I also added flag `--verify.receivers` which also checks if resulting receivers match those specified and if not the return code is `1`. I'm not sure if it should be implemented in the amtool but it makes testing easier.
This should allow user to define …
=> feat: added routing tools to amtool

cluster/cluster_test.go
Closes #1445.
As described in the issue, the other option would be to listen on the 127.0.0.0/8 addresses but I fear that it might still break in some exotic environments anyway.
=> cluster: skip tests when no private ip address exists

CHANGELOG.md, api/api.go, api/api_test.go, cmd/alertmanager/main.go, dispatch/dispatch.go, dispatch/dispatch_test.go
Closes #1508
_I had this change for a while in my backlog, just rebased on master to fix some conflicts._
=> *: remove v1/alerts/groups API endpoint

Makefile, api/api.go, cmd/alertmanager/main.go, notify/impl.go, provider/mem/mem.go, scripts/errcheck_excludes.txt, test/acceptance.go, test/mock.go
Errcheck [1] enforces error handling accross all go files. Functions can
be excluded via `scripts/errcheck_excludes.txt`.
This patch adds errcheck to the `test` Make target.
[1] https://github.com/kisielk/errcheck
Follow up to https://github.com/prometheus/alertmanager/pull/1501#issuecomment-410598596. @stuartnelson3 @juliusv let me know what you think. Of course doing this at all is still up for discussion.
=> *.go: Introduce errcheck enforcing error handling

CHANGELOG.md, cli/config/config.go
Fixes https://github.com/prometheus/alertmanager/issues/1529
If `~/.config/amtool` path is file amtool fails on any command. This adds `os.Stat` check before loading the file as sugested by @simonpasquier .
=> fix amtool: Fixed config path check in amtool

test/with_api_v1/acceptance/send_test.go, test/with_api_v2/acceptance/send_test.go
Recently Travis CI started failing tests quite often (#1532 and #1543 for instance). In particular `TestResolved()` fails because the notifications aren't received in the expected timeframe (tolerance is 150ms).
=> test: don't run TestResolved() in parallel

config/notifiers.go, notify/impl.go
This pull request adds two additional fields (images and links) to the data sent to PagerDuty. Users can either provide a static value in the config or provide template strings which allows values to come from the alert definitions and labels themselves.
Note that this only works when using the v2 API. It could be implemented in the v1 api but it has been deprecated so it's probably not worth it.
I've tested it with both static and template values using my PagerDuty instance.
=> Add support for images and links in the PagerDuty notification config

store/store.go
This fixes the ineffectual assignment for the default GC interval when specifiying a duration of 0
Signed-off-by: Jannick Fahlbusch <git@jf-projects.de>
=> [FIX] Fix ineffectual assignment for default GC interval

config/config.go, config/config_test.go, config/testdata/conf.empty-fields.yml
Closes #1565 
AlertManager won't start if a URL parameter isn't formatted like `http[s]://host[:port][/path]`. It might break existing installations but in any case, those weren't functioning properly (eg notifications couldn't be sent).
=> config: enforce HTTP or HTTPS URLs

cli/alert_query.go
The documentation stated that the `alertname=`
part of a matcher could be dropped and it would be
assumed that the first value was the alertname.
This behavior was only honored if there was a
single matcher, but failed if there were multiple.
Any time we have one or more matchers, check to
see if the first matcher fails parsing. If so,
assume it's intended to be used as the alertname,
and append that value to the matcher.
=> [amtool] support assuming first label is alertname in alert query with matchers

notify/impl.go, notify/impl_test.go
This is analogous of what is done for PagerDuty secrets.
Probably needs a doc update as well.
/cc @stuartnelson3
=> Make OpsGenie API Key a templated string

test/with_api_v2/acceptance.go, test/with_api_v2/acceptance/cluster_test.go, test/with_api_v2/acceptance/inhibit_test.go, test/with_api_v2/acceptance/send_test.go, test/with_api_v2/acceptance/silence_test.go, test/with_api_v2/collector.go, test/with_api_v2/mock.go
Instead of only testing single instance Alertmanagers, this patch
enables individual tests to spin up Alertmanager clusters.
In addition it adds two tests:
1. A test firing alerts against a cluster, expecting to only receive a a
notification by one of the Alertmanager instances in the cluster.
2. A test firing alerts both against a single instance as well as a
cluster, making sure the output equals.
Signed-off-by: Max Leonard Inden <IndenML@gmail.com>
=> test: Enable testing against cluster of Alertmanagers

config/notifiers.go, config/notifiers_test.go, notify/impl.go
Fixes #1556. Either `URL` or `Name` and `Value` need to be provided in slack action. LGTY @simonpasquier? Thanks in advance
=> adds name, value, SlackConfirmationField to slack action

dispatch/dispatch.go, dispatch/dispatch_test.go, notify/impl.go, notify/impl_test.go, notify/notify.go, notify/notify_test.go, test/with_api_v1/acceptance.go, test/with_api_v2/acceptance.go, test/with_api_v2/api_v2_client/client/alert/get_alerts_parameters.go, test/with_api_v2/api_v2_client/client/alert/post_alerts_parameters.go, test/with_api_v2/api_v2_client/client/general/get_receivers_parameters.go, test/with_api_v2/api_v2_client/client/general/get_status_parameters.go, test/with_api_v2/api_v2_client/client/receiver/get_receivers_parameters.go, test/with_api_v2/api_v2_client/client/silence/delete_silence_parameters.go, test/with_api_v2/api_v2_client/client/silence/get_silence_parameters.go, test/with_api_v2/api_v2_client/client/silence/get_silences_parameters.go, test/with_api_v2/api_v2_client/client/silence/post_silences_parameters.go
Some dependencies still depend on it but at the AlertManager's code is clean.
=> *: remove use of golang.org/x/net/context

notify/impl.go, notify/impl_test.go
This pull request aims to close #1555 by returning an error if no auth mechanism is found.
Signed-off-by: glefloch <glfloch@gmail.com>
=> Throw error if no auth mechanism is match

types/types.go, types/types_test.go
Alert merging assumed that EndsAt would always be empty for firing alerts. This is no longer true starting with Prometheus v2.4.0: EndsAt is set to a multiple of the evaluation interval or resend interval (whichever is the largest). See https://github.com/prometheus/prometheus/pull/4550
The issue might be in https://github.com/prometheus/alertmanager/issues/1581 and it has been raised on the [prometheus users mailing list](https://groups.google.com/d/msg/prometheus-users/87uL3bno_8c/jthEiSRaBAAJ) too.
I've added more tests because even though the code change is small, it is quite tricky to get it right (and I'm not sure I did!).
cc @brian-brazil @stuartnelson3 @mxinden
=> types: fix alert merging

notify/impl.go
Use [`quoted-printable`](https://en.wikipedia.org/wiki/Quoted-printable) transfer encoding for the text sent out by the email notifier.
Turns out MIME has a maximum line length of 998 bytes ([RFC 2822](https://www.ietf.org/rfc/rfc2822.txt), section 2.1.1) and some SMTP servers will enforce that by inserting a `<CR><LF>` after 998 characters, whether that's in the middle of a URL or HTML tag, potentially breaking the email's contents.
=> Use quoted-printable transfer encoding for the email notifier

nflog/nflog.go, nflog/nflog_test.go, silence/silence.go, silence/silence_test.go
If they're expired, they should be cleaned up on
the next GC cycle, but merging them in means that
they'll probably be gossip'd continually between
the cluster members.
fixes #1624 
The issue was in the `merge` function: https://github.com/prometheus/alertmanager/blob/master/silence/silence.go#L752-L756
Expired silences would get deleted every 15 minutes (the hard-coded maintenance interval), but on each full-state sync an alertmanager would get a bunch of expired silences. Since they didn't exist in its state cache, they would be merged back in. Since the merge happens every minute, they were seemingly guaranteed to stick around. If all the alertmanagers were started at the same time they might GC all the silences before a full state sync, but if they're offset in their maintenance …
=> [gossip] Don't merge expired gossip messages

notify/impl.go
When creating a `NewClient`, pass only the hostname
as value for the `host` parameter, instead of `n.conf.Smarthost`,
which is hostname port.
This is the same as `smtp.Dial` does, which is called in
the else-branch.
The value passed as `host` argument to `NewClient` is
later compared against the `plainAuth.host` value:
`net/smtp.(*Client).Auth` and `net/smtp.(*plainAuth).Start`
(plainAuth is created created here: <https://github.com/prometheus/alertmanager/blob/master/notify/impl.go#L245>)
In my tests, this fixed the problems described in #980 
Note: after this change, the strings which are compared in
https://golang.org/src/net/smtp/auth.go at (`if server.Name != a.host`)
are derived from the same config value. I think that is correct, but as it
might affect security, it should be …
=> FIX "PLAIN" auth during notification via smtp-over-tls on port 465

cmd/alertmanager/main.go, test/with_api_v1/acceptance.go, test/with_api_v1/acceptance/web_test.go, test/with_api_v2/acceptance.go, test/with_api_v2/acceptance/web_test.go
Closes #1627 
While I was looking at the code, it occurred to me that we use [`os.Exit`](https://godoc.org/os#Exit) improperly as it doesn't run deferred functions. I refactored that part in this PR but it can go in another PR if someone prefers.
Finally, there's still a problem with the UI: the Status tab doesn't render properly but I'm not familiar enough with the front-end code to know how to fix it. @stuartnelson3 and @mxinden, you probably know better.
=> Fix route prefix for the API v2

README.md, config/config.go, config/config_test.go, config/testdata/conf.good.yml, config/testdata/conf.group-by-all.yml, dispatch/dispatch.go, dispatch/dispatch_test.go, dispatch/route.go, dispatch/route_test.go, doc/examples/simple.yml
This PR adds support for group_by_all parameter.
If it is true, all alert's labels will be used for grouping. 
If each alert has unique set of labels, this setting will effectively disable aggregation of different alerts.
=> add group_by_all support

provider/mem/mem.go, provider/mem/mem_test.go
@mxinden - Just a minor fix to a typo in the license statements in /provider/mem/
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Fixed typo in license statement URL

CHANGELOG.md
This would go into `release-0.16` first and then into `master`.
Signed-off-by: Max Leonard Inden <IndenML@gmail.com>
=> CHANGELOG.md: Fix date typo

.travis.yml
This allows to use travis on your github fork.
Otherwise the code is imported inside `$GOPATH/src/github.com/user/repo` and make fails.
=> Travis: specify go_import_path

config/config.go, config/config_test.go
=> config: fix unmarshalling of secret URLs

config/config.go, config/config_test.go
GroupByAll and a duplicate GroupBy were showing up
in the marshaled config, which we don't want.
Fixes #1662
=> Don't write groupbyall and groupby when marshaling config

cmd/alertmanager/main.go, go.mod, go.sum, vendor/github.com/prometheus/common/expfmt/text_create.go, vendor/github.com/prometheus/common/expfmt/text_parse.go, vendor/github.com/prometheus/common/model/time.go, vendor/github.com/prometheus/common/promlog/flag/flag.go, vendor/github.com/prometheus/common/promlog/log.go, vendor/github.com/prometheus/common/route/route.go, vendor/modules.txt
I am not sure if I did this correctly, but I'm willing to accept guidance on how to format things properly. :)
This should handle --log.format for #1657
=> Update prometheus/common and add support for --log.format

cluster/advertise.go
Fix some typo errors:
1. "overriden" to "overridden" in line 25.
2. "inadvertantly" to "inadvertently" in line 31.
=> Fix some annotation typo errors

api/v2/api.go, go.mod, go.sum, vendor/github.com/rs/cors/LICENSE, vendor/github.com/rs/cors/README.md, vendor/github.com/rs/cors/cors.go, vendor/github.com/rs/cors/go.mod, vendor/github.com/rs/cors/utils.go, vendor/modules.txt
We do something similar for the v1 API.
https://github.com/prometheus/alertmanager/blob/cd4a524848ca037f7daa1a27a238f731c0e4c0c7/api/v1/api.go#L132-L139
It will also help Prometheus detecting if the AlertManager supports the v2 API or not.
=> api/v2: Add CORS support

config/notifiers.go, notify/impl.go
Extending [Pushover](https://pushover.net) integration to allow extended customization:
- New `sound` parameter for a [custom notification sound](https://pushover.net/api#sounds).
- New `url_title` parameter, which allows setting [custom text for the supplementary URL](https://pushover.net/api#tldr).
- [HTML formatting support](https://pushover.net/api#html) within the messages.
As for the last one, I've enabled HTML support for all the messages, as I don't really see the reason why not to do so (either way, you need to use explicit HTML tags within your message to use this functionality). Anyhow, if you think otherwise, I'm good with making this configurable as well.
=> Pushover: support HTML, URL title and custom sounds

dispatch/dispatch.go, dispatch/dispatch_test.go
If the original EndsAt is left in place, then as time moves forwards
past the EndsAt then firing alerts will be rendered and treated as
resolved alerts which can cause confusion and races. This is most
likely to happen on retries for a notification.
Mitigate race and fix data races in TestAggrGroup.
Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>
=> Make a copy of firing alerts with EndsAt=0 when flushing.

cli/silence_add.go, cli/silence_query.go
ref #1575
This PR adds support for assuming the first label is `alertname` in silence add and query. It was already existing on silence query, did some cleanup.
Will create another PR for #1682
=> support for assuming first label is alertname in silence add and query

config/notifiers.go, config/notifiers_test.go, notify/impl.go, notify/impl_test.go
This PR is a followup to another PR that was opened #1315.
These changes allow users to define additional fields they would like to pass on to VictorOps and use templates to set the values of those fields.
Example:
```
- name: default
victorops_configs:
- entity_display_name: '{{ .CommonAnnotations.summary}}'
message_type: '{{ .CommonLabels.severity }}'
routing_key: default
state_message: '{{ .CommonAnnotations.description }}'
custom_fields:
tier: '{{ .CommonLabels.tier }}'
storage: '{{ .CommonLabels.storage }}'
```
Logic has been added to prevent a custom field colliding with/overriding a statically defined field. When this occurs, the field will simply be ignored and a debug level log message will notify of this.
=> Support adding custom fields to VictorOps notifications

config/config.go, config/config_test.go, config/testdata/conf.good.yml
closes  #1649
the variable `DefaultGlobalConfig` was being used to initialize values, but it stored previous information due to which some things were persisting in the newer initialization.
In this PR, `DefaultGlobalConfig` is changed to a function so that it returns a fresh `GlobalConfig`  for initialization.
also added some comments.
=> fixes #1649 : Changed DefaultGlobalConfig to a function and added comments

api/v2/api.go
By default go-swagger serves the swagger spec and the redoc UI. This
patch disables both.
This does not need to be permanent, but for now I would prefer to reduce the attach-surface. What are your thoughts?
//CC @metalmatze (Thanks for the catch!)
=> api/v2: Disable serving swagger spec and redoc UI

notify/impl.go
Fixes https://github.com/prometheus/alertmanager/issues/1700.
PagerDuty Alerts are rejected (a 400 BadRequest is sent back from PagerDuty)
when the summary field is longer than 1024 characters
(https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2).
=> trim PagerDuty message summary to 1024 chars, add PagerDuty debug log

api/api.go, cmd/alertmanager/main.go
Instead of cmd/alertmanager/main.go instantiating and starting both api
v1 and v2, delegate that work to a generic api combining the two.
Signed-off-by: Max Leonard Inden <IndenML@gmail.com>
=> api: Combine v1 and v2 into generic api

.promu.yml
Adding support for s390x, as discussed in https://github.com/prometheus/alertmanager/issues/1735
Please review
=> Add suport for s390x

Makefile, scripts/errcheck_excludes.txt
This will fix the errcheck problems, and it might have an impact on the `go generate` part.
It indeed looks like Circle somehow keeps `GOPATH` in the environment for external commands (via `go generate` or the `errcheck` command), while Travis somehow removes it or builds outside of it or whatever. More investigation needed, but this removes a few parts of the equation at least.
=> Fix build problems

cmd/alertmanager/main.go, inhibit/inhibit_test.go, notify/notify_test.go, provider/mem/mem_test.go, types/types.go, types/types_test.go
Instead of registering marker metrics inside of
cmd/alertmanager/main.go, register them in types/types.go, encapsulating
marker specific logic in its module, not in main.go. In addition it
paves the path for removing the usage of the global metric registry in
the future, by taking a local metric registerer.
Signed-off-by: Max Leonard Inden <IndenML@gmail.com>
=> main.go: Move marker metric registering into types/types.go

config/config.go, config/config_test.go
In similar vein to prometheus/prometheus/pkg/relabel/relabel.go, extend
Regexp to include the original regular expression string to faithfully
output what was read.
Update TestEmptyFieldsAndRegex.
Fixes: #1753
Signed-off-by: Miek Gieben <miek@miek.nl>
=> Add original field to Regexp

api/v2/api.go
Follow up of #1711. It seems to me that exposing the OpenAPI specification at `/api/v2/swagger.json` isn't too risky and might be useful for some users ([ref](https://groups.google.com/d/msg/prometheus-users/pzTnCvQ-A0Q/EVFmjMYtDwAJ)).
=> api/v2: serve OpenAPI specification

api/api.go, api/v1/api.go, api/v1/api_test.go, api/v2/api.go, cmd/alertmanager/main.go, config/coordinator.go, config/coordinator_test.go
Instead of handling all config specific logic inside
Alertmangaer.main(), this patch introduces the config coordinator
component.
Tasks of the config coordinator:
- Load and parse configuration
- Notify subscribers on configuration changes
- Register and manage configuration specific metrics
This patch still has a couple of `TODO`s. I am opening a pull request anyways, to get early feedback whether a refactoring like this is wanted.
=> *: Introduce config coordinator bundling config specific logic

inhibit/inhibit.go, types/types.go
This clarifies a bunch of things I have run into during code reading
in preparation for some performance improvements around muting.
It also moves doc comments from places where they don't show up in
godoc to visible places.
It also fixes golint warnings.
Signed-off-by: beorn7 <beorn@soundcloud.com>
=> Improve doc comments for Marker and friends

inhibit/inhibit.go, inhibit/inhibit_test.go, types/types.go
This has been discussed in #666 (issue of hell...).
As concluded there, the cleanest semantics is most likely the
following: "An alert that matches both target and source side cannot
inhibit alerts for which the same is true." The two open questions
were:
1. How difficult is the implementation?
2. Is it needed?
This relatively simple commit proves that the answer to (1) is: Not
very difficult. (This also includes a performance-improving
simplification, which would have been possible without a change of
semantics.)
The answer to (2) is twofold:
For one, the original use case in #666 wasn't solved by our interim
solution. What we solved is the case where the self-inhibition is
triggered by a wide target match, i.e. I have a specific alert that
should inhibit a whole group of target alerts …
=> Modify the self-inhibition prevention semantics

config/coordinator.go
Remove duplicate logs and add a log when the reloading is complete.
=> config: update coordinator's logs

api/api.go, api/v2/api.go, cmd/alertmanager/main.go, notify/notify.go, notify/notify_test.go, silence/silence.go
This encapsulates the logic of querying and marking silenced
alerts. It removes the code duplication flagged earlier.
I removed the error returned by the setAlertStatus function as we were
only logging it, and that's already done anyway when the error is
received from the `silence.Query` call (now in the `Mutes` method).
Signed-off-by: beorn7 <beorn@soundcloud.com>
=> Create a `Muter` implementation for silences

Makefile, api/v1/api.go, api/v2/api.go, notify/notify_test.go, silence/silence.go, silence/silence_test.go, types/types.go
I have also found a bug with zero retention time while doing so. See individual commits.
The first commit just adds a benchmark, which showed me that we need this optimization for high-alert scenarios.
=> Performance improvement checking the silenced state

notify/impl.go, notify/impl_test.go
This PR is intended to replace #1713 which I got into a mess trying to retrospectively sign commits using git rebase.
It adds a noAuth SMTP authentication mechanism which is returned when no `smtp_auth_username` is supplied, allowing this option where a server advertises AUTH but does not require it
CC @simonpasquier - sorry for the extra effort here. 
Closes #1721
=> Allow sending of unauthenticated SMTP requests when smtp_auth_username is not supplied

config/config.go, config/config_test.go
Fixes https://github.com/prometheus/alertmanager/issues/1759
=> Fix receiver name checking in deep sub-routes

.circleci/config.yml, .promu.yml, .travis.yml, Makefile
It also pins errcheck to the latest stable release and simplifies how it gets installed.
=> Switch to Go 1.12

doc/design/secure-cluster-traffic.md
As of today the communication between Alertmanager instances in a cluster is send in clear-text.
Instances in a cluster should communicate among each other in a secure fashion. Alertmanager should guarantee confidentiality, integrity and authenticity for each message touching the wire. While this would improve the security of single datacenter deployments, one could see this as a necessity for wide-area-network deployments.
This patch adds a design document to plan the goal above. A prove of concept implementation can be found [here](https://github.com/mxinden/memberlist-tls-transport).
**Ideas, comments, suggestions, ...,  are very much appreciated!**
=> doc: Add 'Secure Alertmanager cluster traffic' design document

api/v2/api.go, api/v2/api_test.go
Sort the queried silences to match behaviour in the v1 api.
Fixes #1781
=> api/v2: sort silences similarly to v1 api

config/notifiers.go
This fixes the following error found by go vet:
config/notifiers.go:546:2: struct field tag
`yaml:"url_title,omitempty" json:"url_title,omitempty` not compatible with
reflect.StructTag.Get: bad syntax for struct tag value (govet)
URLTitle string   `yaml:"url_title,omitempty" json:"url_title,omitempty`
^
Signed-off-by: Karsten Weiss <knweiss@gmail.com>
=> Fix bad syntax for struct tag value

api/v1/api.go
As discussed in #1793 this breaks external clients when the requests are cross domain
=> Add POST as an allowed CORS request method

api/v2/api.go
Before peers are returned for the status response sort them by name. This will improve the Status page, as  the order will be stable now when refreshing it several times.
The order of peers is stable like this on my cluster now, regardless of which I get routed to by the proxy in front:
/cc @mxinden
=> Sort peers before returning via API

config/notifiers.go, config/notifiers_test.go
Closes #1808 
`APISecret` and `CorpID` are validated after un-marshaling the full configuration.
https://github.com/prometheus/alertmanager/blob/a94088406ab7212acadaa01f4e86467ee1eac8f6/config/config.go#L378-L390
=> config: fix Wechat global parameters

api/v2/api.go, api/v2/client/silence/post_silences_responses.go, api/v2/openapi.yaml, api/v2/restapi/embedded_spec.go, api/v2/restapi/operations/silence/post_silences_responses.go
When the client attempts to update a silence with a non-existent
ID, respond with a 404 (Not Found) instead of a 400 (Bad Request).
Signed-off-by: Paul Gier <pgier@redhat.com>
=> api/v2: Respond with 404 when silence ID is not found

ui/web.go
This patch adds HTTP headers to each web asset response, disabling
caching for the payload. This prevents users running an old version of
the UI against a new version of Alertmanager once they updated. On the
down-side it increases page load size on subsequent page loads.
What do you all think?
=> ui/web: Set HTTP headers to prevent asset caching

notify/impl.go, notify/impl_test.go
I discovered that the Slack URL is logged in clear-text when an error occurs. This PR makes sure that the information isn't leaked anymore.
=> notify: redact Slack webhook URL from logs

notify/impl.go, notify/impl_test.go
Follow-up of https://github.com/prometheus/alertmanager/pull/1822
=> notify: redact more secret data from logs

dispatch/dispatch.go, inhibit/inhibit.go, provider/mem/mem.go, provider/mem/mem_test.go, store/store.go
While investigating a flaky test, I found out that the iterator returned by `(*github.com/prometheus/alertmanager/provider/mem.Alerts).Subscribe()` might miss alerts that would be added in-between. I've also modified `(*github.com/prometheus/alertmanager/storemem.Alerts).List()` to return a slice rather than a closed buffered channel which I feel is more idiomatic.
If you run `TestAlertsSubscribe` several times without the fix, it should exhibit the issue:
```
$ go test -run TestAlertsSubscribe -count 100 -race  ./provider/mem/.
--- FAIL: TestAlertsSubscribe (5.03s)
mem_test.go:238: Unexpected number of alerts for iterator 99, got: 2, expected: 3
--- FAIL: TestAlertsSubscribe (5.04s)
mem_test.go:238: Unexpected number of alerts for iterator 99, got: 2, expected: 3
```
=> Alerts might be dropped 

.circleci/config.yml
Not sure if it's the problem with the container build job but it is the only difference I can see comparing to the Prometheus configuration.
=> .circleci: fix build job

.dockerignore
This should fix the build issues for container images.
=> .dockerignore: add more exceptions

go.mod, go.sum, inhibit/inhibit.go, vendor/github.com/oklog/run/.gitignore, vendor/github.com/oklog/run/LICENSE, vendor/github.com/oklog/run/README.md, vendor/github.com/oklog/run/group.go, vendor/modules.txt
https://github.com/oklog/oklog was archived and the run group package was extracted as https://github.com/oklog/run. We should use this instead for possible future updates.
Similar to https://github.com/prometheus/prometheus/pull/5491.
=> Use github.com/oklog/run not archived oklog/oklog

api/v2/api.go, test/with_api_v2/acceptance/api_test.go
They are exactly the same, no reason to duplicate.
=> Move alert endpoints filter parsing to single function

silence/silence.go, store/store.go
1.There is an unused function 'QTimeRange', clean it.
2. Slice declaration with empty literal initializer instead of nil.
=> Unused function 'QTimeRange' and empty slice declaration via literal 

config/config_test.go, config/testdata/conf.good.yml
There was a report that this isn't working.
Updating the config and ensuring the parsing works
correctly indicates that the image_url is being
read into a string.
check is in response to #1551
=> Add image_url to example of good config

.gitignore, CHANGELOG.md, config/config_test.go, config/notifiers.go, config/testdata/conf.opsgenie-default-apikey-old-team.yml, config/testdata/conf.opsgenie-no-apikey.yml, notify/impl.go, notify/impl_test.go
Fixes: https://github.com/prometheus/alertmanager/issues/1818
Fixes: https://github.com/prometheus/alertmanager/issues/1342
Some decisions I made:
* "Teams" config option will fail on unmarshalling the config. I marked it as deprecated. AM is 0.x version it should be fine (?)
* I allow the use case for dynamic set of responders from alert's label using templating. Seems like it fits into how others fields are treated.
* I allow for full flexibility, so you can use any type you want. There is no validation. I don't think it is worth as Opsgenie changes those things (?). Let me know if it's needed. I think if the type is wrong and create alert will fail it's fine as "validation"
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> opsgenie: Moved from deprecated, non documented teams to responders field.

cmd/alertmanager/main.go, notify/impl.go, notify/impl_test.go, notify/notify.go, notify/notify_test.go, scripts/errcheck_excludes.txt
Currently every time an HTTP-based integration notifies something, it creates a new HTTP client and the connection is only closed after 5 minutes (idle connection time-out). Although usually there aren't thousands of notification requests during such interval, it consumes unnecessary resources.
[`config.NewClientFromConfig()`](https://godoc.org/github.com/prometheus/common/config#NewClientFromConfig) from `github.com/prometheus/common` detects whenever the configuration on disk (eg certificates, tokens) has changed so re-using the same client instead of creating one per request should be transparent. It also means that an invalid configuration (eg non-existing certificate) will be detected during the loading of the configuration instead of during the first notification.
=> *: use persistent HTTP clients

cli/alert_query.go
This was dropped accidentally in
https://github.com/prometheus/alertmanager/pull/1798
fixes #1906
=> Support filtering cli alert queries by receiver

README.md
I couldn't find a reference for determining API routes on the readme, after some trial and error I found out what worked.
=> docs: clarify API routing (and with --web.external-url)

nflog/nflog.go, silence/silence.go
With the next release of client_golang, Summaries will not have
objectives by default. To not lose the objectives we have right now,
explicitly state the current default objectives.
Signed-off-by: beorn7 <beorn@grafana.com>
=> Add objectives to Summaries

config/notifiers.go, config/notifiers_test.go
`^apple|banana|cherry$` finds matches to either of `^apple`, `banana`, or `cherry$`, so strings like `apple0`, `1banana2`, `3cherry` are accepted; I believe this wasn't intentional.
=> config/notifiers.go: fix opsgenieValidTypesRe

test/with_api_v2/acceptance.go, test/with_api_v2/mock.go
I've discovered this while reviewing #1830. I coudln't find any reason why we were using the v1 API for the v2 tests.
=> test/with_api_v2: remove calls to the v1 API

config/notifiers.go, notify/pagerduty/pagerduty.go
Closes #1784
For clarity, I've chosen to rename the field `text` to `href` in the configuration though it could break people (but I suspect that it isn't widely used).
Unfortunately I don't have a way to validate it. Maybe @seanhoughton, @sbueringer, @mikebryant or @adamdecaf could help (I've looked at the Git history for people that contributed to the PagerDuty code).
=> notify/pagerduty: fix images

.circleci/config.yml
By default Go uses GOMAXPROCS but a Circle CI executor has many cores (> 30) while the CPU and RAM resources are throttled (a medium instance has 2 vCPUs and 4GB of RAM). If we don't limit this to the number of allocated cores, the job is likely to get OOMed and killed.
=> Limit the number of tests executed in parallel

cluster/cluster.go, cluster/delegate.go
- `alertmanager_cluster_alive_messages_total`, total number of alive messages received.
- `alertmanager_cluster_peer_info`, a constant metric labeled by peer name.
- `alertmanager_cluster_pings_seconds`, histogram of latencies for ping messages.
=> cluster: add more metrics

.gitignore, notify/email/email.go, notify/email/email_test.go, notify/email/testdata/auth.yml, notify/email/testdata/noauth.yml, notify/notify.go
In addition, this commit passes the current context to the TCP dialer and it doesn't log any QUIT errors if the email delivery wasn't successful.
Related #1944 
Related #980
=> notify/email: wrap all errors for easier debugging

notify/opsgenie/opsgenie.go, notify/opsgenie/opsgenie_test.go
Ref: https://groups.google.com/d/msg/prometheus-users/3sAQ9kxEgPI/rE-ADUYiBAAJ
Tested against OpsGenie API, the error message looks like this:
```
cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422: {\"message\":\"Request body is not processable. Please check the errors.\",\"errors\":{\"priority\":\"should be one of [ P1, P2, P3, P4, P5 ]\"},\"took\":0.005,\"requestId\":\"610e618e-7138-4898-9c70-c4eef2d68bf8\"}
```
=> notify/opsgenie: log error from OpsGenie API

README.md, cmd/alertmanager/main.go
Fixes https://github.com/prometheus/alertmanager/issues/1814
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> docs/flags: Make it explicit that HA is enabled by default and how to disable it.

config/notifiers.go, config/notifiers_test.go, notify/slack/slack.go
Closes https://github.com/prometheus/alertmanager/issues/1220.
=> Add the ability to configure slack markdown field

notify/hipchat/hipchat.go, notify/hipchat/hipchat_test.go, notify/opsgenie/opsgenie.go, notify/opsgenie/opsgenie_test.go, notify/pagerduty/pagerduty.go, notify/pagerduty/pagerduty_test.go, notify/pushover/pushover.go, notify/pushover/pushover_test.go, notify/slack/slack.go, notify/slack/slack_test.go, notify/util.go, notify/util_test.go, notify/victorops/victorops.go, notify/victorops/victorops_test.go, notify/webhook/webhook.go, notify/webhook/webhook_test.go
=> notify: refactor code to retry requests

cli/check_config.go, cli/test_routing_test.go, cli/utils.go, config/config.go, config/config_test.go, config/coordinator.go
The origin field of config is not currently in use. It can be used to replace local variables
Signed-off-by: johncming <johncming@yahoo.com>
=> config: use the origin field instead of local var

cmd/alertmanager/main.go, notify/notify.go, notify/notify_test.go
This was the last package that was still using the global registry.
=> notify: don't use the global metrics registry

go.mod, go.sum, vendor/golang.org/x/sys/windows/security_windows.go, vendor/golang.org/x/sys/windows/syscall_windows.go, vendor/golang.org/x/sys/windows/zsyscall_windows.go, vendor/modules.txt
Updating projects using libraries that were recently updated to support Risc-V architecture.
Go upstream work is tracked on: golang/go#27532
Risc-V software support tracker on https://github.com/carlosedp/riscv-bringup
Signed-off-by: CarlosEDP <me@carlosedp.com>
=> Update x/sys and x/net modules to support Risc-V

notify/wechat/wechat.go
it should check the HTTP status code first.
=> notify/wechat: adjust result check sequence.

dispatch/dispatch.go, inhibit/inhibit.go, inhibit/inhibit_test.go, provider/mem/mem.go, store/store.go, store/store_test.go
Ref https://github.com/coreos/kube-prometheus/issues/205
The aggregation group is already responsible for removing the resolved alerts. Running the garbage collection in parallel introduces a race and eventually resolved notifications may be dropped.
I couldn't find a way to add a test since the first GC happened after 15min. I have a script to reproduce the issue and I've verified that the issue is gone after this change. The script goes like:
* send firing alert repeatedly for about 14min.
* send resolved alert at 14min45s (just before the GC which itself happens before the next group interval).
```
route:
group_by: [job]
group_wait: 10s
group_interval: 30s
repeat_interval: 10h
```
=> dispatch: don't garbage-collect alerts from store

types/match.go, types/match_test.go
matcher miss a method for equal.  The current way is that compare two structures directly.  matcher needs a special method for compare equal. 
add a test case for matchers compares.
=> types: remove unused equal method and add test case.

nflog/nflog.go
use errors.New instead of fmt.Errorf for no custom error msg.
=> nflog: use errors.New instead of fmt.Errorf for no custom error msg.

api/v1/api.go
relatively rare  typo:
https://github.com/prometheus/alertmanager/blob/e4437ab54f26dbcd66b90eaf4d5701fee98a1da6/api/v1/api.go#L791-L796
return error more common.
=> api/v1: return error more clear and common.

dispatch/dispatch_test.go
`GroupBy` is empty in the test case which is not matched with production code.
https://github.com/prometheus/alertmanager/blob/ab537b5b2f9dc55cc4a1faed5df5618c7648c088/dispatch/dispatch_test.go#L42
In production code,  `GroupBy` is not empty unless `GroupByAll` enabled. when `GroupBy` no empty, it contains all the keys of responding labels.
https://github.com/prometheus/alertmanager/blob/4535311c34f13ddcc492e3c1e769eec85c18dde2/dispatch/dispatch.go#L253
https://github.com/prometheus/alertmanager/blob/4535311c34f13ddcc492e3c1e769eec85c18dde2/dispatch/dispatch.go#L237
=> dispatch: route group labels should contain group common label.

cluster/cluster.go
The Invalid listen address errors should be as same as Invalid advertise address.
Signed-off-by: Kien Nguyen <kiennt2609@gmail.com>
=> Consolidate invalid address log

inhibit/inhibit.go, provider/mem/mem.go, store/store.go, store/store_test.go
I've spotted a date race in a CI run. It's very unlikely to happen but still better to fix it.
```
==================                                                                             
WARNING: DATA RACE                                                                             
Write at 0x00c000016c10 by goroutine 15:                                                       
github.com/prometheus/alertmanager/store.TestGC.func2()             
/home/simon/workspace/src/github.com/prometheus/alertmanager/store/store_test.go:91 +0x6e 
github.com/prometheus/alertmanager/store.(*Alerts).gc()
/home/simon/workspace/src/github.com/prometheus/alertmanager/store/store.go:84 +0x346
github.com/prometheus/alertmanager/store.(*Alerts).Run.func1() …
```
=> store: fix potential flaky test

config/config.go, config/config_test.go, config/testdata/conf.nil-match_re-route.yml, config/testdata/conf.nil-source_match_re-inhibitiion.yml, config/testdata/conf.nil-target_match_re-inhibitiion.yml
Otherwise the program could panic.
```yaml
route:
receiver: empty
routes:
- match_re:
invalid_label:
receiver: empty
receivers:
- name: empty
```
```
level=info ts=2019-10-24T15:31:19.726Z caller=main.go:217 msg="Starting Alertmanager" version="(version=0.19.0, branch=master, revision=a75cd02786dfecd25e2469fc4df5d920e6b9c226)"
level=info ts=2019-10-24T15:31:19.726Z caller=main.go:218 build_context="(go=go1.13.1, user=simon@simon-laptop, date=20191024-15:20:11)"
level=info ts=2019-10-24T15:31:19.758Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=192.168.1.17 port=9094
level=info ts=2019-10-24T15:31:19.759Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-10-24T15:31:19.781Z …
```
=> config: forbid nil regexp matchers

config/config.go, config/config_test.go, dispatch/route.go
I might be wrong but I think that JSON marshaling is a left-over from older Alertmanager versions.
=> config: remove support for JSON marshaling

config/notifiers.go, notify/pagerduty/pagerduty.go, notify/pagerduty/pagerduty_test.go
Relates to #2082 
When loading the configuration, we check that`routing_key` and `service_key` aren't empty but we didn't do the same after expanding the template.
=> notify/pagerduty: check that PagerDuty keys aren't empty

silence/silence.go, silence/silence_test.go, test/with_api_v1/acceptance/silence_test.go, test/with_api_v2/acceptance/silence_test.go
=> At least one non-empty silence matcher

README.md
All the examples are written with `$ amtool` except for two of them.
This change will add `$ amtool` for all of them.
=> README.md: Add consistency for amtool examples

template/template.go, template/template_test.go
Since it's impossible to create a string slice in a Go template by
default, add a function to work around this problem.
The use case is to make it easy to call KV.Remove with an arbitrary
slice inside a template.
This is a follow up to https://github.com/prometheus/alertmanager/pull/2094
=> template: add the default template function stringSlice

notify/notify.go
https://github.com/prometheus/alertmanager/blob/311650658ada0ad906b6a6a77c985b7536a09f14/nflog/nflog.go#L454-L481
It is difficult to return a value from a function call that is not of length 0 or 1, and the length 2 check has two drawbacks
1. If the query function returns a length of 3 in the future, the check is skipped (probably not desired) and default is probably better
2. Checks of length 2 should be expiration codes
Signed-off-by: johncming <johncming@yahoo.com>
=> notify: optimize length check.

notify/slack/slack.go, notify/slack/slack_test.go
=> slack: retry 429 errors

cluster/cluster_test.go
Still trying to fix `github.com/prometheus/alertmanager/test/with_api_v2/acceptance`
=> Fix TestClusterJoinAndReconnect on macos

cmd/alertmanager/main.go, dispatch/dispatch.go, dispatch/dispatch_test.go
This change adds 2 metrics:
* `alertmanager_dispatcher_aggregation_groups`, number of active aggregation groups.
* `rate(alertmanager_dispatcher_alert_processing_duration_seconds`, quantile-less summary for the processing of alerts by the dispatcher.
=> dispatch: add metrics

CHANGELOG.md, notify/slack/slack.go, notify/slack/slack_test.go
This reverts commit 26cc96a787b8b3b597a14fb7ced986194ae2c062.
As discussed in https://github.com/prometheus/alertmanager/issues/2121, when an API endpoint applies rate-limits, retrying immediately might cause more harm than waiting a bit.
From the Slack [documentation](https://api.slack.com/docs/rate-limits):
> Continuing to send messages after exceeding a rate limit runs the risk of your app being permanently disabled.
For now, I think that retrying the notification on the next `group_interval` as it was before is the safest option.
cc @roidelapluie @gavk34 @stuartnelson3 @mxinden
=> Revert "slack: retry 429 errors (#2112)"

client/client_test.go, config/config.go
=> config: fix JSON unmarshaling for HostPort

cmd/alertmanager/main.go, dispatch/route.go, dispatch/route_test.go
move walkRoute to dispatch package for better encapsulation and add test case.
=> move walkRoute to dispatch package.

MAINTAINERS.md
I have not been very active as a maintainer of Alertmanager in the last couple of month and I don't think this will change in the near future. Thus I think it is time for me to remove myself from the maintainers list.
I will stick around within the Prometheus ecosystem and stay subscribed to all notifications of the Alertmanager repository for a bit longer.
I learned a lot, thanks everyone!
Signed-off-by: Max Inden <IndenML@gmail.com>
=> MAINTAINERS.md: Remove Max Inden (mxinden)

dispatch/route.go, dispatch/route_test.go
Fixes https://github.com/prometheus/alertmanager/issues/1857
=> Inherit their parent route's grouping when "group_by: [...]"

notify/slack/slack.go
Add the slack channel when logging error from slack.
https://github.com/prometheus/alertmanager/issues/2176
=> Add slack channel when logging error.

.github/stale.yml
During the dev Summit 2019/2, there was a consensus to mark stale PR
after 60 days.
This change is adding the stale bot configuration required for this.
The stale bot has already access to the Prometheus organization. It
does _not_ comment and does _not_ close the stale pull request. It just
adds a label 'stale'.
This is already done in the collectd_exporter repository and there it
works as expected.
https://docs.google.com/document/d/1VVxx9DzpJPDgOZpZ5TtSHBRPuG5Fr3Vr6EFh8XuUpgs/edit
=> Mark pull request as stale after 60d of inactivity

dispatch/dispatch.go
The new dispatcher metrics are not registered on the provided registerer, but on the default one. This PR fixes it, as well as handle the case the input registerer is `nil`.
=> Fixed dispatcher metrics registration

api/v2/api.go, api/v2/api_test.go, api/v2/models/cluster_status.go, api/v2/openapi.yaml, api/v2/restapi/embedded_spec.go
Before this change, the API returns a `null` value for `peers`:
```
$ curl -s localhost:9093/api/v2/status | jq '.cluster'
{           
"peers": null,           
"status": "disabled"  
}  
```
After
```
{           
"peers": [],           
"status": "disabled"  
}
```
=> api/v2: return empty array of peers when disabled

dispatch/dispatch.go, dispatch/dispatch_test.go
Fixes: #2182 
By ensuring operations on the `cancel` and `ctx` field are wrapped with a mutex this removes the race condition from the dispatcher.
=> Fix race condition in dispatcher

README.md, doc/examples/simple.yml
I would say mentioning this wherever possible would help that others get to know this as early as possible. The [`simple.yml` is also referenced from the documentation](https://github.com/prometheus/docs/blob/master/content/docs/alerting/configuration.md#L52-L53). Means it's part of the documentation itself, isn't it?
We've learned it the harder way: All services monitored with the `ServiceMonitor` from the [`Prometheus Operator`](https://github.com/coreos/prometheus-operator) get a `service` label. Therefore we've set `equal: ['service']`. Except alerts based on the [`kube-state-metrics` service](https://github.com/kubernetes/kube-state-metrics) which needed an extra `equal: ['container']` instead. We didn't know this while configuring this (relates to …
=> docs: Add warning that inhibition occurs on missing `equal`

README.md
A lot of people (including myself) seem to struggle with setting up high availability. I think it makes sense to improve the remarks on UDP/TCP for high availability.
=> Improve remark on UDP/TCP for high availability

config/notifiers.go, go.mod, notify/pagerduty/pagerduty.go, notify/pagerduty/pagerduty_test.go
PagerDuty will soon start enforcing a size limit of 512KB on all events. To prevent sending events that are larger than that, this PR implements the proposal that was decided in this issue https://github.com/prometheus/alertmanager/issues/2178
The size of events are checked after they are encoded into json. If the size is above 512KB, the custom details (or details for v1 events) are replaced with an error message.
This was my first time writing Go so the code may not be the best :)
=> Enforce 512KB event size limit for Pagerduty events

cluster/cluster.go
We forgot to log the error message from the `Join()` function which makes it harder to understand what's happening...
cc @liliC
=> cluster: log error on reconnect failures

cli/cluster.go, cli/format/format.go, cli/format/format_extended.go, cli/format/format_json.go, cli/format/format_simple.go, cli/format/sort.go, cli/root.go
Closes #2192 
This pr implements amtool cluster show command
Simple output
```
$ amtool --alertmanager.url http://localhost:9094 cluster show
Cluster Status:  ready
```
Extended output
```
$ amtool --alertmanager.url http://localhost:9094 cluster show -o extended
Cluster Status:  ready
Address            Name
192.30.10.111:9094  01E4R8TX0WTNW1JYH3MB0NGHA1
192.30.42.5:9094    01E3S5C0DTS3RMJZ71RH8LPD69
192.30.42.140:9094  01E3S5BA4TX4KR030ZXXKEA6WC
```
Json output
```
$amtool --alertmanager.url http://localhost:9094 cluster show -o json
{"name":"01E3S5BY4GX4KR034ZXXREA6WC","peers":[{"address":"192.30.42.140:9094","name":"01E3S5BA4TX4KR030ZXXKEA6WC"},{"address":"192.30.42.5:9094","name":"001E3S5C0DTS3RMJZ71RH8LPD69"},{"address":"192.30.10.111:9094","name":"01E4R8TX0WTNW1JYH3MB0NGHA1"}],"stat …
```
=> Add cluster command to show cluster and peer statuses.

cmd/alertmanager/main.go
When `routePrefix` is set alertmanager doesn't redirect traffic from `/` to target `routePrefix`
Prometheus implemented it with an http redirect to targeted `routePrefix`,  [here](https://github.com/prometheus/prometheus/blob/cd12f0873c3eb2031f7ba9b2e169449aa1012e3f/web/web.go#L328-L330)
Add the same code, to have the same comportement
=> Add redirect on / to routePrefix

api/v2/api.go, pkg/labels/parse.go
When an API v2 handler logged a message, the log wouldn't include the
path and method. Since different handlers perform the same
validations (e.g. matchers for alerts and silences), it isn't easy to
know which handler was invoked (though the logged filename + line number provides a hint).
=> api/v2: add path and method to API v2 logs

config/notifiers.go, notify/webhook/webhook.go, notify/webhook/webhook_test.go
The webhook notifier is the only notifier that does not allow templating
on the Alertmanager side. Users who encounter occasional alert storms
(10ks of alerts going off at once for the same group) have reported
webhook receiver systems not being able to cope with the load caused by
the resulting large webhook notifier messages (the alerting rules also
contained large annotations that can't be stripped away due to lack of
templating). Reducing group size also wasn't an option, but this change
proposes to allow truncating the list of alerts sent in the webhook body
to a provided maximum length. This assumes that e.g. if a group receives
20k alerts, you really are fine only receiving 10k because you wouldn't
be able to check them all anyway.
=> Allow limiting maximum number of alerts in webhook

notify/notify.go
Alertmanager can experience occasional failures when sending
notifications to an external service. If the operation succeeds after
some retry, the 'alertmanager_notifications_failed_total' metric
increases but nothing is logged (unless running with log.level=debug).
Hence an operator might receive an alert about notification failures but
wouldn't know which integration was failing.
With this change, notification failures are logged at the warning level.
To avoid log flooding, similar failures on retries aren't logged.
Additional information on the failing integration has also been added.
cc @roidelapluie for review. Based on user's feedback from https://github.com/prometheus/alertmanager/issues/2147#issuecomment-626221046.
=> notify: improve logs on notification errors

.circleci/config.yml
Version `0..6.0` of the orb was buggy and led to container images not being pushed to the registries.
cc @juliusv
=> .circleci/config.yml: bump Prometheus orb version

config/notifiers.go, notify/opsgenie/opsgenie.go, notify/opsgenie/opsgenie_test.go
Introduce two new config options for the Opsgenie receiver:
- `all_labels_as_details`: If `true`, all labels are propagated to the Opsgenie details (default is `false`).
- `labels_as_details`: An optional list of labels, which should be propagated to the Opsgenie details.
If the `all_labels_as_details` and `labels_as_details` value isn't set, the existing `details` option is used.
Closes #682.
=> Propagate labels to Opsgenie details

.github/ISSUE_TEMPLATE.md
As 0.21.0 will update clusters, we want to know of people have all their
AM at the same release when they open a clustering issue.
=> Ask for all versions

CHANGELOG.md, notify/notify.go
By default the library implementing the back-off timer stops the timer
after 15 minutes. Since the code never checked the value returned by the
ticker, notification retries were executed without delay after the 15
minutes had elapsed (e.g. for `group_interval` greater than 15m).
This change ensures that the back-off timer never expires.
Relates to #2286, hough it doesn't fix what's reported there.
=> notify: always retry with a back-off

docs/configuration.md
Found while studying https://www.prometheus.io/docs/alerting/latest/configuration/
---
Relative links are rendered relatively to the source repository, so this link points to GitHub at the moment.
This commit changes the link to an absolute URL, bringing readers to the Routing tree editor.
=> docs: Fix dead link to visual route editor

docs/configuration.md
Relative links are rendered relatively to the source repository, so this
link points to GitHub at the moment.
This commit changes the link to an absolute URL, bringing readers to the
Routing tree editor.
Signed-off-by: Manuel Hutter <manuel@hutter.io>
=> docs: Fix dead link to visual route editor (#2298)

docs/configuration.md
PagerDuty has restructured their documentation, making links stale
=> Update PagerDuty doc links

config/notifiers.go, config/notifiers_test.go, docs/configuration.md, notify/wechat/wechat.go, notify/wechat/wechat_test.go
According to the WeChat work official API document, adding markdown type message support.
https://translate.google.com/translate?hl=en&sl=zh-CN&tl=en&u=https%3A%2F%2Fwork.weixin.qq.com%2Fapi%2Fdoc%2F90000%2F90135%2F90236%23markdown%25E6%25B6%2588%25E6%2581%25AF&prev=search
=> notify: add markdown support for wechat

config/config.go, config/notifiers.go
The "empty" boolean is the false value. This means that values of false will not
be present in the YAML output. As such they won't be displayed in the config
section on the Status overview page (/#/status), which can be especially
confusing for the SMTPRequireTLS (smtp_require_tls) field of the configuration
as this one will default to true.
=> do not omit "empty" booleans in yaml output

examples/ha/alertmanager.yml
10s+10s does not really change.
Give 30s for group wait and 5m for group interval seems better.
=> Change HA exemple defaults to be more reasonable

cli/format/format_extended.go, cli/format/format_simple.go
Closes #2204 
Signed-off-by: Fahri Yardımcı
Added state field into both simple and extended output. 
sometimes extended output can be a bit long and can be hard to read sometimes therefore finding the alert state in simple output can things much easier.
Extended output
```
$ ./amtool --alertmanager.url http://alertmanager:9093 alert query -o extended -s -a  'alertname="Watchdog"'
Labels                                                            Annotations  Starts At  Ends At  Generator URL  State
alertname="Watchdog" prometheus="test" severity="none"  message="This is an alert meant to ensure that the entire alerting pipeline is functional.
"                                                                 2020-07-10 11:00:00 UTC  2020-07-16 16:00:00 UTC …
```
=> Add alert status for extended and simple output

examples/ha/alertmanager.yml
It is not needed with Prometheus and can confuse users.
=> Remove resolve timeout from the config shipped by default

notify/pagerduty/pagerduty.go, notify/pagerduty/pagerduty_test.go
PagerDuty Event API v2 [1] requires images to have an `src` property, and links
to have an `href` property.
This commit filters out images and links that don't satisfy those conditions,
to avoid getting an HTTP 400 error in response.
This also adds flexibilty when using templates to configure images and links,
as it's now possible to omit images or links by letting the template return an
empty string for the `src` or `href` property, respectively.
[1]: https://developer.pagerduty.com/docs/events-api-v2/trigger-events/#context-properties
Signed-off-by: Benoît Knecht <bknecht@protonmail.ch>
=> notify/pagerduty: Filter out empty images and links

docs/configuration.md
These fields are all available on the PagerdutyConfig type:
https://github.com/prometheus/alertmanager/blob/59a96579cc9d117ae72cfb6ad45033ee746c6ba8/config/notifiers.go#L201..L203
I took the descriptions from the PagerDuty events-api-v2 docs:
https://developer.pagerduty.com/docs/events-api-v2/overview/
=> Add some missing PagerDuty fields to docs

api/v1/api.go, api/v2/api.go, api/v2/api_test.go
Filtering the alert out when the label is missing precludes a
possible match for an empty value. This change allows the
match to be evaluated.
Closes #2342
Signed-off-by: Victor Araujo <vear91@gmail.com>
=> Make filter labels consistent with Prometheus

notify/notify.go
Fixes: #2361 
Signed-off-by: Max Neverov <neverov.max@gmail.com>
=> Add metric for permanently failed notifications

cli/silence_update.go
A trivial fix to avoid nil pointer dereference. It can occur when `amtool` fails to get silences in `amtool silence update`.
Before:
```shell
$ amtool silence update --alertmanager.url=INVALID-URL --duration=1h 94fbd24a-79fc-40d9-8a11-026c83ab9015
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1793415]
goroutine 1 [running]:
github.com/prometheus/alertmanager/cli.(*silenceUpdateCmd).update(0xc000322a80, 0x1b15d40, 0xc000322ae0, 0xc0000c6120, 0xc000322ae0, 0xc000588ed0)
/Users/koki/go/src/github.com/prometheus/alertmanager/cli/silence_update.go:67 +0x3d5
github.com/prometheus/alertmanager/cli.execWithTimeout.func1(0xc0000c6120, 0x0, 0x0)
/Users/koki/go/src/github.com/prometheus/alertmanager/cli/utils.go: …
```
=> cli: avoid nil dereference in silence update

doc/alertmanager-mixin/alerts.libsonnet, doc/alertmanager-mixin/config.libsonnet
The alert was just looking at the minimum across integrations. So a
complete failure of one integration would be masked by a still working
other integration. With this fix, the `integration` label is retained
(as it was already expected by the `description`), and thus any
one failing integration will trigger the alert.
In addition, an `alertmanagerCriticalIntegrationsRegEx` is provided
that allows to mark integrations as critical. Integrations that are
not used to deliver critical alerts, or those that are just there for
auditing and logging purposes can now be configured to only trigger a
warning alert if they fail.
@duologic relevant to the recent firing of AlertmanagerClusterFailedToSendAlerts in our production environment.
=> Fix and improve AlertmanagerClusterFailedToSendAlerts

pkg/labels/matcher.go, pkg/labels/matcher_test.go, pkg/labels/parse.go, pkg/labels/parse_test.go
@aSquare14 is working on using the same `labels.Matcher` that we already use in the UI and API for the matchers in the configuration, i.e. routing tree and inhibition rules. This will also introduce negative matching as requested in #1023 and simplify the syntax. See #2434. This will also help with making our code more DRY as we currently have two matcher implementation that do more or less the same: `labels.Matcher` and `types.Matcher`. We will still need the latter for silences, as their structure is directly marshaled into the HTTP API responses, so replacing them is a bit more involved.
Anyway, that's just for context.
While discussing all of this with @aSquare14, I realized that `labels.Matcher` has a few issues:
- It doesn't validate that the name is a valid Prometheus label name.
- …
=> Improve labels.Matcher

cli/routing.go, config/config.go, dispatch/route.go, dispatch/route_test.go, doc/alertmanager-mixin/alerts.libsonnet, doc/alertmanager-mixin/config.libsonnet, pkg/labels/matcher.go, pkg/labels/matcher_test.go, pkg/labels/parse.go, pkg/labels/parse_test.go, types/match.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
Related issue : #1023 
Note : I am adding negative matchers for routing in this PR. Will add support for inhibition rules in next PR.
=> Add negative matchers for routing.

config/config.go, inhibit/inhibit.go, inhibit/inhibit_test.go, pkg/labels/matcher.go
Related issue : #1023
Related Pull Requests : #2456 #2434 #2441 
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
=> Add negative matchers for inhibitors

cli/format/format_extended.go
Fixed extended printing to use same regex that is expected to be used when creating silences.
=> Fix extended printing of regex sign

notify/victorops/victorops.go, notify/victorops/victorops_test.go
The error used during the templating of the routing key is not checked before it is later reassigned.
=> fix(notify/victorops): Catch routing_key templating errors

cluster/channel.go, cluster/cluster.go
I understand `MaxGossipPacketSize` has several implications in the way clustering works (oversized messages are always propagated via TCP which influence the number of parallel connections we make) but also downstream implementations might want to configure this.
I don't think the alertmanager offers any guarantees if downstream implementations change this value so it should be safe to make public? 😄
=> Make MaxGossipPacketSize public

silence/silence.go
This has been discussed in #2479. Even if the conclusion there was
that we don't need this in a bugfix release, it's still better to have
this kind of robustness. So this introduces the same check into the
main branch.
@vladimiroff @aSquare14
=> Catch unknown matcher types in gossipped silences

api/v2/api.go, api/v2/api_test.go
Fixes #2283.
This PR changes how `gettableSilenceMatchesFilterLabels` in api/v2 checks whether a silence matches a given filter, especially for regex cases. In short,
- before: a silence matches a filter if a pattern value in the silence matches pattern strings of the filter by regex.
- after: a silence matches a filter if a pattern value in the silence and pattern strings of the filter are equivalent.
For instance, as shown in figure #2283, a silence `alertname~=(foo|bar)` didn't match a filter of the same pattern `alertname~=(foo|bar)`, since the regex match fails. After the fix, the silence and filter will match as we use string comparison instead.
=> api: check silence matching by string comparison in getSilences

docs/configuration.md
Signed-off-by: machine424 <ayoubmrini424@gmail.com>
=> Fix a typo in docs/configuration.md

api/api.go, api/v1/api.go, api/v2/api.go, cluster/cluster.go, notify/notify.go
A Peer as defined by the `cluster` package represents the node in the
cluster. It is used in other packages to know the status of all of the
members or how long should we wait to know if a notification has already fired.
In Cortex, we'd like to implement a slightly different way of
clustering (using gRPC for communication and a
hash ring for node discovery).
This is a small change to support that by changing the consumer of other
packages to an interface.
~~Silences and Notification channels don't need an interface as they take
a `func([]byte) error` as a parameter.~~
Edit: Ended up creating an interface for it as I think it's somewhat useful.
Signed-off-by: gotjosh <josue@grafana.com>
=> Clustering: Interface for Peers in other packages

cli/root.go, cmd/alertmanager/main.go
=> Amtool and Alertmanager binaries print to stdout

cluster/cluster.go, cluster/cluster_test.go, notify/notify.go
WaitReady is a blocking call and so should accept a Context in order to
be responsive to cancellation of the notification pipeline for any reason.
Signed-off-by: Steve Simpson <steve.simpson@grafana.com>
=> Clustering: Change WaitReady to accept a Context.

docs/notifications.md
Add a line break before the list to make sure it is properly rendered on the documentation website.
=> docs: Fix list formatting

notify/notify.go, notify/notify_test.go
We have `NewRetryStage` method which takes this `metrics` struct, and given both the struct and the method to create it is unexported, it is impossible to use vendored `NewRetryStage`. We would like to use it in Grafana. Can we export them?
=> Export `newMetrics` function and `metrics` struct

MAINTAINERS.md
Following  Andrey's amazing work in the alertmanager UI, I am formally inviting him to join the project as maintainer.
According to our governance https://prometheus.io/governance/ , this change is subject to lazy consensus.
=> Add Andrey as maintainer

cluster/cluster.go, cluster/delegate.go
In Cortex, we use the clustering implementation to achieve HA for each tenant. Under this scenario, we create one state per tenant and have that be synchronised through gossip.
Under this scheme, the state map can end up being called concurrently if we try to add a state while gossiping to another node. Overall, I feel it's safer to just make sure we synchronise access upstream to avoid downstream consumers worrying about this.
=> Clustering: Fix unsynchronised access

dispatch/dispatch.go
It looks as if `Dispatch.Stop` doesn't unlock the mutex if `d.cancel == nil`. I'm rectifying it to unlock it also if `d.cancel == nil` and the method returns early. It seems to fix a deadlock in Grafana (on server shutdown), during our test suite.
[Here](https://gist.github.com/aknuds1/a9dcff50dd8cba2b82f570ed6b942923)'s a stacktrace of the involved goroutines when the deadlock occurs.
Let me know if you want me to write a test also.
=> Dispatch: Make sure mutex gets unlocked on call to Stop

docs/configuration.md, go.mod, go.sum
This PR upgrades the common version so that OAuth 2.0 is supported and properly documents the config.
cc @roidelapluie
=> Add OAuth 2.0 Config

docs/configuration.md
This documentation change is intended to lift moratorium on new AlertManager receivers with long-term maintenance plan.
=> Lift moratorium on AlertManager receivers with long-term maintenance plan

doc/examples/simple.yml, docs/configuration.md
While the documentation for the matchers themselves was updated, we
missed the examples.
I propose to merge this into the release-0.22 branch so that it gets
included in the ongoing release.
cc: @asquare14
=> Update matcher examples

dispatch/dispatch.go, dispatch/dispatch_test.go
This PR should fix #2562.
_Please see the issue for more details. I also suggest to review this with enabling "Hide whitespace changes"._
=> Fix race condition causing 1st alert to not be immediately delivered when group_wait is 0s

pkg/labels/matcher.go, pkg/labels/matcher_test.go
Default the isEqual flag to true in alertmanager                        
Solves #2602 - the new version of alertmanager introduces an isEqual    
flag to support != matchers in alertmanager silences. Clients set this  
to true in the JSON blob sent to the api to indicate a foo=bar matcher, 
and to false to indicate foo!=bar. Due to gos unmarshalling, anything   
that _doesn't_ include this flag will default to false (i.e. a !=       
matcher), so any clients that aren't aware of this flag (such as amtools
before negative matchers and the new api) will not send it, and when you
think you are making a foo=bar matcher, alertmanager will interpret that
as a not equals.                                                        
This commit changes the Unmarshaling of the v1matcher struct to …
=> Default the isEqual flag to true in alertmanager

notify/notify_test.go, provider/mem/mem_test.go, silence/silence.go, silence/silence_test.go, types/types.go
Previously, if a pending silence existed for an alert, and it later
became active without any silences getting added in the meantime, we
would miss the existence of that newly active silence.
This is my attempt to fix #2426 (and possibly others). This is a late night hack, and we should also add a unit test to expose the behavior. But I thought I put this out so that you can stop me if I'm on the wrong track here.
See #2586 for @waitstory's earlier attempt, which made me aware of the issue in the first place.
=> Include pending silences for future muting decisions

cmd/alertmanager/main.go, dispatch/dispatch_test.go, go.mod, go.sum, provider/mem/mem.go, provider/mem/mem_test.go, provider/provider.go
This PR adds callback to `*mem.Alerts` type, which can be used for implementing limits on number of in-memory alerts.
We would like to use this (or similar) mechanism in Cortex, to protect the Cortex cluster against misconfigured or malicious clients to avoid OOMing alertmanager (in Cortex, we start many Alertmanager instances in single process, one for each tenant).
Alertmanager itself could use this callback to implement similar protection, and if there is interest, I can send PR doing just that.
=> Added possibility to pass callback to `mem.Alerts`, useful for implementing limits on alerts.

cmd/alertmanager/main.go, dispatch/dispatch.go, dispatch/dispatch_test.go
This PR introduces limit for maximum number of per-route groups that Alertmanager's dispatcher can have. Dispatcher cannot report error back when limit is hit, so it just logs this and increments metric.
Similar to https://github.com/prometheus/alertmanager/pull/2569, we would like to use this limit in Cortex to protect Cortex' multitenant alertmanager against misconfigurations. In Prometheus Alertmanager itself this limit is not used. If there is interest to have this limit configurable in Prometheus Alertmanager, I'm happy to send new PR with that change.
(TODO: I'd like to add unit test for cleanup of groups, but other than that PR is ready for review / discussion about the approach.)
=> Added group limit to dispatcher.

config/config.go, config/config_test.go
`MarshalJSON` method must return valid JSON or error.
This PR fixes JSON marshaling ~and unmarshalling~ of `config.URL` and `config.Regex` wrappers with `nil` values. Such values are now mashalled into `null` json literal ~, and can be unmarshalled properly as well. (Empty strings are also unmarshalled into wrappers with `nil` value).~
Also fixed JSON marshalling of empty `Matchers`.
I will send similar patch to `common` repository, which also has `config.URL`.
**Update: To avoid introducing breaking changes, I've removed changes to unmarshalling. Unit tests documenting current behaviour are left in place.**
=> Fix mashaling of URL, Regex wrappers with nil value, and empty Matchers.

docs/configuration.md
We copy-pasted this from the docs. Took us a while to see the typo, so here's the fix.
=> Docs: Fixed typo 'weeekday_range'

doc/alertmanager-mixin/alerts.libsonnet
The expression `alertmanager_cluster_members{job="alertmanager"}[5m])` is assumed to return
one series for each alertmanager instance in the cluster. When running inside Kubernetes,
alertmanager pods can get evicted and rescheduled. This can change the instance label and
produce a new series for that alertmanager instance.
When this happens, there will be a short interval in which Prometheus returns values from both
the new series and the old series. As a result, counting the number of
series for the `alertmanager_cluster_members` metric will overestimate the
number of instances in the given cluster.
This commit modifies the the AlertmanagerMembersInconsistent alert to group series by
`alertmanagerNameLabels` when calculating the number of alertmanagers in
the cluster.
Please refer to the …
=> Improve the AlertmanagerMembersInconsistent alert

pkg/labels/parse.go, pkg/labels/parse_test.go
Fixes https://github.com/prometheus/alertmanager/issues/2630
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> matchers: Parse Matcher now expects consistent enclosing with quotes.

notify/notify.go, notify/notify_test.go
The mute time mechanism uses the internal timer of alert aggregation groups to determine the current time, which is then used to determine whether a route should be muted. By default, this time fires in the local time of the server, not UTC as desired. 
This PR ensures comparisons are only made in UTC.
=> Ensure time interval comparisons are in UTC

README.md
Via original docs https://prometheus.io/docs/alerting/latest/configuration/#inhibit_rule
=> Docs: target_match and source_match are DEPRECATED

docs/configuration.md, notify/opsgenie/opsgenie.go
* OpsGenie provides management of both alerts and incidents.
* package opsgenie uses OpsGenie alert api, so let's refer to
alert instead of incident in logs and doc to avoid confusion.
=> OpsGenie: refer to alert instead of incident

README.md, cli/root.go, cli/template.go, cli/template_render.go
Add a new template rendering command that allows users to test out their
templates. This is especially needed because small bugs in templates do
not surface until alertmanager actually tries to render them.
Signed-off-by: Giedrius Statkevičius <giedrius.statkevicius@vinted.com>
=> cli: add new template render command

cli/format/format.go
This is the best we can do to make amtool support old releases.
Supersedes #2634
Fix #2666
=> Fix empty isEqual in amtool.

README.md, cli/root.go
Just like with prometheus or alertmanager endpoints, we sometimes need to disable TLS certificate check. We can do that providing `<tls_config>` section there.  
amtool is a simpler thing but it does provide us some basic features like providing custom port and performing basic auth. I think skipping tls verification will fit in here too.
=> Add ability to skip TLS verification for amtool

cli/root.go, go.mod
This change detects the alertmanager version when initiating the client.
It ignores most errors since I expect amtool to fail later.
If amtool is not compiled with proper version, we do not do anything
either.
We use MajorMinor for now as we have not reach 1.0, but we still allow
the bugfix version number (Z in x.y.Z) to differ.
=> amtool: Detect version drift and warn users

docs/configuration.md
1. The `configuration.md` use both of `’` and `'`. I unified them as `'`.
2. I think `case-insentive` should probably be `case-insensitive`.
3. `sender's address.` makes a little more sense.
=> Fix some typo

cmd/alertmanager/main.go, nflog/nflog.go, nflog/nflog_test.go, silence/silence.go, silence/silence_test.go
This enables support for custom Maintenance callbacks as part of the periodic maintenance of silences and notification logs.
Effectively a no-op for the Alertmanager but allows a downstream implementation to inject custom logic as part of it.
=> Enable support for custom callbacks as part of maintenance

config/notifiers.go, docs/configuration.md, notify/opsgenie/opsgenie.go, notify/opsgenie/opsgenie_test.go
=> Add the option to update message and description when sending alerts to opsgenie

silence/silence.go, silence/silence_test.go
https://github.com/prometheus/alertmanager/pull/2689 introduced a
regression where the default maintenance function would no longer be
called even if no override was specified. The Alertmanager now crashes
on any silence maintenance run without this fix.
=> Correctly call default silence maintenance function

docs/configuration.md
Docs says the default value of `send_resolved` of `sns_configs`, introduced at https://github.com/prometheus/alertmanager/pull/2615, is `false`. On the other hand, implementation says it's `true`.
https://github.com/prometheus/alertmanager/blob/e35efbddb66a73fd8723be5334477e76f21fbd19/config/notifiers.go#L133-L136
Personally I prefer it's `false`, but this feature has been already released. So I leave the value as it is and fix the docs.
=> docs: Fix default value of send_resolved for sns_configs

cli/silence_query.go
This PR adds a `--created-by` argument to the `amtool silence query` command so that silences can be filtered by the author they were created with in `amtool silence add --author=<name>`.
Fixes https://github.com/prometheus/alertmanager/issues/2410, fixes https://github.com/prometheus/alertmanager/issues/2476.
=> Allow filtering silences by createdBy author

notify/opsgenie/opsgenie.go, notify/pagerduty/pagerduty.go, notify/pushover/pushover.go, notify/slack/slack.go, notify/sns/sns.go, notify/victorops/victorops.go, notify/webhook/webhook.go, notify/wechat/wechat.go
We are re-enabling HTTP 2 again. There has been a few bugfixes upstream
in go, and we have also enabled ReadIdleTimeout.
=> Enable HTTP 2 again

docs/https.md, go.mod, go.sum
Similar to https://github.com/prometheus/prometheus/pull/9546/
=> Add support for security-related HTTP headers

cluster/advertise.go, cluster/advertise_test.go, cluster/cluster.go, cluster/cluster_test.go, cmd/alertmanager/main.go
Before this change, Alertmanager would refuse to startup if using a
advertise address binding to any address (0.0.0.0), and the host only
had an interface with a public IP address. After this change we feature
flag permitting the use of a discovered public address for cluster
gossiping.
=> Add feature flag to enable discovery and use of public IPaddr for clustering.

config/notifiers.go, docs/configuration.md, notify/opsgenie/opsgenie.go, notify/opsgenie/opsgenie_test.go
=> opsgenie: Extend config with 'entity' and 'actions' fields

config/config.go
Before this PR, when marshalling to JSON, the go variable name would be taken (respective 'Name' and 'TimeIntervals') as JSON field name. With this PR we take instead the same name as for the YAML fields as everywhere else in the configuration.
=> Expose the fields from MuteTimeInterval in JSON using the YAML field name

test/with_api_v1/acceptance.go, test/with_api_v1/helper.go, test/with_api_v1/helper_test.go
This is confusing as it sits in the root of the repo. Considering we
have a v2 client lib at (https://github.com/prometheus/alertmanager/blob/main/api/v2/client/alertmanager_client.go) this commit removes the v1 one to try and avoid
that confusion
Solves #2762
=> Remove v1 client lib

docs/configuration.md
When trying to create more complex matchers, I wasn't sure whether the alert's labels had to match all matchers (AND) or just one (OR) in order to be sent. Looks like the source code indicates matchers are always ANDed together anywhere the `Matchers` type is used: https://github.com/prometheus/alertmanager/blob/fd0929ba9fc58737a9c91f24771862692fa72d17/pkg/labels/matcher.go#L179-L185
Also I see my editor trimmed trailing whitespace. I figure that's desirable, but I can undo it if need-be.
It does feel like "ANDed" is a weird word, but I guess it's somewhat common: https://english.stackexchange.com/a/79744
If there's a less obscure way to describe logical AND, I'm open to changing it.
=> Document that matchers are ANDed together

config/config.go, config/config_test.go
Unmarshal should validate that the root route does not contain any matchers. Prior to this change,
only the deprecated match structures were checked. It adds a check for matchers provided with the updated matching syntax.
=> config: root route should have empty matchers

ui/app/.gitignore
A command `make ui/app/script.js` sometimes generates temporary files and does not remove them correctly. This is because the following line is evaluated by Make even if `script.js` was already generated.
https://github.com/prometheus/alertmanager/blob/1b8afe7cb5aafe59442e35979ec57401145ea26b/ui/app/Makefile#L45
It is difficult to remove these files perfectly because BSD mktemp(1) may create multiple files before returning a file name.
https://www.freebsd.org/cgi/man.cgi?query=mktemp&sektion=1
> Any number	of temporary files may be created in a single invocation, including one based on the internal template	resulting from the `-t` flag.
So I just ignore them by `.gitignore`.
(Note that they are removed when running `make clean`: <https://github.com/prometheus/alertmanager/blob/1b8afe7cb5aa …
=> chore: Let git ignore temporary files for ui/app

notify/slack/slack.go
Signed-off-by: Prashant Balachandran <pnair@redhat.com>
Fixed issue https://github.com/prometheus/alertmanager/issues/2769
=> Truncating fields that are sent to slack

notify/sns/sns.go
Since the TopicARN field is a template string, it's safer to check for
the ".fifo" suffix in the rendered string.
@roidelapluie does it make sense?
=> notify/sns: detect FIFO topic based on the rendered value

docs/configuration.md
The Markdown variant used on prometheus.io is different from the GitHub one and
requires code blocks to be indented by four spaces to be recognized as part of
a list item vs. terminating the list.
<hr/>
**Before:**
<hr/>
**After:**
=> Fix markdown list describing Alertmanager matchers

api/v2/api_test.go, silence/silence.go, silence/silence_test.go
Delete silence currently returns HTTP 500 if called on an expired silence.  This makes it non-idempotent, as the following call sequence can result:
```
T0 initial: DELETE /api/v1/silence/MySilence => Timeout (but actually succeeded)
T1 retry:   DELETE /api/v1/silence/MySilence => 500
```
After this sequence, the user is left uncertain whether there's a problem in AlertManager/Prometheus.  Even fetching the silence to verify its state won't confirm whether the 500 was indicative of a separate underlying problem that could manifest in other ways later.
Prometheus exposes the delete_series API which does exhibit idempotent behaviour -- calling delete_series on an already deleted series returns the same status as the initial delete_series call:  HTTP 200.
This PR changes Silences.expire(id) …
=> Return no error when deleting expired silence

cmd/alertmanager/main.go
This PR adds two new CLI args to support custom snapshot intervals for nflogs and silences.
Fixes #2660.
=> Add CLI args for snapshot intervals

notify/notify.go
This is less confusing to read if the receiver stages are constructed in the
same order as they are used in the pipeline below.
=> Sort receiver stage constructions by pipeline order

doc/alertmanager-mixin/.lint
Within https://github.com/grafana/dashboard-linter/commit/9a32e58ed01ee136ea674887f04a559a15eda3e6, the rules have been split into two different rules:
`target-job-rule`
`target-instance-rule`
All of our queries do contain the `job` label but as per the reason, we don't need both in this particular case.
Fixes #2899
=> Mixin: Rename exclusion rule from `panel-job-instance-rule` to `targert-instance-rule`

dispatch/route.go
Ranging over a nil slice is just a noop as well.
=> Remove unneeded nil check before ranging over slice

cmd/alertmanager/main.go
The function value and parameters of a defer statement are immediately
evaluated, so this "disp" value is always nil, and calling Stop() on a nil
dispatcher is a no-op, so this does nothing, but is confusing.
=> Remove unneeded stopping of nil Dispatcher

README.md
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
'go get' is no longer supported outside a module. To install, I replaced installation with 'go install'.
=> docs: fix installation for go1.18

.circleci/config.yml
`machine: true` is being removed by the end of May 2022.
=> .circleci/config.yml: use supported machine image

config/notifiers.go, config/notifiers_test.go, doc/alertmanager-mixin/.lint
The validation should fail if both `api_key` and `api_key_file` are
defined. I think there was a typo in the original PR (#2728) that
enforced `api_url` and `api_key_file` not being defined at the same
time.
cc @jkroepke since you did the initial implementation.
=> config: fix validation of OpsGenie configuration

docs/configuration.md
I noticed that some of the formatting on
https://prometheus.io/docs/alerting/latest/configuration/#time_interval-0 is
broken (including some words being formatted as italic due to underscores). This should fix that.
=> Fix Markdown formatting bugs / typos in the config docs

doc/alertmanager-mixin/.lint
With https://github.com/grafana/dashboard-linter/pull/49 `template-job-rule` no longer validates both `instance` and `job` labels. Add the new rule of `template-instance-rule` to the exclusions to preserve the previous behaviour.
This should fix the CI for the mixin.
=> Mixin: `template-job-rule` now only validates `job` and not `instance` and `job` labels

cmd/alertmanager/main.go, dispatch/dispatch_test.go, provider/mem/mem.go, provider/mem/mem_test.go, types/types.go, types/types_test.go
Fixes #1439 and #2619 (which are duplicates) 
The previous metric is not _technically_ reporting incorrect results as the alerts _are_ still around and will be re-used if that same alert (equal fingerprint) is received before it is GCed. Therefore, I have kept the old metric under a new name `alertmanager_marked_alerts` and repurposed the current metric to match what the user sees in the UI.
I have tested this (and you can too) with the following:
1. First, send a payload to the Alertmanager with different alerts to cover all the cases (make sure you edit the `endsAt` for `AlwaysFiringExpired`,  `AlwaysFiringExpiringSoon` and others as necessary) - you want one alert to be expired on reception and one that eventually expires to see how the metrics behave.
```bash
curl -X "POST" …
```
=> Alert metric reports different results to what the user sees via API

test/with_api_v2/acceptance/api_test.go, test/with_api_v2/acceptance/cluster_test.go, test/with_api_v2/acceptance/inhibit_test.go, test/with_api_v2/acceptance/send_test.go, test/with_api_v2/acceptance/silence_test.go, test/with_api_v2/mock.go
While merging #2944, I noticed the CI failed: https://app.circleci.com/pipelines/github/prometheus/alertmanager/2686/workflows/b6f87b0a-20c3-455b-b706-432c38a77511/jobs/12028.
It seemed like a deadlock between uncoordinated routines but I couldn't pin point (or reproduce, I tried with -race and -count) the exact problem. However, from the logs, I could point out where the problem originated and kind of have a hunch it had to do with the way net listeners are handled by the TODO removed.
The more worrying bit of the CI failure is that it took 10m to timeout, with this change we'll force close the connection with a 5s deadline so at the very least we'll get the feedback faster.
Along the way, I fixed a couple of instances of variables shadowing package names which should be pretty harmless. …
=> Force close mock servers as part of v2 acceptance tests

notify/notify_test.go, provider/mem/mem_test.go, silence/silence.go, types/types.go, types/types_test.go
This accurately reflects what the function _actually_ does. If no active silences IDs are provided and the list of inhibitions we have is already empty the alert is actually set to Active. Took me a while to realise this as I was understanding how do we populate the alert list.
While doing #2943 I was a bit puzzled as to where the active alerts are first introduced to `memMarker`, after carefully reading the interface I realised that a function named `SetSilenced` is actually used for that (!!). I'm not sure what our policy is and technically can be considered a breaking change so I'd like to hear opinions on whether this is worth it or not? At the very least the interface documentation is clear about it if we decided not to do this.
=> Marker: Rename `SetSilenced` to `SetActiveOrSilenced`

docs/configuration.md
Updated for this change: https://github.com/prometheus/common/pull/331
Bringing in line with Prometheus docs: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#oauth2
=> Update configuration doc to reflect tls_config in oauth2

go.mod, go.sum, silence/silence.go, silence/silence_test.go
github.com/benbjohnson/clock provides a time interface to programs
rather than using the stdlib time package. This allows mocking time in
programs and tests. In this commit, the clock is used to speed up and
simplify testing of the silences package.
Fixes #2850
=> Issue #2850: Add benbjohnson/clock to the silences package.

config/notifiers.go, notify/telegram/telegram.go, notify/telegram/telegram_test.go
The original PR was #2879 accidentally closed (by deleting its branch) after rebasing... :man_shrugging: 
Closes https://github.com/prometheus/alertmanager/issues/2876
=> notify/telegram: Set API URL and ParseMode defaults

docs/https.md
May refer to https://github.com/prometheus/exporter-toolkit/blob/14464f8d9bad4970fb2bbb16d64af22075aa4ec9/web/handler.go#L35
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
=> docs: correct the accepted value for X-XSS-Protection header

api/v2/api_test.go, api/v2/testing.go
As part of #2971, I'm about to extend the test for silences - extract the functions into helpers as part of a separate file and add names to the expectations so that we can easily identify them.
**functionality-wise everything remains unchanged** this is just to accommodate for the new tests as part of #2971
=> Refactor POST /api/v1/silences

api/v1/api_test.go, api/v2/api_test.go, cli/config/config.go, cli/config/config_test.go, cli/config/http_config.go, cli/template_render.go, cluster/tls_config.go, config/config.go, examples/webhook/echo.go, nflog/nflog_test.go, notify/email/email_test.go, notify/opsgenie/opsgenie.go, notify/opsgenie/opsgenie_test.go, notify/slack/slack.go, notify/slack/slack_test.go, notify/util.go, notify/util_test.go, notify/wechat/wechat.go, scripts/errcheck_excludes.txt, silence/silence_test.go, template/template.go, test/cli/acceptance.go, test/with_api_v1/acceptance.go, test/with_api_v2/acceptance.go
`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
=> Remove ioutil

.circleci/config.yml
Only build all binaries on main/release.
Signed-off-by: SuperQ <superq@gmail.com>
=> Speedup CI builds

api/v2/api.go
This is a of a nitpicky change, but having error logs on bad requests
is a bit of a pain. This means that a bad client can spam the logs with
bad requests that are really not actually an issue for the server -
we just send back the error and move on. This commit moves a couple of logs
from `Error` to `Debug` so that they can be filtered a bit better
Signed-off-by: sinkingpoint <colin@quirl.co.nz>
=> Move api error logs to debug

docs/https.md
Addresses [this issue](https://github.com/prometheus/prometheus/issues/10852) from the Prometheus repo for the alertmanager repo.
Signed-off-by: Alex Gavin <a_gavin@icloud.com>
=> docs: clarify supported tls cipher suites

docs/management_api.md, ui/web.go
Some frameworks issue HEAD requests to determine health.
This is meant to be the alertmanager equivalent of prometheus/prometheus#11160
Signed-off-by: Nicolas Dumazet <nicdumz.commits@gmail.com>
=> /-/{healthy,ready}/ respond to HEAD

notify/slack/slack.go, notify/slack/slack_test.go
Trailing newlines will almost always be present in a posixish file, so trim it away at first opportunity to prevent having invalid URLs we won't discover until a notification is sent.
=> Trim contents of slack api urls from files

notify/util.go, notify/util_test.go
Replace three dots characters `...` with ellipsis (U+2026) `…` characters to save 2 extra chars space.
Related issue: #3050
=> Truncate messages with fewer characters

docs/configuration.md, notify/notify_test.go, timeinterval/timeinterval.go, timeinterval/timeinterval_test.go
This PR addresses #2771 by adding a `time_zone` field to time interval definitions, which accepts an IANA time zone name (like 'Australia/Sydney') and if supplied means that the time intervals are defined inside that time zone.
On Windows machines the only time zones that are accepted are 'Local' and 'UTC', but I think that is probably enough for 99% of users who just want to use their local server time zone. I have noted this in the documentation, and also added some more info to the error message when a timezone fails to load on Windows mentioning that the user may need to supply their own time zone database.
I think it's also probably worth changing the default to be the server's local time rather than UTC as this would probably be unexpected for most users, but it is breaking behavior …
=> Add timezone support to time intervals.

notify/email/email_test.go
We don't need to test `getPassword()` separately as it can be covered with the tests already checking the various authentication methods.
Follow-up of #3038
=> notify/email: refactor tests

timeinterval/timeinterval.go
The introduction of https://github.com/prometheus/alertmanager/pull/2782 broke the linter due to a misformatted comment, this fixes it.
=> Appease the linter on `timeinterval.go`

pkg/labels/parse.go, pkg/labels/parse_test.go
=> Ensure matcher values are present when parsing matchers from strings

api/v2/api.go
Grafana Mimir vendors the Prometheus Alertmanager. Specifically, Grafana Mimir (which is a multi-tenant system) creates a Prometheus Alertmanager instance for each tenant. This means that, in a given process, there could be hundreds or thousands of Prometheus Alertmanager instances (one for each tenant).
While investigating some high memory utilization, I noticed that in some clusters the memory allocated by `loads.Analyzed()` (swagger spec) takes about 50% of memory.
In this PR I'm proposing to lazy load and then cache the swagger spec. To my understanding, the swagger spec is immutable, so shouldn't be an issue sharing it between different Aletmanager instances.
WDYT?
=> Reduce memory utilization in downstream projects creating multiple Alertmanager instances

config/notifiers.go, config/notifiers_test.go, docs/configuration.md, notify/pagerduty/pagerduty.go, notify/pagerduty/pagerduty_test.go
Allow PagerDuty `service_key` and `routing_key` to be read from files. Inspired by https://github.com/prometheus/alertmanager/pull/2623 by @sinkingpoint but updated, resolved conflicts and added documentation.
Related to issue #2498 
Signed-off-by: Oktarian Tilney-Bassett <oktariantilneybassett@improbable.io>
=> Add support for reading PagerDuty secrets from files

nflog/nflog.go, nflog/nflog_test.go, notify/notify.go, notify/notify_test.go
It seems useless to keep the notifications in the nflog for longer than
twice the repeat interval. This should help reduce memory usage of
clustered alertmanagers.
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
=> Expires notify log sooner when possible

config/config.go, config/config_test.go, config/notifiers.go, config/notifiers_test.go, config/testdata/conf.victorops-both-file-and-apikey.yml, config/testdata/conf.victorops-default-apikey-file.yml, docs/configuration.md, notify/victorops/victorops.go, notify/victorops/victorops_test.go
Related to issue #2498. Basically a copy of https://github.com/prometheus/alertmanager/pull/2728.
https://github.com/prometheus/alertmanager/pull/2554 can be closed as a result.
Signed-off-by: Oktarian Tilney-Bassett 😄
=> Add support for reading VictorOps API key from file

notify/opsgenie/opsgenie.go, notify/pagerduty/pagerduty.go, notify/pushover/pushover.go, notify/slack/slack.go, notify/telegram/telegram.go, notify/util.go, notify/util_test.go, notify/victorops/victorops.go
While most integrations set a limit by UTF-8 compatible characters (some like Webex) use runes - as pointed out in https://github.com/prometheus/alertmanager/pull/3132. This PR makes it explicit wether the truncation is happening at a byte or rune level.
=> Truncate: Be explicit on truncation of runes or bytes.

config/notifiers.go, config/notifiers_test.go
Solves #2887, where Opsgenie responder type can be templated according to [docs](https://prometheus.io/docs/alerting/latest/configuration/#responder), but configuration logic checked for specific list of values only.
=> Add check for templated Opsgenie receiver config

notify/opsgenie/opsgenie.go, notify/pagerduty/pagerduty.go, notify/pushover/pushover.go, notify/slack/slack.go, notify/telegram/telegram.go, notify/victorops/victorops.go
Some integrations define maximum lengths of messages that they accept. We usually respect these, by truncating the user's message for them.
Since we are actively modifying what the user asked us to send, let's log this event at warning level. That way, operators can more easily see when their message is too long, and know that we changed it for them.
Fixes https://github.com/prometheus/alertmanager/issues/3134
We no longer log the full-blown message per https://github.com/prometheus/alertmanager/issues/3134#issuecomment-1315343535.
=> Emit warning-level logs when truncating messages in notifications

.circleci/config.yml
It should fix the publish_main and publish_release jobs in CircleCI.
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
=> Bump Docker version for remote Docker

cluster/connection_pool.go, go.mod, go.sum
- Bump Go dependencies
- bump hashicorp/golang-lru to v2
- bump aws-sdk-go to v1.44.162
- bump prometheus/common to v0.39.0
- relases https://github.com/prometheus/alertmanager/pull/3157
Signed-off-by: junya koyama <arukiidou@yahoo.co.jp>
=> bump:hashicorp/golang-lru to v2,aws-sdk-go,prometheus/common

notify/telegram/telegram.go, notify/telegram/telegram_test.go
Closes #3061
I've tested it with a personal bot and it worked for me.
=> telegram: use HTML template with HTML parse mode

cmd/alertmanager/main.go
No need to spawn a goroutine, nor wait for a channel. Let's just put everything in a single select call.
=> Fixup: make signal handlers a bit simpler.

test/cli/acceptance.go, test/with_api_v1/acceptance.go, test/with_api_v2/acceptance.go, test/with_api_v2/acceptance/cluster_test.go
The CI environment isn't as performant as local machines: the time
needed to fully initialize the test environment can be significant and
skew the verification. Rather than setting the "virtual" clock used to
measure alert timings at the beginning of the acceptance test, it is
better to wait for the test bed to be ready.
I've run the `test` job several times and it looks like it's way less flaky than before.
cc @gotjosh
=> test: reduce flakiness of acceptance tests

docs/configuration.md
* The current page outline was an unstructured and unsorted mess, so I tried to organize the different configuration file fields into categories.
* I also sorted receivers alphabetically.
* Corrected the Telegram receiver's "bot_token" to be a "secret", not "string".
* Other minor improvements and wording additions to the sections.
Old vs. new TOC:
=> Multiple improvements to Alertmanager configuration docs

config/notifiers.go, docs/configuration.md, notify/webhook/webhook.go, notify/webhook/webhook_test.go
As discussed in https://github.com/prometheus/alertmanager/pull/3223
/cc @gotjosh @simonpasquier
=> mark webhook URL as a secret

template/template.go, template/template_test.go
This commit implements the `Stringer` interface for Pairs and KVs. It changes how Pairs are printed in templates from `map[name1:value1 name2:value2]` to `name1=value1, name2=value2`. KVs work similar, but are first sorted into pairs before being printed.
This should mean that Alertmanager has better text when using `{{ .Annotations }}` and `{{ .Labels }}`, as an example, without having to write a `range` with custom delimitation.
=> Implement Stringer interface for Pairs and KVs

cli/silence_query.go
In the Web UI, we have a UI to get information on a given silence through its ID. This functionality is missing from amtool however, leading to the necessity to pull _all_ the silenced, and filter with `grep` or similar.
This commit adds in a `--id` flag to the `silence query` command, which allows specifying an ID to match on, matching the functionality of the Web UI.
Signed-off-by: sinkingpoint <colin@quirl.co.nz>
=> Add `--id` flag to `amtool silence query`

cmd/alertmanager/main.go
In the main function, `WaitGroup` done twice, but add three times, so it will get stuck when exiting.
Currently, `AlertManager` cannot gracefully-exiting, because [wg.Wait()](https://github.com/prometheus/alertmanager/blob/6450c9ff18a4f7a6ebcefa83e157e80485014a4b/cmd/alertmanager/main.go#L333) for two done, but added three times
Signed-off-by:  chengjoey <zchengjoey@gmail.com>
=> fix gracefully-exiting stuck due to adding one more for `WaitGroup`

silence/silence_test.go
Today I learned that `runtime.Gosched()` doesn't do what I thought it would. While it allows other goroutines to run it doesn't guarantee that the main goroutine will be blocked until others are run.
Sadly, I had to fall back to the sleep approach.
I ran several instances of the follow with success at all times
```
~> go test -run "TestSilences_Maintenance_SupportsCustomCallback" -count 100
PASS
ok      github.com/prometheus/alertmanager/silence      0.654s
```
=> Fix silences flaky test

docs/notifications.md, template/template.go, template/template_test.go
What
----
Add [TrimSpace](https://pkg.go.dev/strings#TrimSpace) in the list of FuncMap to make it available while using templates.
Testing
----
Added a test along with this PR
```
➜  alertmanager git:(main) GO_ONLY=1 GOOPTS="-count=1 -run TestTemplateExpansion" make test | grep -i 'template'
go test -race -count=1 -run TestTemplateExpansion ./...
ok  	github.com/prometheus/alertmanager/template	4.355s
```
=> Make TrimSpace available for use in the template

docs/configuration.md
Added an extra note to the documentation for repeat_interval regarding its relation to data retention.
Some projects that build on top of AlertManager (Cortex comes to mind) haven't ported over the change in #1993 , and so users/tenants are surprised when they see alerts being resent more frequently than expected.
In addition to the logging, it would be better to document up front the affect of data retention on alert resend behaviour (as suggested in #2934).
Signed-off-by: Soon-Ping Phang <soonping@amazon.com>
=> Added note on data retention to documentation for repeat_interval

template/template.go, template/template_test.go
This commit fixes data corruption in templates that use the title function as it used a shared cases.Title when casers should not be shared between goroutines. When templates that used the title function were executed at the same time, data corruption would occur in the text that was being cased. This is fixed using a separate caser for each function call.
Here is an example of the issue as explained [here](https://github.com/prometheus/alertmanager/issues/3277#issuecomment-1453800831):
```
2023/03/03 16:40:51 Waltz, BaD
2023/03/03 16:40:51 Waltz, Bad Nymph, For Quick Jigs Vex
2023/03/03 16:40:51 Waltz, Bad Nymph, For Quick Jigs Vex
2023/03/03 16:40:51 Waltz, Bad Nymph, For Quick Jigs Vex
2023/03/03 16:40:51 Waltz, Bad Nymph, For Quick Jigs Vex
2023/03/03 16:40:51 Waltz, Bad Nymph, For …
```
=> Fix corruption in templates that use title function

nflog/nflog.go, nflog/nflog_test.go
Due to various reasons, we've observed different kind of errors on this area. From read-only disks to silly code bugs. Errors during maintenance are effectively a data loss and therefore we should encourage proper monitoring of this area.
Similar to https://github.com/prometheus/alertmanager/pull/3285
=> Metrics: Notification log maintenance success and failure

config/notifiers.go, config/notifiers_test.go, docs/configuration.md, notify/telegram/telegram.go, notify/telegram/telegram_test.go
Adds support for loading Telegram bot token from file.
This PR is mainly inspired by #3131. I've made a few changes considering the conversation in #3131, done minor refactoring, added some tests, and rebased changes to the current main.
=> Support loading Telegram bot token from file

notify/wechat/wechat.go
fix response json field name according to debug log:
`
ts=2023-04-17T07:49:52.559Z caller=wechat.go:178 level=debug integration=wechat response="{\"errcode\":60020,\"errmsg\":\"not allow to access from your ip, hint: [1681717792365202991262631], from ip: xxx.xxx.xxx.xxx, more info at https://open.work.weixin.qq.com/devtool/query?e=60020\"}" incident="{}:{alertname=\"不可用\"}"
`
and wechat api doc:
[https://developer.work.weixin.qq.com/document/path/90236](https://developer.work.weixin.qq.com/document/path/90236)
=> fix wechat notifier response field name

notify/slack/slack.go, notify/slack/slack_test.go
this uses the new error with reason to determine based on status code what the reason is for the slack integration
partial #3231
While I'm the committer of this message, I had no doing in the actual code and instead, the list of individuals below are to be contributed:
@alexmobo @zzehring @suntala @gloriasc @katebrenner @ktw4071
=> add reason code to slack notifier

notify/slack/slack.go, notify/slack/slack_test.go
This was introduced as part of #3252 and its a case I didn't really took into account.
=> Slack Notifier: Only return an error when it actually occurs

config/notifiers.go, docs/configuration.md, notify/pushover/pushover.go
Extending [Pushover](https://pushover.net/) integration to allow for `device` parameter to be used.
https://pushover.net/api#device
=> Add support for pushover devices

api/v2/api.go, api/v2/api_test.go, api/v2/client/silence/delete_silence_responses.go, api/v2/openapi.yaml, api/v2/restapi/embedded_spec.go, api/v2/restapi/operations/silence/delete_silence_responses.go
When a client attempts to delete a non-existent silence, respond with 404 instead of 500.
This PR is a rebase of an old an open [PR](https://github.com/prometheus/alertmanager/pull/2815) by @hateeyan and fixes the test failures.
=> api/v2: Delete silence respond with 404 when silence is not found

README.md, cluster/cluster.go, cluster/cluster_test.go, cmd/alertmanager/main.go
This PR makes it possible to set a label for the Memberlist cluster. This label is used to block any traffic that is not meant for the cluster.
For instance, in a situation where there are multiple alertmanager clusters, such as in K8s where IP addresses are shared and reused throughout the cluster, this label helps to prevent a wrong alertmanager cluster from receiving traffic meant for another cluster.
=> Cluster: Add memberlist label configuration option

pkg/labels/parse_test.go
As part of #3353, I'd like confidence in the current test suite to catch any regressions from introducing a new parser.
This adds two cases where we expect to parsing to fail.
=> Add more tests to TestMatchers

notify/webhook/webhook.go, notify/webhook/webhook_test.go
It's common to have empty lines at the end of a file therefore it would be good if the code handles it correctly, also it will align the webhook url_file behaviour with the slack api_url_file.
=> Trim space from webhook url_file content

pkg/labels/parse_test.go
I found a possible bug (unexpected behaviour?) in the current parser for label matchers where `\n` is interpolated and `\t` is not. I've chosen to document this with a test while I figure out if this is intentional or not.
Related: https://github.com/prometheus/alertmanager/pull/3353
=> Document difference between tab and newline in tests

cmd/alertmanager/main.go, docs/configuration.md
This commit updates Alertmanager to log a warning when repeat_interval is less than group_interval for an individual route.
When `repeat_interval` is less than `group_interval`, the earliest a notification can be sent again is the next time the aggregation group is flushed, and this happens at each `group_interval`.
Fixes #3370
=> Log a warning when repeat_interval is less than group_interval

.circleci/config.yml, .promu.yml
Go 1.19 will be EOL come August.
https://go.dev/doc/devel/release
Verified 1.20 tag available: https://quay.io/repository/prometheus/golang-builder?tab=tags
```
Build with Go 1.20
- Start using Go 1.20 toolchain to build
- Remove deprecated reference to updating .travis.yml
```
=> Build with Go 1.20

template/email.html
According to schema.org's faq both https and http are fine, but https is preferred going forward: https://schema.org/docs/faq.html#19
Why am I making this change? To make some security code scanner happy :)
=> Update email.html to use "https://schema.org" instead of "https://schema.org"

docs/configuration.md
This pull request fixes an incorrect example in the docs:
```
matchers: [ "foo = bar,baz", "dings != bums" ]
```
Is not valid and will throw the following error:
```
ts=2023-06-22T09:51:29.199Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=config.yml err="bad matcher format: baz"
```
The example should be:
```
matchers: [ "foo = \"bar,baz\"", "dings != bums" ]
```
Fixes #3400
=> Fix example matchers in docs

.circleci/config.yml, doc/alertmanager-mixin/Makefile
In mixtool, the tip of master broke for our mixin - I have managed to trace it down and opened a PR (see https://github.com/grafana/dashboard-linter/pull/143) but for now, let's pin the version to make sure our CI is not affected.
There's also the fact that I golang circleCI orb hasn't been updated in ages - updating it solved the CI problem we hand on tests_frontend where the goland version was failing to install. I think this might have been a result of #3411
=> CI: Pin the mixtool version in CircleCI and update the golang CircleCI orb

notify/notify.go
This pull request updates `notify.go` to log the GroupKey and fingerprints of an alert at the debug level, and just the GroupKey at the warning level should the notify attempt fail.
Here is an example of it at debug level:
```
ts=2023-08-03T09:28:36.829Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=foo[c5a7cb1][active]
ts=2023-08-03T09:28:38.725Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=bar[4656093][active]
ts=2023-08-03T09:28:51.830Z caller=dispatch.go:515 level=debug component=dispatcher aggrGroup="{}:{alertname=\"foo\"}" msg=flushing alerts=[foo[c5a7cb1][active]]
ts=2023-08-03T09:28:51.984Z caller=notify.go:757 level=debug component=dispatcher receiver=email integration=email[0] …
```
=> Log the GroupKey and alerts in retry

notify/slack/slack.go, notify/slack/slack_test.go
As described in the "More error types" section below, Slack API can return errors with a 200 response code:
https://slack.dev/node-slack-sdk/web-api#handle-errors
This change adds parsing of API response to extract error messages.
Signed-off-by: Anton Tolchanov <anton@tailscale.com>
=> Treat error response payloads from Slack as errors

CHANGELOG.md
It should be `<major>.<minor>.<patch>-rc.<candidate>` both the `VERSION` file and the `CHANGELOG` header must match.
=> Release: fix the version formatting

CHANGELOG.md
Signed-off-by: Leonardo Taccari <leot@NetBSD.org>
---
Minor PR that just fixes a thinko/pasto in the year (it should be 2023, not 2022).
=> Fix year in 0.26.0-rc.0 entry

.circleci/config.yml
The test job fails constantly on the release-0.25 branch. Skipping it to be able to publish v0.25.1.
=> .circleci/config.yml: disable test job requirement on publish

notify/notify.go
Implementing notify metrics for missing integrations, following https://github.com/prometheus/alertmanager/issues/3237
=> [FEAT] Add missing integrations to notify metrics

docs/configuration.md
This commit updates the docs on inheritance for group_wait, group_interval and repeat_interval.
=> Docs: Update docs on inheritance for time intervals

CHANGELOG.md
Some users have been vocal about the security fix not visible enough in the changelog, it seems like prometheus uses [SECURITY] to disclose these and I think it's a good practice.
A copy of #3487 but for the release branch of 0.26
=> Add a `[SECURITY]` to the changelog and update CVE-2023-40577

config/notifiers.go, docs/configuration.md, notify/pushover/pushover.go
Add support ttl in pushover, following issue https://github.com/prometheus/alertmanager/issues/3454
=> Add missing ttl in pushhover

config/notifiers.go, test/cli/acceptance.go, test/cli/acceptance/cli_test.go
This commit fixes issue #3505 where amtool would fail with `error: scheme required for webhook url` when using amtool with `--alertmanager.url`.
The issue here is that `UnmarshalYaml` for `WebhookConfig` checks if the scheme is present when `c.URL` is non-nil. However, `UnmarshalYam`l for `SecretURL` returns a non-nil, default value `url.URL{}` if the response from `api/v2/status` contains `<secret>` as the webhook URL.
=> Fix scheme required for webhook url in amtool

notify/notify.go
This is harmless as the vector won't be duplicated but let's remove it anyways.
=> Remove duplicate integration from metrics

.github/workflows/ci.yml, .github/workflows/golangci-lint.yml, .github/workflows/mixin.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .gitignore, Makefile
This is a first draft to move from CircleCI to Github Actions.
Generally I tried to trigger workflows only for relevant changes, e.g. the mixin-lint is only triggered if a file in the mixins change.
Two things are tbd:
1. This doesn't yet store the frontend asset tarball anywhere. I wasn't exactly sure how this is currently handled in the CircleCI setup, any pointer are appreciated.
2. ~This currently uses my fork of `maildev` at https://github.com/jan--f/maildev/tree/hide-starttls-when-user-password, which simply re-enables `STARTTLS`, which was disabled in [v1.1.1](https://github.com/maildev/maildev/pull/276/). There is a [PR](https://github.com/maildev/maildev/pull/435) up that looks promising in order for Alertmanager to switch back to upstream `maildev`. The current PR version …
=> Github actions

cli/utils.go
As discussed with @gotjosh [here](https://github.com/prometheus/alertmanager/pull/3483#discussion_r1334210090), we agreed to remove this function as it's un-used.
=> Remove unused function GetAlertmanagerURL

dispatch/route.go, dispatch/route_test.go
Adding a UUID to identify the route in general 
The route can be UUID by itself matchers+parents matchers + itself position 
```
route1(matcher="1")
route2(matcher="1")                   route3(matcher="1")           route4(matcher="1")
route5(matcher="1")      route6(matcher="1")            
```
For example to UUID route 6, it will be (matcher="1")/(matcher="1")/(matcher="1")/1
=> Add the route ID to uuid

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/release.yml
This add
- a job to build on 3 architectures in the CI action
- Fixes the publish action to cross build all architectures first
~TODO: add a release action and discuss and add appropriate trigger filters for release and publish.~
=> actions: cross build in ci and fix publish

docs/configuration.md
Although it is true that Repeat interval should be greater than or equal to the Group interval, it should also be a multiple of it too. If the Repeat interval is not a multiple, then because of how aggregation groups are flushed, it will be made into one implicitly. This commit documents this behavior.
=> Update configuration docs for Repeat interval

docs/configuration.md
now fits to https://github.com/prometheus/alertmanager/blob/v0.26.0/config/notifiers.go#L168-L175
similar to https://github.com/prometheus/alertmanager/pull/3495; introduced in https://github.com/prometheus/alertmanager/pull/3324
=> Fix Docs: default for msteams config

cmd/alertmanager/main.go, notify/notify.go, notify/notify_test.go, timeinterval/timeinterval.go, timeinterval/timeinterval_test.go, types/types.go
This should make implementing #3520 a bit cleaner given that we shouldn't need to introduce a direct dependency on marker in `notify`.
There's absolutely no change of functionality here and I've expanded coverage for similar logic in both places.
=> Refactor: Move `inTimeIntervals` from `notify` to `timeinterval`

go.mod, go.sum
cc: @simonpasquier 
Also wondering if we should consider a go bump here its on 1.18 currently
=> fix: Bump golang.org/x/net to v0.17.0

notify/notify.go
This commit updates Alertmanager to add a duration to the notify success message. It complements the existing histogram to offer fine-grained information about notification attempts. This can be useful when debuggin duplicate notifications, for example, when the duration exceeds peer_timeout.
```
ts=2023-10-16T19:22:49.666Z caller=notify.go:817 level=debug component=dispatcher receiver=test integration=webhook[0] aggrGroup={}:{} alerts=[[6ad8c19][active]] msg="Notify success" attempts=1 duration=3.064417ms
```
=> Add duration to the notify success message

Makefile, api/v2/client/alert/get_alerts_responses.go, api/v2/client/alert/post_alerts_responses.go, api/v2/client/alertgroup/get_alert_groups_responses.go, api/v2/client/general/get_status_responses.go, api/v2/client/receiver/get_receivers_responses.go, api/v2/client/silence/delete_silence_responses.go, api/v2/client/silence/get_silence_responses.go, api/v2/client/silence/get_silences_responses.go, api/v2/client/silence/post_silences_responses.go, api/v2/models/alert_group.go, api/v2/models/alert_groups.go, api/v2/models/alertmanager_status.go, api/v2/models/cluster_status.go, api/v2/models/gettable_alert.go, api/v2/models/gettable_alerts.go, api/v2/models/gettable_silence.go, api/v2/models/gettable_silences.go, api/v2/models/matchers.go, api/v2/models/postable_alert.go, api/v2/models/postable_alerts.go, api/v2/restapi/operations/alertmanager_api.go
Bumps the API spec/client generation util of `go-swagger` from 0.30.2 to 0.30.5 which is the latest stable.
=> Bump: go-swagger to latest stable

notify/notify.go
This commit adds debug logs to MuteStage that logs when an alert is muted. This can help operators root cause missing notifications when alerts are silenced by mistake or purpose but then forgotten about.
```
ts=2023-10-15T21:10:47.858Z caller=notify.go:537 level=debug component=dispatcher msg="Notifications will not be sent for muted alerts" alerts="[[26cdc50][active] [d7f5862][active]]"
```
=> Add debug logs for muted alerts

matchers/compat/parse_test.go, matchers/compliance/compliance_test.go, matchers/parse/lexer.go, matchers/parse/parse_test.go
This commit updates the matchers parser to reject unquoted openmetrics escape sequences. As an example, `foo=bar\n` will no longer parse, and must instead be written as `foo="bar\n"`. This avoids an issue where the input is valid in both the matchers and classic parsers, but results in two different parsings.
=> Support UTF-8 label matchers: Do not allow unquoted escape sequences

matchers/compat/parse.go
This commit removes the open and close braces from the suggestion as braces do not make sense in the configuration file. This does not change the behavior of the suggestion whatsoever as these are optional.
=> Support UTF-8 label matchers: Remove braces from suggestion

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/golangci-lint.yml, .github/workflows/mixin.yml, .promu.yml, go.mod, go.sum
I would like to propose we update the minimum Go version to 1.21. Go [1.20](https://tip.golang.org/doc/go1.20) and [1.21](https://tip.golang.org/doc/go1.21) have a number of useful additions to the built-in packages. For example, I would like to use `strings.ContainsFunc` [here](https://github.com/prometheus/alertmanager/pull/3580).
If we don't want to remove Go 1.18 and Go 1.19 support for the time being then that's fine too! I just thought I would see if this is an option before inlining the function to make it work on Go versions 1.19 and older.
=> Update go.mod to require Go 1.21

matchers/parse/parse_test.go, matchers/parse/token.go
Quoted tokens can contain both UTF-8 byte and code point literals that should be interpreted when quoted. However, we need to check that the interpreted literals are valid UTF-8 code points or not. This now happens in unquote.
=> Support UTF-8 label matchers: unquote should check for invalid UTF-8 code points

doc/alertmanager-mixin/alerts.libsonnet
Since [Alertmanager 0.26.0 version](https://github.com/prometheus/alertmanager/blob/ce6efba023b0397cb522d64e910684e48d12455f/CHANGELOG.md#0260--2023-08-23), a new label `reason` was added in the `alertmanager_notifications_failed_total` metric to indicate the type of error of the alert delivery. 
As a result, the original alert rules are broken because labels are mismatched between `alertmanager_notifications_failed_total` and `alertmanager_notifications_total metrics`.
Prometheus requires samples with exactly the same labels to get matched together when performing calculations. [docs](https://prometheus.io/docs/prometheus/latest/querying/operators/#one-to-one-vector-matches)
Use the `on` vector matching keyword to match only the `integration` label to allow for matching between series …
=> fix: label mismatch for alertmanager_notifications_failed_total

pkg/labels/matcher.go, pkg/labels/matcher_test.go
This commit updates the String method to print non-Prometheus compliant label names in a format that can be parsed in the UTF-8 parser. Such inputs are never valid in the classic parser. If the label name is Prometheus compliant, it is still printed unquoted.
=> Support UTF-8 label matchers: Update Stringer for non-Prometheus compliant label names

notify/discord/discord.go
Discord is limiting the length of the message (title, description). In this PR, I propose truncating the strings like AM does for pushover or opsgenie.
Doc: https://discord.com/developers/docs/resources/channel#embed-object-embed-limits
Closes: #3310
=> Reflect Discord's max length message limits

api/v2/api.go, api/v2/client/silence/get_silences_responses.go, api/v2/openapi.yaml, api/v2/restapi/embedded_spec.go, api/v2/restapi/operations/silence/get_silences_responses.go
There's no change to the logic here - it just struck me as odd that we were reusing the response from alerting groups in the silences call when it's pretty simple to add a new one in the API description.
This is more accurate as well, as this will be used to power the documentation.
=> API: Allow the Silences API to use their own 400 response

config/config.go, matchers/compat/parse.go, matchers/compat/parse_test.go, test/with_api_v2/acceptance/utf8_test.go
This commit fixes missing UTF-8 support in the group_by for routes.
=> Fix UTF-8 not supported in group_by

README.md
#1023 (0.22+?) introduced a new, now preferred matchers syntax for routes and inhibitions. The README still uses the old, deprecated syntax. This PR updates those examples (and fixes a very minor example config comment typo).
:heavy_check_mark: I've checked that the new config still parses with alertmanager v0.26.
:heavy_check_mark: The quoting is consistent with the style used in the already updated inhibitions example.
=> README: Use new matchers syntax in config examples

.github/workflows/golangci-lint.yml, .golangci.yml, cluster/cluster_test.go, cluster/tls_connection_test.go, cluster/tls_transport_test.go, dispatch/dispatch_test.go, dispatch/route_test.go, matchers/compat/parse_test.go, matchers/parse/parse_test.go, nflog/nflog_test.go, notify/email/email_test.go, notify/msteams/msteams_test.go, notify/notify_test.go, notify/opsgenie/opsgenie_test.go, notify/slack/slack_test.go, notify/sns/sns_test.go, notify/webhook/webhook_test.go, silence/silence_test.go, store/store_test.go, template/template_test.go, test/with_api_v2/acceptance/api_test.go, test/with_api_v2/acceptance/utf8_test.go
This help ensure that the the testify best practices are followed.
It requires an upgrade of golangci-lint.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> golangci-lint: enable testifylint linter

matchers/compat/parse.go, matchers/compat/parse_test.go
This commit makes functions in the compat package public. These functions are useful for software that builds on top of the Alertmanager that also need to migrate from classic mode to UTF-8.
=> Support UTF-8 label matchers: Make functions in compat package public

api/v2/api.go, cli/alert_add.go, cli/alert_query.go, cli/root.go, cli/silence_add.go, cli/silence_query.go, cli/test_routing.go, cmd/alertmanager/main.go, config/config.go, matchers/compat/metrics.go, matchers/compat/parse.go, matchers/compat/parse_test.go
This commit adds the following metrics to the compat package:
- `alertmanager_matchers_parse`
- `alertmanager_matchers_disagree`
- `alertmanager_matchers_incompatible`
- `alertmanager_matchers_invalid`
With a label called origin to differentiate the different sources of inputs: the configuration file, the API, and amtool.
The disagree_total metric is incremented when an input is invalid in both parsers, but results in different parsed representations, then there is disagreement. This should not happen, and suggests their is either a bug in one of the parsers or a mistake in the backwards compatible guarantees of the matchers/parse parser.
The incompatible_total metric is incremented when an input is valid in pkg/labels, but not the UTF-8 parser in matchers/parse. In such case, the matcher …
=> Support UTF-8 label matchers: Add metrics to matchers compat package

api/api.go, api/v2/api.go, cmd/alertmanager/main.go, silence/silence.go, silence/silence_test.go, types/types.go, types/types_test.go
This commit fixes inconsistent UTF-8 behavior if the compat package is not initialized and feature flags are not passed to the API. This can happen when Alertmanager is used as a package in software such as Cortex or Mimir.
The inconsistent behavior is that Alertmanager will accept UTF-8 alerts but reject UTF-8 configurations.
Since feature flags are optional via api.Options, we cannot force them to be passed to api.New at compile time. Instead, it's better to defer back to the compat package which is consistent even when not initialized.
=> Fix inconsistent defaults in UTF-8 behavior

matchers/compat/parse.go, matchers/compat/parse_test.go
This pull request fixes a missing check when validating UTF-8 label names that is present in `prometheus/common`.
=> Fix missing check for len(name) == 0

cmd/alertmanager/main.go, silence/silence.go
This commit removes some code that should have been removed in #3668. The FeatureFlags in silence.Options are no longer used but were still initialized. These had a no-op effect.
=> Remove unused feature flags

notify/email/email.go
This should ignore any newlines in the smtp password file (actually, the file contents are trimmed).
fixed #3549 
**BEWARE** I did not test or even build the project after this single-line change (sorry: I don't know how to do it and honestly can't be bothered to learn how to for a drive-by contribution)
=> Newlines in smtp password file are now ignored

cmd/alertmanager/main.go
This commit adds a new metric called `alertmanager_inhibit_rules`. It is identical to the `alertmanager_integrations` and `alertmanager_receivers` metrics that are present in the current and previous versions.
Some examples of this at `/metrics`:
```
alertmanager_inhibit_rules 0
```
```
alertmanager_inhibit_rules 1
```
```
alertmanager_inhibit_rules 2
```
=> Add metric for inhibit rules

matchers/compat/parse.go
This commit fixes a small bug in the warning logs for incompatible matchers where the error from the UTF-8 parser was logged as nil.
=> Fix nil error in warn logs about incompatible matchers

matchers/compat/metrics.go, matchers/compat/parse_test.go
This commit changes the metrics in the compat package from gauges to counters. The reason for this is that in some cases the gauge should behave like a gauge (i.e. loading configurations) but in other cases should behave like a counter (i.e. HTTP requests).
Second, because the compat package is a global package (due to how config.Load works), in tenanted systems like Cortex and Mimir it was non-trivial to reset the gauges per tenant each time their configuration was reloaded.
Instead, it's easier to compute the rate of increase as 0 instead of check that the gauge is 0 to know if UTF-8 strict mode can be enabled.
=> Change compat metrics to counters

cli/root.go
There is no need to register these metrics in amtool, so use `compat.NewMetrics(nil)` instead of `compat.RegisteredMetrics`.
=> Do not register compat metrics in amtool

config/notifiers.go, docs/configuration.md, notify/discord/discord.go, notify/discord/discord_test.go, notify/msteams/msteams.go, notify/msteams/msteams_test.go
=> feat: implement webhook_url_file for discord and msteams

notify/notify.go, notify/notify_test.go
Addresses: #3512
This adds a new counter metric `alertmanager_alerts_supressed_total` that is incremented by `len(alerts)` when an alert is suppressed for being outside of a time_interval, ie inside of a mute_time_intervals or outside of an active_time_intervals.
=> feat: add counter to track alerts dropped outside of time_intervals

matchers/compat/parse.go
This commit fixes a small number of inconsistencies in the compat package logging. It now has consistent use of classic matchers parser and UTF-8 matchers parser, instead of old matchers parser and new matchers parser.
=> Fix a small number of inconsistencies in compat package logging

featurecontrol/featurecontrol.go
This commit fixes a log line in the featurecontrol package which should be "UTF-8 strict mode" and not "UTF-8 mode".
=> Fix log line in featurecontrol

test/with_api_v2/acceptance.go
This commit attempts to address a panic that occurs in acceptance tests if a server in the cluster fails to start:
```
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xa0 pc=0x101785858]
goroutine 27 [running]:
testing.tRunner.func1.2({0x101cc73e0, 0x1023c09c0})
/usr/local/go/src/testing/testing.go:1545 +0x1c8
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1548 +0x360
panic({0x101cc73e0?, 0x1023c09c0?})
/usr/local/go/src/runtime/panic.go:914 +0x218
github.com/prometheus/alertmanager/test/with_api_v2.(*Alertmanager).Terminate(0x14000a50300) …
```
=> Fix panic in acceptance tests

docs/configuration.md
This pull request updates the docs to:
1. Explain that there is a new parser for label matchers, the transition period, and how Alertmanager reverts to the classic parser.
2. How to use the feature flags to switch between fallback, UTF-8, and classic parse modes.
3. The difference between UTF-8 matchers and classic matchers.
4. Improved the documentation on composing matchers to make more complex expressions.
=> Support UTF-8 label matchers: Update the docs on how to use UTF-8 in label matchers and parse mode feature flags

cluster/cluster_test.go
wait until `p2.Status()` returns because it blocks until we're ready - that way, we're guaranteed to know that the cluster size is 2.
This keeps failing consistently now https://github.com/prometheus/alertmanager/actions/runs/7900029184/job/21561068687?pr=3721
=> Fix flaky test TestClusterJoinAndReconnect/TestTLSConnection

config/config.go
This PR fixes the discord & msteams webhook_url_file config option introduced in #3555
There was a missing check for the WebhookURLFile causing this error:
msg="Loading configuration file failed" file=alertmanager.yml err="no discord webhook URL provided"
=> fix: discord & msteams webhook_url_file configuration

cli/template_render.go
Currently, the default example alerts of the `amtool template render` command contain an invalid status, leading to `.Alerts.Firing` and `.Alerts.Resolved` returning empty arrays.
This PR changes one of the two examples to `firing` the other to `resolved`.
=> `amtool template render` improve default data

docs/configuration.md
This pull request fixes code blocks in the docs that were blockquoted by mistake.
=> Fix code blocks in the docs being blockquoted instead

provider/mem/mem.go, provider/mem/mem_test.go, store/store.go
This PR is a fix for #3682. In some instances, `mem.Alerts.Subscribe()` and `store.gc()` can get deadlocked
1. Lock acquisition in `store.Alerts.gc()`:
- The method `store.Alerts.gc()` acquires a lock on its internal mutex `store.Alerts.mtx`
- While holding the lock, it then calls the callback function which will try to acquire a lock on `mem.Alerts.mtx`
2. Concurrent Execution:
-  `mem.Alerts.Subscribe()` acquires a lock on its internal mutex `mem.Alerts.mtx` and calls `store.Alerts.List()`
3. Deadlock situation:
- Callback function tries to acquire a lock on `mem.Alerts.mtx`. However this lock is already being held by `mem.Subscribe()`
- Similarly `mem.Subscribe()` cannot proceed because `store.List()` cannot acquire lock (`store.Alerts.mtx`) because it is being held by `store.gc()` …
=> Fix for deadlock issue #3682

provider/mem/mem.go, store/store.go, store/store_test.go
This PR addresses this [comment](https://github.com/prometheus/alertmanager/pull/3715#discussion_r1507309879) 
I did not want to change `type AlertStoreCallback interface` as this might be a breaking change
=> Send a slice of values to callback function instead of references

silence/silence_bench_test.go, silence/silence_test.go
This commit updates the existing benchmarks for silences to also benchmark Mutes. This complements the existing Query benchmarks by also measuring the time taken to mark silenced alerts.
=> Silences: Add benchmarks for Mutes

inhibit/inhibit_bench_test.go
This commit adds benchmarks for Mutes in the inhibit package. Here is an example of the benchmarks being run:
```
go test ./... -bench=.
goos: darwin
goarch: arm64
pkg: github.com/prometheus/alertmanager/inhibit
BenchmarkMutes/1_inhibition_rule,_1_inhibiting_alert-8         	 1498118	       778.2 ns/op
BenchmarkMutes/10_inhibition_rules,_1_inhibiting_alert-8       	 1528195	       784.1 ns/op
BenchmarkMutes/100_inhibition_rules,_1_inhibiting_alert-8      	 1364626	       797.3 ns/op
BenchmarkMutes/1000_inhibition_rules,_1_inhibiting_alert-8     	 1331232	       848.7 ns/op
BenchmarkMutes/10000_inhibition_rules,_1_inhibiting_alert-8    	 1314247	       841.0 ns/op
BenchmarkMutes/1_inhibition_rule,_10_inhibiting_alerts-8       	 1379548	       870.3 ns/op …
```
=> Inhibition Rules: Add benchmarks for Mutes

inhibit/inhibit_bench_test.go
This commit adds more benchmarks for inhibition rules where just the last rule in the benchmark inhibits the labels. Here is an example of these benchmarks:
```
BenchmarkMutes/10_inhibition_rules,_last_rule_matches-8        	 1094041	      1020 ns/op
BenchmarkMutes/100_inhibition_rules,_last_rule_matches-8       	  347079	      3306 ns/op
BenchmarkMutes/1000_inhibition_rules,_last_rule_matches-8      	   39068	     26769 ns/op
BenchmarkMutes/10000_inhibition_rules,_last_rule_matches-8     	    4387	    260687 ns/op
```
=> Add more benchmarks for inhibition rules

notify/notify_test.go
This commit rewrites the existing TestTimeActiveStage unit tests to have complete isolation between test cases. Before this change, each test case affected the state of its subsequent tests.
The motivation behind this change is to make it easier to assert that alerts have been marked as muted.
=> #3513: Rewrite TestTimeActiveStage tests

notify/notify_test.go
This commit rewrites the existing TestTimeMuteStage unit tests to have complete isolation between test cases. Before this change, each test case affected the state of its subsequent tests.
The motiviation behind this change is to make it easier to assert that alerts have been marked as muted.
=> #3513: Rewrite TestTimeMuteStage tests

dispatch/route.go, dispatch/route_test.go
This pull request fixes a bug (#3802) where Route.ID() returns conflicting IDs.
For example, the configuration:
receiver: test
routes:
- matchers:
- foo=bar
continue: true
routes:
- matchers:
- bar=baz
- matchers:
- foo=bar
continue: true
routes:
- matchers:
- bar=baz
Gives the following Route IDs:
{}
{}/{foo="bar"}/0
{}/{foo="bar"}/{bar="baz"}/0
{}/{foo="bar"}/1
{}/{foo="bar"}/{bar="baz"}/0
When it should give these Route IDs:
{}
{}/{foo="bar"}/0
{}/{foo="bar"}/0/{bar="baz"}/0
{}/{foo="bar"}/1
{}/{foo="bar"}/1/{bar="baz"}/0
=> Fix `Route.ID()` returns conflicting IDs

docs/notifications.md, template/template.go, template/template_test.go
This commit adds the date and tz functions to templates. This means users can now format time in a specified format and also change the timezone to their specific locale.
An example of how these functions work, and can be composed together, can be seen here:
{{ .StartsAt | tz "Europe/Paris" | date "15:04:05 MST" }}
=> Add date and tz functions to templates

api/api.go, api/metrics/metrics.go, api/v1_deprecation_router.go
=> Fix version in APIv1 deprecation notice

go.mod, go.sum
Addresses:'
```
Scanning your code and 410 packages across 83 dependent modules for known vulnerabilities...
=== Symbol Results ===
Vulnerability #1: GO-2024-2687
HTTP/2 CONTINUATION flood in net/http
More info: https://pkg.go.dev/vuln/GO-2024-2687
Module: golang.org/x/net
Found in: golang.org/x/net@v0.20.0
Fixed in: golang.org/x/net@v0.23.0
Example traces found:
#1: cli/root.go:122:52: cli.NewAlertmanagerClient calls config.NewClientFromConfig, which eventually calls http2.ConfigureTransports
#2: types/types.go:290:28: types.MultiError.Error calls http2.ConnectionError.Error
#3: notify/notify.go:998:21: notify.TimeActiveStage.Exec calls log.jsonLogger.Log, which eventually calls http2.ErrCode.String
#4: notify/notify.go:998:21: notify.TimeActiveStage.Exec calls log.jsonLogger.Log, which …
```
=> dep: Manually upgrade golang.org/x/net (#3674)

ui/app/Makefile
The elm npm package doesn't support linux/arm64. The easiest option is to force docker to run this as a AMD64 container.
Upstream issue:
https://github.com/elm/compiler/issues/2283
=> ui: Force using linux/amd64 when using docker

notify/notify.go, timeinterval/timeinterval.go, timeinterval/timeinterval_test.go, types/types.go
This commit updates the TimeMuter interface to also return the names of the time intervals that muted the alerts.
=> #3513: TimeMuter returns the names of time intervals

dispatch/dispatch.go, inhibit/inhibit.go, provider/mem/mem.go, silence/silence.go, types/types.go, types/types_test.go
This commit adds a new GroupMarker interface that marks the status of groups. For example, whether a group is muted because or one or more active or mute time intervals. It renames the existing Marker interface to AlertMarker to avoid confusion.
It is based on https://github.com/prometheus/alertmanager/pull/3791.
=> #3513: Add GroupMarker interface

dispatch/dispatch.go, dispatch/dispatch_test.go, store/store.go, store/store_test.go
This commit fixes a race condition in dispatch.go that would cause a firing alert to be deleted from the aggregation group when instead it should have been flushed.
The root cause is a race condition that can occur when dispatch.go deletes resolved alerts from the aggregation group following a successful notification. If a firing alert with the same fingerprint is added back to the aggregation group at the same time then the firing alert can be deleted.
The issue was first reported in #3006.
1. `git checkout v0.27.0`
2. Add the following sleep to `dispatch.go`. This makes it easier to observe the race condition because the scheduler can resume the test between `ag.alerts.Get(fp)` and `ag.alerts.Delete(fp)`, during which it should replace the resolved alert with a firing alert.
```go
diff …
```
=> Fix race condition in dispatch.go

cmd/alertmanager/main.go, dispatch/dispatch.go, dispatch/dispatch_test.go, notify/notify.go, notify/notify_test.go, types/types.go, types/types_test.go
This pull request updates TimeMuteStage and TimeActiveStage to mark groups as muted when its alerts are muted by an active or mute time interval, and remove any existing markers when outside all active and mute time intervals.
It is based on https://github.com/prometheus/alertmanager/pull/3792, https://github.com/prometheus/alertmanager/pull/3794 and https://github.com/prometheus/alertmanager/pull/3795.
=> #3513: Mark muted alerts

provider/mem/mem.go, provider/mem/mem_test.go, store/store.go
The main branch will easily fail the newly added test case:
```
=== RUN   TestAlertsConcurrently
mem_test.go:565:
Error Trace:    /prometheus-io/alertmanager/provider/mem/mem_test.go:565
Error:          Not equal:
expected: 0
actual  : -171
Test:           TestAlertsConcurrently
```
There are multiple race conditions in the provider/mem:
1. Any Put or GC operation that occurs concurrently with this code block will introduce a race condition https://github.com/prometheus/alertmanager/blob/c920b605b647f2548e23a3dc2fea014b9c9dbf43/provider/mem/mem.go#L204-L228
2. A race condition between Put() and Subscribe() can cause some newly added Alerts to be missed.
@simonpasquier @w0rm @gotjosh please take a look
=> Fix race conditions in the memory alerts store

cmd/alertmanager/main.go, docs/configuration.md, silence/silence.go, silence/silence_test.go
This commit adds limits for silences including the maximum number of active and pending silences, and the maximum size per silence (in bytes).
=> Add limits for silences

cmd/alertmanager/main.go, docs/configuration.md, silence/silence.go, silence/silence_test.go
The limits we added in #3852 should include expired silences.
=> Limits should include expired silences

silence/silence_test.go
This commit fixes silence tests that relied on the maintenance function running at a fixed 100ms interval. If the go runtime that runs the maintenance is not scheduled with 150ms then the test will fail.
=> Fix TestSilenceLimits tests

notify/sns/sns.go, notify/sns/sns_test.go
Update sns notifier to return the error that `TmplText` returns instead of completely ignoringg it
Fixes #3528
=> Return error when TmplText errors in sns notifier

notify/sns/sns.go, notify/sns/sns_test.go
Reverts prometheus/alertmanager#3531
=> Revert "Return error when TmplText errors in sns notifier"

cmd/alertmanager/main.go, silence/silence.go, silence/silence_test.go
This commit changes silence limits from a struct of ints to a struct of functions that return individual limits. This allows limits to be lazy-loaded and updated without having to call `silences.New()`.
=> Silence limits as functions

cmd/alertmanager/main.go, silence/silence.go, silence/silence_test.go
This commit renames an existing (unreleased) limit from `max-per-silence-bytes` to `max-silence-size-bytes`.
Based on #3885.
=> Rename silence limit to max-silence-size-bytes

api/v2/api.go, api/v2/api_test.go, notify/notify_test.go, silence/silence.go, silence/silence_bench_test.go, silence/silence_test.go
This commit removes the Id from the method `silences.Set(*pb.Silence)` as it is redundant. The Id is still set even when creating a silence fails. This will be fixed in a later change.
=> Remove Id return from silences.Set(*pb.Silence)

config/config.go, config/config_test.go
Fixes https://github.com/prometheus/alertmanager/issues/3884
Updated the config.go to redact the URL.
Added test cases to check URL stays hidden.
=> Fix: Hide config.SecretURL when the URL is incorrect.

silence/silence.go, silence/silence_test.go
This commit fixes a bug where the MaxSilences limit can cause an incomplete update of existing silences, where the old silence can be expired but the new silence cannot be created because it would exceeded the maximum number of silences.
=> Fix MaxSilences limit causes incomplete updates of existing silences

api/v2/api_test.go, api/v2/testing.go
This commit adds a unit test for the `postSilencesHandler` to create and then update a silence. It shows that changing the ID of an existing silence returns 404 Not Found, and removing the ID of an existing silence re-creates that silence with a different ID.
=> Add tests for create and then update silences

silence/silence.go, silence/silence_test.go, test/with_api_v2/acceptance/utf8_test.go
This commit fixes a bug where an invalid silence causes incomplete updates of existing silences. What happens here is in some cases where the new silence is invalid, it can expire the old silence without creating the new silence. What should happen instead is the entire operation is aborted, and the original silence is left in place. This has been fixed by moving validation out of the `setSilence` method and putting it at the start of the `Set` method instead.
=> Fix invalid silence causes incomplete updates

silence/silence.go, silence/silence_test.go
This commit fixes a bug where the `MaxSilenceSizeBytes` limit can cause an incomplete update of existing silences, where the old silence can be expired but the new silence cannot be created because it would exceed the maximum size limit.
I moved `sil.UpdatedAt = now` out of `setSilence` and into `Set` and `Expire` because we want to make sure the `UpdatedAt` timestamp is calculated in the size when we call `checkSizeLimits`. Forget to set `sil.UpdatedAt` in either of these places and the following tests fail:
```
--- FAIL: TestSilenceSet (0.00s)
--- FAIL: TestSilenceLimits (0.00s)
--- FAIL: TestSetActiveSilence (0.00s)
--- FAIL: TestSilenceExpire (0.00s)
--- FAIL: TestSilenceExpireWithZeroRetention (0.00s)
--- FAIL: TestSilenceExpireInvalid (0.00s)
```
=> Fix MaxSilenceSizeBytes limit causes incomplete updates of existing silences

.github/workflows/golangci-lint.yml
update golangci-lint-action version to `v6.1.0`
=> chore: update golangci-lint-action version

go.mod, go.sum, silence/silence.go, silence/silence_bench_test.go, silence/silence_test.go
This commit replaces the archived and no longer maintained benbjohnson/clock package with coder/quartz. It is one of two pull requests. This pull request updates the `silence` package.
=> Replace benbjohnson/clock with coder/quartz

go.mod, go.sum, notify/email/email.go, notify/email/email_test.go
Closes https://github.com/prometheus/alertmanager/issues/4005
=> fix: close SMTP submission correctly to handle errors

docs/configuration.md
It was referring to itself, maybe because of the deprecated homonym global:mute_time_intervals ?
=> docs: clarify route:mute_time_intervals

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/mixin.yml, .promu.yml, go.mod
* Update Go build to 1.23.
* Update minimum Go version to 1.22.
=> Update Go to 1.23

go.mod, go.sum, nflog/nflog.go, nflog/nflog_test.go
This commit finishes replacing benbjohnson/clock with coder/quartz and removes it from `go.mod`.  It is stacked on top of #4001.
=> Finish replacing benbjohnson/clock with coder/quartz

notify/telegram/telegram.go
Before commit [1], the message parse mode value is the same as bot parse mode. Therefore, we don't need to pass ParseMode whenever sending message. But after that commit, if we don't pass SendOpts's ParseMode, the library will use the default mode which is empty string "", and HTML tags aren't parsed.
[1] https://github.com/tucnak/telebot/commit/864bef4e4d3a60b8079db4fdb51cac2e779349cd
Close-Issue: https://github.com/prometheus/alertmanager/issues/4026
=> fix(telegram): passing ParseMode when sending message

silence/silence.go, silence/silence_test.go
This is a small change which adds a second return value to `state.merge` to differentiate between cases where a silence is updated in place and where a silence is added. This is used by callers to decide if the `Silences.version` ought to be incremented. It fixes a bug where the `Silences.Version()` returns a incremented value for operations which don't need to increment the value. In our environment this change results in a significant performance improvement for production workloads because many fewer `QMatches` queries are issued by `Silencer.Mutes`.
I believe this is a just a bug for three reasons:
1. `Silences` reads "Increments whenever silences are added" (and other operations that mutate the silence state, such as the GC, do not increment the version) …
=> bugfix: only increment Silences version if a silence is added

notify/discord/discord.go, notify/discord/discord_test.go
Just to ensure this works correclty as expected, I originally thought there was a bug with the shadowing of the `content` varible but there isn't - to avoid further confusion I have followed up on this document left by George: https://github.com/prometheus/alertmanager/pull/3555#discussion_r1398448423
=> Add a test for `Notify` of the Discord integration

config/notifiers.go, docs/configuration.md, notify/discord/discord.go, notify/discord/discord_test.go
Allow for custom username and avatar URLs to be set in discord notifications.
Add `username` and `avatar_url` to discord configuration, default empty string.
Re-introduce the rest of what was proposed in #3821 now that #4007 is merged
=> Discord notifier: Add username and avatar_url

config/notifiers.go, docs/configuration.md, notify/webhook/webhook.go, test/with_api_v2/acceptance/send_test.go
We have witnessed cases where POST requests hang, because the receiver has become temporarily unresponsive, leading to failed notification attempts. If the request times out before the dispatcher timeout, because of some aspect of how the HTTP client is configured, then the request is retried, but this does not happen reliably.
To cover all eventualities, it makes sense to have a shorter per-request timeout. I think this timeout needs to be opt-in from the user perspective, as it requires prior knowledge of how fast the webhook should respond, and that it could lead to duplicate notifications.
=> Add timeout option for webhook notifier.

matcher/parse/lexer_test.go, matcher/parse/parse_test.go
This pull request adds additional tests for the questions asked in https://groups.google.com/g/prometheus-users/c/Ra0oiVpVur8.
=> Add tests for regex character classes

matcher/compat/parse.go
=> Improve the warning message to include escaping

notify/jira/jira.go, notify/jira/jira_test.go
Update Jira notifications to support templating in `project` and `issue_type`.
I'd like to be able to open issues in multiple Jira projects with different priorities and issue types depending on the alert labels or annotations.
Some Jira fields, like `summary` and `priority`, already allow templating, but it's missing in these two.
=> Enable templating for Jira project and issue_type

notify/msteamsv2/msteamsv2.go
As reported in comments of https://github.com/prometheus/alertmanager/issues/4088, a separate PR for the full width support of adaptive card is raised. @grobinson-grafana please have a review. Thanks
FYI: I have compiled alertmanager and tested the changes.
=> Add full width to adaptive card for msteamsv2

config/config.go, config/config_test.go, config/testdata/conf.inhibit-equal-utf8.yml, config/testdata/conf.inhibit-equal.yml
This commit fixes a bug where UTF-8 characters are not allowed in the `Equal` field for inhibition rules, even when UTF-8 strict mode is enabled.
This bug occurred because we forgot to override the validation in `model.LabelName`. I have copied the same logic used for `GroupBy` with `GroupByStr`, adding `EqualStr`.
We would like to upgrade prometheus/common in future and use the validation there instead, but it presents challenges with downstream projects like Mimir and Cortex where, at present, UTF-8 can be enabled and disabled in separate components at the same time, which is not supported in prometheus/common.
=> Fix UTF-8 not allowed in Equal field for inhibition rules

config/config.go, config/config_test.go
I have a deployment where a sidecar between the config-reloader and alertmanager loads and unmarshals a base configuration, extends it with more routes and receivers, and then marshals it back for the alertmanager. 
However, the default Marshal implementations in the receivers hide all Secret and SecretURLs when marshaling the config back to a YAML. We have to duplicate all the receiver structs in our code to be able to switch them to plain strings and URLs.
I'd be helpful to be able to re-use the structs already here in the alertmanager. 
This is already supported by some of the Prometheus common configs by using a global `MarshalSecretValue` [here](https://github.com/prometheus/common/blob/aeb616a795915a559fe308885ab6de6101180ed6/config/config.go#L33).
For now, I'm adding support for a …
=> Update config to allow showing secret values when marshaled

config/coordinator.go
This hash is presented to operators to track the contents of the Alertmanager config file.
The method used to calculate the hash takes only the lower 48 bits of an MD5 hash, in order to stuff the hash into the metric value.
Although this is probably obvious to many operators, I think it's worth documenting that this method isn't cryptographically strong and that collisions are common, to add an extra layer of discouragement for anybody from trying to use this metric for secure purposes.
=> Document that the hash exposed in alertmanager_config_hash is not cryptographically strong

docs/configuration.md
Fixed a formatting error that made the <slack_config> section unavailable from the menu in the web documentation
=> Fixed formatting error

docs/configuration.md
Related https://groups.google.com/g/prometheus-users/c/Ra0oiVpVur8.
=> Improve the documentation on escaping in UTF-8 matchers

notify/msteamsv2/msteamsv2.go
* Fix typo for 'weight' to correct format of title
* Add wrap to content of adapter card to avoid truncating long text
=> Fix format issues of msteams adapter card

docs/configuration.md
=> fix:(alertmanager/docs): header for slack config

.github/workflows/publish.yml
Same as #4258, I missed an update in previous PR
The update addresses failing GitHub Actions caused by the deprecation of v3 actions/upload-artifact and actions/download-artifact APIs.
This change:
- Updates promci from previous version to v0.4.6
- I hope resolves CI failures in artifact upload/download steps
https://github.com/prometheus/promci/releases/tag/v0.4.6 https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> fix(ci): update promci to v0.4.6 to handle artifact actions deprecation (2)

config/config.go, config/config_test.go, inhibit/inhibit.go, inhibit/inhibit_test.go
This commit fixes a subtle bug introduced in #4177 where external code that imports `config.InhibitRule` for the purpose of JSON/YAML encoding can encode an inhibition rule with missing equals labels. This bug will happen if someone updates their Go modules, writes labels to the `Equal` field, and does not also write the same labels to the `EqualStr` field.
Before #4177:
```go
b, err := json.Marshal(InhibitRule{
Equals: model.LabelNames{"foo"},
})
```
```json
{
"equals": ["foo"]
}
```
After #4177:
```go
b, err := json.Marshal(InhibitRule{
Equals: model.LabelNames{"foo"},
})
```
```json
{}
```
To fix this, I propose removing `EqualStr` and changing `Equal` from `model.LabelNames` to `[]string`. This will cause an intentional breaking change, and require the maintainer of downstream code to …
=> Fix subtle bug in JSON/YAML encoding of inhibition rules

notify/jira/jira.go, notify/jira/jira_test.go
https://github.com/prometheus/alertmanager/pull/4159 enabled templating for Jira config fields `project` and `issue_type` by rendering the templates in the request body sent to create the issue:
However, it doesn't render the value in a previous request that checks if the Jira issue already exists, throwing the error:
```
notify retry canceled due to unrecoverable error after 1 attempts:
failed to look up existing issues: HTTP request to JIRA API: 
unexpected status code 400:
{"errorMessages":["The value '{{ .CommonLabels.project }}' does not exist for the field 'project'."],"warningMessages":[]}
```
This change adds the same template function to render the `project` value in the search request as well.
=> Render Jira project template when searching for existing issues

notify/opsgenie/api_key_file, notify/opsgenie/opsgenie.go, notify/opsgenie/opsgenie_test.go
The goal is to trim the spaces on the API key file for Opsgenie as it is already done for most other integrations (Slack, Discord, PagerDuty, etc.)
=> opsgenie : trim space for api key file

inhibit/inhibit.go
with big number of inhibitions I see pretty bad picture when we spend plenty of time in time.Now()
This can be fixed by calling it once per `hasEqual`
=> replace Resolved with ResolvedAt to reduce amount call to time.Now()

cli/root.go
fixes #4216 
I pattern to test a command which invokes os.exit comes from https://willsena.dev/golang-how-to-test-code-that-exits-or-crashes/
=> amtool: fix panic if --verbose is in used.

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/release.yml, CHANGELOG.md, cli/root.go, cmd/alertmanager/main.go, config/config.go, config/config_test.go, config/coordinator.go, config/notifiers.go, docs/configuration.md, go.mod, go.sum, inhibit/inhibit.go, inhibit/inhibit_test.go, notify/jira/jira.go, notify/jira/jira_test.go, notify/msteamsv2/msteamsv2.go, notify/opsgenie/api_key_file, notify/opsgenie/opsgenie.go, notify/opsgenie/opsgenie_test.go, notify/rocketchat/rocketchat.go, notify/sns/sns_test.go, notify/util.go, ui/Dockerfile
* [ENHANCEMENT] Improved performance of inhibition rules when using Equal labels. #4119
* [ENHANCEMENT] Improve the documentation on escaping in UTF-8 matchers. #4157
* [ENHANCEMENT] Update alertmanager_config_hash metric help to document the hash is not cryptographically strong. #4157
* [BUGFIX] Fix panic in amtool when using `--verbose`. #4218
* [BUGFIX] Fix templating of channel field for Rocket.Chat. #4220
* [BUGFIX] Fix `rocketchat_configs` written as `rocket_configs` in docs. #4217
* [BUGFIX] Fix usage for `--enable-feature` flag. #4214
* [BUGFIX] Trim whitespace from OpsGenie API Key. #4195
* [BUGFIX] Fix Jira project template not rendered when searching for existing issues. #4291
* [BUGFIX] Fix subtle bug in JSON/YAML encoding of inhibition rules that would cause Equal labels to …
=> Prepare Release 0.28.1

Dockerfile
Dockerfile was mixing absolute and relative Alertmanager configuration and storage paths.
=> Dockerfile: Use absolute paths for Alertmanager files

docs/configuration.md
This commit improves the documentation around the group timers such as group_wait, group_interval and repeat_interval. It offers a more in-depth explanation of how these timers work without going into detail about how they are implemented in the code.
=> Improve documentation around group timers

doc/alertmanager-mixin/alerts.libsonnet
5m is an unfortunate value since its the same as the default group_interval. If only a single alert fires and a single notifier fails consistently the alert will never fire, since the rate[5m] will be 0 after less then the group_interval.
=> mixin: longer rate interval for Alertmanager[Cluster]FailedToSendAlerts

MAINTAINERS.md
George has been a cornerstone of the Alertmanager community. From meticulously triaging issues to delivering critical UTF-8 support, his contributions have touched every aspect of the project.
We are proud to officially welcome him as a maintainer.
Thank you for your invaluable dedication and hard work, George.
=> Add George Robinson as an Alertmanager mantainer

docs/alerts_api.md
Fixes an extra space after "here" that was written as "here ".
=> Fix extra space at the end of here

README.md
README still references `/api/v1` and provides a message that discourages to use `/api/v2`, so I think it would be nice to change this.
=> Update README information about api/v2 and api/v1

notify/notify.go, notify/notify_test.go
A simple fix to correct the log message. In cases where context cancelation occurs, the logs show notification was attempted twice when in fact it was only attempted once
=> Fix logged notification count

types/types_test.go
This commit changes an incorrect assertion that a
suppressed silenced alert is marked as active.
Change-Id: 86e470c80eb5aa3fd59b32374e664ee2
Relates-To: https://github.com/prometheus/alertmanager/issues/4315
=> chore(tests): fix incorrect types test assertion

config/config.go, config/config_test.go
This PR fixes a typo in the route config validation error message.
=> chore: fix typo in route config validation error message

config/notifiers.go, config/notifiers_test.go, docs/configuration.md, notify/pushover/pushover.go, notify/pushover/pushover_test.go
Hey all,
this is my first contibution to alertmanager. Please let me know if I missed something.
There are two changes in this PR, but hey seemed very related:
- Document the (already existing) feature of enabling HTML message formatting when using Pushover
- Add the possibility to use monospace formatting for messages in Pushover (+documentation, +test)
API documentation can be found [here](https://pushover.net/api#html).
=> Pushover: Add monospace message formatting, add documentation for existing HTML styling

docs/configuration.md
=> docs: Correct heading level for Slack

matcher/compat/parse.go
When importing alertmanager in a project with `prometheus/common` >= [v0.62.0](https://github.com/prometheus/common/releases/tag/v0.62.0) in [classic mode](https://prometheus.io/docs/alerting/latest/configuration/#classic-mode), calls to `compat.IsValidLabelName` use `UTF8Validation` scheme due to a new default for [NameValidationScheme](https://github.com/prometheus/common/blob/v0.62.0/model/metric.go#L37). This PR addresses this change by correctly using the legacy validation logic. 
As a workaround, set `model.NameValidationScheme` to `model.LegacyValidation`.
=> fix(matchers/compat): use legacy name validation scheme in classic mode

.github/dependabot.yml
This should help update all the aws-sdk-go-v2 deps together, reducing pull requests and reducing the risk that these deps become out of sync.
=> Update dependabot to group AWS deps

cmd/alertmanager/main.go, dispatch/dispatch.go, dispatch/dispatch_test.go
- make dispatcher maintenance interval configurable
Related to #4540
=> feat(dispatcher): add maintenance interval config

silence/silence.go
1) Since MarshalBinary does not perform any writes or state modifications (the local buffer doesn’t affect shared state), it’s more appropriate to use RLock instead of Lock.
2) We can call Lock/Unlock later, just before getSilence in the function func (s Silences) Set(sil pb.Silence)
=> minor Lock/Unlock optimization
