- AUTHORS.md
- CONTRIBUTING.md
- LICENSE
- NOTICE
- README.md
> License cleanup.

- Makefile.INCLUDE
> Fix Go download link for several archs and OSes.

- main.go
- web/web.go
> Make flag names consistent across projects.

- README.md
- config/config.go
- config/config.proto
- config/fixtures/sample.conf.input
- config/generated/config.pb.go
- manager/notifier.go
This adds https://pushover.net/ as a way of notification.
I'm not sure if this is entirely useful for everybody but I saw myself using it so I thought I'd contribute.
Thanks!
> add pushover as notification method

- web/web.go
This fixes https://github.com/prometheus/prometheus/issues/607
> Only serve alerts page from /alerts or /.

- manager/notifier.go
instead continue in case other notifications should alert
> fix notifier, return means no other notifications will work. 

- manager/notifier.go
- manager/notifier_test.go
I created an HTML template, similar to the existing email body template. I use it for content in the Flowdock message. It's rather generic, and I think it can be used also in other HTML-capable notification receivers like Hipchat.
In Flowdock it looks like:
> HTML template for notifications with FlowDock

- manager/notifier.go
> Fixed pushover api call with retry and expire flags

- manager/notifier.go
Renamed TopicARN to TopicArn to match https://github.com/aws/aws-sdk-go/blob/54390aa3615c49d34e593de83ddc72e5ee35f97d/service/sns/examples_test.go#L518.
> Renamed TopicARN to TopicArn

- Makefile
- build_info.go
Broken by the following commit
e38bb7c Use Makefile.COMMON and add generated files.go
> Fix version info string.

- web/alerts.go
Yeah, I could have gone through even more effort to sort alphabetically by exact labelset, but don't want
to put too much effort into the old web UI now. Main thing is that now entries will at least be sorted by
their alertname, as well as stay in the same position in general between page loads.
> Sort alerts consistently in web UI.

- config/fixtures/sample.conf.input
I was trying to figure out how to set up opsgenie and ended up digging out the syntax from an older PR. This seems like the canonical place for it to be documented.
> Update sample config to include opsgenie example

- inhibit.go
- test/acceptance.go
- test/acceptance/simple_test.go
- test/collector.go
The inhibition acceptance test is still failing because the `Subscribe` method needs fixing
(it currently does not return all alerts).
> Add inhibiting test, fix some uncovered issues

- README.md
> Show build status of master branch

- Makefile
- Makefile.COMMON
Sync Makefile.COMMON with other projects.
Fix associated lint warning.
Not sure about web/blob/files.go
> Bump Go version from 1.4.2 to 1.5.1.

- main.go
> Ensure data directory exists

- dispatch.go
- provider/sql.go
> Remove data races

- config/config.go
- config/notifies.go
- notify/impl.go
- template/default.tmpl
Seems to be working OK, although resolving alerts seems a bit hit & miss - not due to this code I don't think as the OpsGenie API calls are pretty simple, but more the firing/resolve flow.
/cc @fabxc
> Add OpsGenie notifier

- config/notifies.go
- notify/impl.go
- template/default.tmpl
> Improve Slack integration

- Dockerfile
Now that default templates are compiled in.
> Remove default.tmpl from Docker image

- config/config.go
- config/notifiers.go
- notify/impl.go
- ui/bindata.go
> Hide secret configuration data

- main.go
- notify/notify.go
- notify/notify_test.go
- template/template.go
- types/types.go
> Set previous inhibition/silence state

- template/template.go
> Allow zero matching template files

- config/config.go
- config/notifiers.go
- dispatch.go
- dispatch_test.go
- notify/impl.go
- notify/notify.go
- notify/notify_test.go
- route.go
- route_test.go
> Move send_resolved parameter to notifier configuration

- config/notifiers.go
- test/acceptance/send_test.go
> Correctly parse send_resolved config field

- api.go
- web.go
> Add basic instrumentation

- api.go
> Make metric names consistent.

- notify/impl.go
> Add instrumentation about notifications

- vendor/github.com/prometheus/common/log/log.go
- vendor/github.com/prometheus/common/log/syslog_formatter.go
- vendor/vendor.json
> Update common/log vendoring

- vendor/github.com/prometheus/common/model/silence.go
- vendor/github.com/prometheus/common/model/time.go
- vendor/github.com/prometheus/common/route/route.go
- vendor/vendor.json
This will enable ms precision for configuration. Unlikely to be relevant for the Alertmanager but configuration shouldn't be different from Prometheus.
> Update common/* package vendoring

- config/config.go
The root route in the configuration must not exclude any alerts,
i.e. not have any matchers.
All receivers referenced in the routing tree are validated to exist.
> Add routing validation

- api.go
- notify/impl.go
- template/internal/deftmpl/bindata.go
- ui/bindata.go
> Fix vetting errors

- vendor/github.com/mattn/go-sqlite3/README.md
- vendor/github.com/mattn/go-sqlite3/callback.go
- vendor/github.com/mattn/go-sqlite3/doc.go
- vendor/github.com/mattn/go-sqlite3/sqlite3.go
- vendor/github.com/mattn/go-sqlite3/sqlite3_json1.go
- vendor/vendor.json
@nikgrok could you validate that this branch works if you build it with your Go 1.6?
@stapelberg
> Update go-sqlite3 vendoring

- notify/impl.go
@fabxc @m-o-e 
Solves first part of #270.
> Add debug log for unexpected opsgenie responses

- README.md
See https://github.com/prometheus/alertmanager/issues/285
> Clarify build- vs. run-time dependencies in README.md

- notify/impl.go
Hello @fabxc,
I'm trying to upgrade our alertmanager installation and had to make a minor fix to make it handle the case where an alert is closed more than once, which can happen if i.e. an operator closes the alert manually. The behavior is not documented in OpsGenie's API docs, so the code is based on exploratory testing.
Perhaps in poor style, but very conveniently for myself, I also drive-by-fixed a few minor things while touching the file. I hope you don't mind that I included them here, but I'll be happy to break them out in a separate PR if you wish.
Thanks,
-AndersM
> Notifications: Improve OpsGenie error handling, and minor fixes

- version/info.go
> Use runtime.Version() instead of injected version

- config/config.go
- template/internal/deftmpl/bindata.go
- ui/bindata.go
> Hide PushOver auth information

- ui/app/css/main.css
Change-Id: I5f5ce8c7113b2188083ef0ec9ef2bcc4d74f5500
> Change fallback fonts to something readable

- template/template.go
Fixes https://github.com/prometheus/alertmanager/issues/314
> Add safeHtml template function.

- circle.yml
> ci: push images to Quay

- api.go
- main.go
Add api/-/reload endpoint #353 
@fabxc  Sorry for re-created the pull request. Because i cant fix the git conflict.
Thanks
> Add api/-/reload endpoint #353

- inhibit_test.go
- notify/impl.go
@fabxc Just to reduce the noise...
> Fix go vet warnings

- notify/impl.go
AUTH LOGIN is an authentication in smtp server (like PLAIN or MD5).
It would be nice to have this feature to use alertmanager email.
> Add support for smtp AUTH LOGIN

- config/notifiers.go
> config: make Slack channel optional

- cmd/alertmanager/main.go
> Pdbogen error on nonflag args

- api/api.go
Ideally I would also like to access POST and DELETE methods, but that probably doesn't make sense from a security perspective?
> allow CORS for api GET and OPTIONS

- notify/impl.go
- notify/notify.go
The retry flag allows an integration to specify whether a retry can
potentially be solved or if the error is likely not going to recover.
For example invalid authentication is likely a wrong configuration and
therefore a retry would not make sense, while a server error is likely
a temporary problem and can potentially be solved on the next retry.
It would be good to review all the added flags that enable/disable
retry, especially the ones in the email notifier.
@fabxc @beorn7 @brian-brazil 
Fixes #311
> add retry flag for notify providers

- CHANGELOG.md
> changelog: add latest versions

- README.md
- examples/ha/alertmanager.yaml
> add HA documentation to README.md

- config/config.go
- config/notifiers.go
- notify/impl.go
> config/notify: Add SMTP Require TLS global option

- cmd/alertmanager/main.go
Currently all mesh communication is unencrypted. Adding this parameter allows the operator to make use of this functionality of mesh. The operator has to take care of password rotations.
@fabxc @aecolley
fixes #529
> encrypt mesh communication

- api.go
@beorn7 when you get a chance, would be appreciated :) since the new ui is being developed as a separate app, I need the cors access to delete silences.
> Add DELETE to acceptable cors methods

- ui/app/index.html
- ui/app/src/Main.elm
- ui/app/src/Views.elm
- ui/app/src/Views/AlertList/FilterBar.elm
- ui/app/src/Views/AlertList/Views.elm
- ui/app/src/Views/NavBar/Types.elm
- ui/app/src/Views/NavBar/Views.elm
This is a quick spike testing out Bootstrap as our UI framework.
@stuartnelson3  @w0rm What do you think?
This is not focussed on design but rather technical usability.
> Spike: Use vanilla Bootstrap as ui framework

- .travis.yml
- ui/Dockerfile
- ui/app/src/Silences/Decoders.elm
- ui/app/src/Views/SilenceForm/Types.elm
This runs elm-format inside a docker container serving the Elm
environment. Afterwards we check with git if a file changed and fail
accordingly.
> test: Add elm-format job to travis ci configuration

- api/api.go
- cmd/alertmanager/main.go
- ui/web.go
- vendor/github.com/prometheus/common/expfmt/decode.go
- vendor/github.com/prometheus/common/expfmt/expfmt.go
- vendor/github.com/prometheus/common/log/syslog_formatter.go
- vendor/github.com/prometheus/common/route/route.go
- vendor/vendor.json
To match https://github.com/prometheus/common/pull/79
> Remove use of route.Context

- notify/impl.go
> notify: hex encode deduplication hash

- cmd/alertmanager/main.go
Closes #596
@fabxc @mxinden @brian-brazil
> Add config hash metric

- config/config.go
- config/config_test.go
Added unit test and comment for #767
> Added unit test for continue in root route error

- README.md
> docs: Add note to not load balance Alert trafic

- silence/silence.go
- silence/silence_test.go
> silence: fix and test expiration behavior

- CHANGELOG.md
I was just reading through the changelog and many changes are miscategorised.
Breaking changes should be marked with CHANGE, new user-facing things are FEATURES, tweaks and internals are ENHANCEMENTS.
> Correct change types in 0.6.x changelogs

- cli/root.go
Move config file to a more consistent location and update docs
> Fixes #831 

- config/config.go
- config/config_test.go
- config/testdata/conf.good.yml
> Elide secrets in alertmanager config

- CHANGELOG.md
@brancz Forgot about this. Sorry.
> Add status api change to changelog

- CHANGELOG.md
@brancz Same thing again. Once this is merged I will update the GitHub release notes.
> Merge changelog changes back to master.

- notify/impl.go
AlertManager currently is not able to send mails to smtp port 465. Adding this change that will take care of the above. In alertmanager conf file, you need to explicitly supply "require_tls" to false, in order to work with smtp port 465 
Refer issue #705 
@stuartnelson3  @beorn7
> Changes to send mail via smtp port 465

- cli/root.go
The config file location was changed in 305263e4626. Update the flag usage text accordingly.
/cc @Kellel
> Update config file location in flag usage text

- cli/utils.go
Exit with error code from subcommands as well as root command
> Fixes #898

- vendor/github.com/weaveworks/mesh/status.go
- vendor/vendor.json
Work was really done by @Kellel in https://github.com/prometheus/alertmanager/pull/940, just moving this along
> Fixes #925

- artifacts/README.md
Sentence and spelling cleanup, also removed a trailing newline.
Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>
> Cleanup artifacts/README.md

- api/api.go
Closes #957 
I see mention of a configurable UI to sort silences. 
Does feature this really make sense after filtering when there'll only be a few silences shown?
> Sort silences based on current status

- config/config.go
- config/config_test.go
> Improve config package test coverage

- config/notifiers_test.go
this improves the package test coverage a lot :)
> Add tests to notifiers config

- dispatch/dispatch.go
A single entry in aggrGroups is just a single group, not plural.
> Clarify variable names in Dispatcher.processAlert()

- api/api.go
- api/api_test.go
Fixes https://github.com/prometheus/alertmanager/issues/1060
@beorn7 @stuartnelson3
> Fix negative matchers filtering

- README.md
- config/config.go
- config/config_test.go
- config/notifiers.go
- config/notifiers_test.go
- config/testdata/conf.good.yml
- notify/impl.go
This closes #877 and maintains backwards compatibility with current configurations
> Add support for PagerDuty API v2

- cli/alert.go
- cli/check_config.go
- cli/check_config_test.go
- cli/config.go
- cli/silence_add.go
- cli/silence_expire.go
- cli/silence_query.go
- cli/utils.go
https://github.com/golang/go/wiki/Errors#errors
> Clean code style - amtool errors

- README.md
Updated HA configuration, adding Prometheus 2.x.
> Updated README for Prometheus 2.x

- cmd/alertmanager/main.go
- provider/mem/mem.go
- provider/mem/mem_test.go
@brancz and I were discussing this earlier, and it seemed to make sense to make this configurable.
I'm happy to change the flag name, so any suggestions are welcome.
> Make alertGC interval configurable

- api/api.go
Found two places where struct members being
updated in api.Update() where being accessed
elsewhere without locks.
testing this at the moment.
> Lock around variables used in Update()

- api/api.go
> Fix wrong lock

- README.md
Did this to give an example with multiple email addresses in the “to“ field.
> Added 2nd email address to “to“ field

- cli/silence_query.go
This means there's no longer a way to list both active and expired
silences at the same time. This is the desired behaviour according to
consensus at https://github.com/prometheus/alertmanager/pull/1175
> Make --expired list only expired silences (#1176)

- cli/silence_update.go
Quick update to amtool silence update to allow dwy suffixes to be added to the expire flag, to maintain syntax compatibility with amtool silence add
> amtool silence update support dwy suffixes to expire flag

- vendor/github.com/weaveworks/mesh/overlay.go
- vendor/vendor.json
> Fix pending connections never going to established

- notify/impl.go
@stuartnelson3 here is the proposal, as we discussed in the issue #1211 in case you agree that this change makes sense to be part of the AM official release.
>  Fixes prometheus/alertmanager#1211

- config/config.go
- config/config_test.go
- config/notifiers.go
- config/notifiers_test.go
- config/testdata/conf.opsgenie-default-apikey.yml
- config/testdata/conf.opsgenie-no-apikey.yml
> allow global opsgenie api key

- config/notifiers.go
- notify/impl.go
> Add templating to PD-CEF fields; Add missing field

- api/api.go
- api/api_test.go
Fixes #1191.
cc @Conorbro @stuartnelson3 @brian-brazil
> api: support zero StartsAt for alerts

- cmd/alertmanager/main.go
> cluster: Make peer timeout configurable

- config/config.go
- config/config_test.go
- config/notifiers.go
- config/notifiers_test.go
- notify/impl.go
- notify/impl_test.go
- vendor/github.com/prometheus/common/config/config.go
- vendor/github.com/prometheus/common/config/http_config.go
- vendor/vendor.json
This is #930 rebased on master.
Closes #516 and #853.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prometheus/alertmanager/1222)
> *: configure http client from config

- api/api.go
- provider/mem/mem_test.go
Spotted at https://travis-ci.org/prometheus/alertmanager/builds/344780795#L594
> Fix miscellaneous issues revealed by Go 1.10

- Makefile
- api/api.go
- cli/silence_import.go
- cli/silence_update.go
- cmd/alertmanager/main.go
- nflog/nflog_test.go
- notify/impl_test.go
- notify/notify_test.go
- provider/mem/mem_test.go
- types/types.go
This change also fixes potential issues highlighted by running
staticcheck.
> Run staticcheck as part of the build process

- README.md
> Update for new HA docs

- dispatch/route.go
- test/acceptance/send_test.go
This is what the intended default is, and what
the documentation says.
@stuartnelson3
> The default group_by is meant to be no labels.

- cluster/cluster_test.go
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> gofmt code

- nflog/nflog.go
- silence/silence.go
Signed-off-by: Ted Zlatanov <tzz@lifelogs.com>
Addresses #1346 
Trivial change.
> #1346: move maintenance messages to DEBUG log level

- notify/impl.go
Invalid configuration template in WechatConfig
> fix wechat issue (#1353)

- api/api.go
This is a follow-up of f825d97de4d45dcbbff85fba7ed3f95d50f4640d.
cc @mxinden
> api: remove dead code

- .circleci/config.yml
Fix similar to https://github.com/prometheus/prometheus/pull/4149.
> circleci: fix docker push command

- .circleci/config.yml
Similar to https://github.com/prometheus/prometheus/pull/4182
> Fix CircleCI config for releases

- pkg/parse/parse.go
- pkg/parse/parse_test.go
> parse: fix parsing for label values with commas

- Makefile
- Makefile.common
- template/internal/deftmpl/bindata.go
- ui/bindata.go
> Use Makefile.common from Prometheus

- notify/impl.go
- vendor/github.com/mwitkow/go-conntrack/LICENSE
- vendor/github.com/mwitkow/go-conntrack/README.md
- vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go
- vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go
- vendor/github.com/mwitkow/go-conntrack/listener_reporter.go
- vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go
- vendor/github.com/prometheus/common/config/config.go
- vendor/github.com/prometheus/common/config/http_config.go
- vendor/github.com/prometheus/common/expfmt/decode.go
- vendor/github.com/prometheus/common/expfmt/expfmt.go
- vendor/github.com/prometheus/common/expfmt/text_parse.go
- vendor/github.com/prometheus/common/model/silence.go
- vendor/github.com/prometheus/common/model/time.go
- vendor/github.com/prometheus/common/model/value.go
- vendor/golang.org/x/net/LICENSE
- vendor/golang.org/x/net/PATENTS
- vendor/golang.org/x/net/internal/timeseries/timeseries.go
- vendor/golang.org/x/net/trace/events.go
- vendor/golang.org/x/net/trace/histogram.go
- vendor/golang.org/x/net/trace/trace.go
- vendor/golang.org/x/net/trace/trace_go16.go
- vendor/golang.org/x/net/trace/trace_go17.go
- vendor/vendor.json
> vendor: update prometheus/common packages

- dispatch/dispatch.go
- types/types.go
- types/types_test.go
This PR adds unit tests on top of #1339.
> Sort alerts in correct order

- template/email.html
Fixed minor issue in email template.
> fix: email template typo in alert-warning style

- config/notifiers.go
- config/notifiers_test.go
Closes #1451
cc @CatherineBowen @Allex1 if one of you wants to try it.
@stuartnelson3 since it is a regression, it might be a case for a v0.15.1 release. WDYT?
> config: fix regression with Pager Duty

- cmd/alertmanager/main.go
> alertmanager: fix Settle() interval

- api/api.go
- cli/check_config.go
- cli/format/format_extended.go
- cli/format/format_simple.go
- cli/silence_query.go
- cli/silence_update.go
- client/client.go
- cmd/alertmanager/main.go
- examples/webhook/echo.go
- inhibit/inhibit.go
- notify/impl.go
- notify/notify.go
- test/acceptance.go
...as discovered by "gosec" (many other ones reported, but not all make
a lot of sense to fix).
> Fix a bunch of unhandled errors

- MAINTAINERS.md
I would like to help out @stuartnelson3 as a second official maintainer of the Alertmanager project.
Let me know what you think.
> MAINTAINERS.md: Add Max Inden

- config/notifiers.go
- notify/impl.go
> Slack: Support image/thumb url in attachment

- Makefile.common
> Sync Makefile.common

- provider/mem/mem.go
... rather than in the Subscribe method. Currently the cleanup for a
given Alert subscription is done in a blocking goroutine, started in
the Subscribe method.
This simplifies it by moving the cleanup to the GC.
Additionally it simplifies the subscribe method by setting up the
buffered channel big enough to fill it up with all pending alerts
preventing the necessity to start a goroutine in Subscribe at all.
/cc @mxinden @brancz
> provider/mem: cleanup closed listener in GC

- .circleci/config.yml
#1518 introduced the issue.
See https://circleci.com/gh/prometheus/alertmanager/2634 for instance.
cc @stuartnelson3
> circleci: fix Docker jobs

- Dockerfile
> Using the recommended label syntax for maintainer.

- README.md
> README.md: update HA section

- README.md
> Fix the Swagger/OpenAPI link

- README.md
It took me quite some digging, I hope this helps others (e.g. #1550)
as side note: Without turning on debug logs, it doesn't really show the clustering is not working. Shall I report that as an issue?
> Make a note about the firewall in HA mode

- .circleci/config.yml
Similar to https://github.com/prometheus/prometheus/pull/4685
> circleci: store build outputs as artifacts

- .circleci/config.yml
- .promu.yml
- .travis.yml
- asset/assets_vfsdata.go
> *: move to go1.11

- Dockerfile
> run as nobody

- cmd/alertmanager/main.go
Similar to https://github.com/prometheus/prometheus/pull/4865
> cmd/alertmanager: use buffered channel for signal

- test/with_api_v2/acceptance/send_test.go
Follow up of https://github.com/prometheus/alertmanager/pull/1611#issuecomment-438953319
> test: add acceptance test for firing alerts with EndsAt

- cluster/delegate.go
In cluster/delegate.go, I change the label name full_state and update to const value.
Signed-off-by: yeya24 <ben.ye@daocloud.io>
> replace labels to const to reduce hardcode

- notify/impl.go
- notify/impl_test.go
We were truncating strings in a few places but not very consistently. This is a follow-up of #1701.
> notify: factorize code truncating strings

- CHANGELOG.md
- api/v1/api_test.go
- cli/test_routing_test.go
- ui/app/CONTRIBUTING.md
- Fix error string should not be capitalized from [Golang coding convention](https://github.com/golang/go/wiki/CodeReviewComments#error-strings)
- api/v1/api_test.go
- cli/test_routing_test.go
- Fix some typos:
- CHANGELOG.md
- ui/app/CONTRIBUTING.md
> Fix styling and typos

- api/v2/openapi.yaml
- api/v2/restapi/embedded_spec.go
- api/v2/restapi/operations/alert/get_alerts_parameters.go
- api/v2/restapi/operations/alert/get_alerts_urlbuilder.go
- api/v2/restapi/operations/silence/get_silences_parameters.go
- api/v2/restapi/operations/silence/get_silences_urlbuilder.go
- test/with_api_v2/api_v2_client/client/alert/get_alerts_parameters.go
- test/with_api_v2/api_v2_client/client/silence/get_silences_parameters.go
- ui/app/Makefile
Closes #1783 
cc @roidelapluie
> *: fix filter parameters with comma

- CHANGELOG.md
- cli/silence_query.go
- cli/test_routing.go
- cluster/delegate.go
- notify/impl.go
- test/with_api_v1/acceptance.go
- test/with_api_v1/acceptance/send_test.go
- test/with_api_v1/mock.go
- test/with_api_v2/acceptance.go
- test/with_api_v2/acceptance/send_test.go
No functional change.
Signed-off-by: Karsten Weiss <knweiss@gmail.com>
> Fix some typos

- Makefile
Not needed anymore since https://github.com/prometheus/alertmanager/pull/1738
> Makefile: remove bzr check

- cli/alert_add.go
- cluster/cluster.go
- notify/impl.go
No functional change, fix golint error in 3 files
1. struct field generatorUrl should be generatorURL
2. if block ends with a return statement, so drop this else and outdent its block
> fix golint error

- notify/impl.go
- notify/impl_test.go
Related to #1809. When the PagerDuty v2 API returns a 400 (bad request) status, the error message is only visible at the debug level while it is visible at the error level with the v1 API. This PR makes consistent for both cases as the format of the error response is the same between v1 and v2.
> notify: rework handling of PagerDuty responses

- CHANGELOG.md
- api/v2/api.go
- cli/alert_add.go
- cli/alert_query.go
- cli/config.go
- cli/format/format.go
- cli/format/format_extended.go
- cli/format/format_json.go
- cli/format/format_simple.go
- cli/format/sort.go
- cli/root.go
- cli/routing.go
- cli/silence_add.go
- cli/silence_expire.go
- cli/silence_import.go
- cli/silence_query.go
- cli/silence_update.go
- cli/test_routing.go
- cli/test_routing_test.go
- cli/utils.go
Update the amtool cli to use the v2 API
Includes godoc improvements
> cli: update amtool to use apiv2

- dispatch/dispatch.go
- notify/notify.go
> *: log at debug level when context is canceled

- asset/asset.go
This PR avoids issues like https://github.com/prometheus/pushgateway/issues/240
> asset: fix when outside of $GOPATH

- test/with_api_v1/acceptance.go
delete duplicate close of http body.
> test/with_api_v1: delete duplicate close of http body.

- test/with_api_v2/acceptance.go
Seen here: https://circleci.com/gh/prometheus/alertmanager/4519
> test/with_api_v2: fix variable shadowing

- cli/root.go
> Use scheme and auth info if present from URL

- notify/impl.go
Closes #1700 for people using the PagerDuty v1 endpoint.
Tested locally with a fake service key and it seems working.
cc @gouthamve
> notify: truncate description for PagerDuty v1

- cli/root.go
> cmd/amtool: use base path from the configured URL

- api/v2/api.go
- api/v2/api_test.go
> api/v2: fix alerts with multiple receivers

- template/template.go
- template/template_test.go
One small improvement and more tests to make sure that it is valid.
> template: add tests

- template/template.go
Hopefully fixes #1903 by adding the Fingerprint to the template data. My goal for this is to have the fingerprint in the Webhook data for downstream consumption.
> Add Fingerprint to template data

- template/template_test.go
This was recently added and the test needs to be updated.
> Add fingerprint to expected template test output

- test/cli/acceptance.go
- test/cli/acceptance/cli_test.go
- test/cli/collector.go
- test/cli/mock.go
Working on some acceptance tests for amtool
> test/cli: add basic amtool cli tests

- cmd/alertmanager/main.go
> cmd/alermanager: log when repeat_interval > retention

- config/config.go
- config/config_test.go
- config/notifiers.go
- notify/email/email.go
- notify/email/email_test.go
> *: check Smarthost validity at config loading

- README.md
fixes #1820
Signed-off-by: Christoph Maser <christoph.maser+github@gmail.com>
> Add docs for cluster.reconnect flags

- notify/email/email.go
- notify/email/email_test.go
Rspamd - `MISSING_MID (2.5)`
Reference: [jordan-wright/email](https://github.com/jordan-wright/email/blob/041e0cec78b06dd35f6431f4fa92f2b29fa30d67/email.go#L612)
> Add email notify Message-Id Header

- ui/app/Makefile
Noticed this was missing
@simonpasquier
> add elm-* to ui/app make clean

- types/types.go
> types: remove redundant statements.

- config/config.go
- config/config_test.go
- dispatch/route.go
Relates to #2129
This reverts commit 918f08b66ac0e95990383951f6fd8f9e5434d590.
> Revert "config: remove support for JSON marshaling (#2086)"

- cli/root.go
Signed-off-by: Kevin Hellemun <17928966+OGKevin@users.noreply.github.com>
Closes #2160
> [#2160] Removed default assignment of env vars.

- MAINTAINERS.md
I've been largely inactive for the last 6 months,
and have no plans to become active again.
> remove stuart from MAINTAINERS.md

- api/v2/api.go
@celian-garcia I need to check that the CI pipeline is still working after a configuration change I did hence I'm submitting the follow-up for #2173
> api/v2: Fix silence creation error message

- examples/ha/send_alerts.sh
add shebang for test script  to fix goland run script error
> add shebang for test script

- .github/ISSUE_TEMPLATE.md
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> .github/ISSUE_TEMPLATE.md: fix typo

- docs/configuration.md
See https://github.com/prometheus/docs/pull/1663
> Add note about details handling for Opsgenie

- docs/configuration.md
- docs/notifications.md
> docs: document alert's fingerprint

- config/coordinator.go
Closes #2372
Signed-off-by: Kevin Hellemun <17928966+OGKevin@users.noreply.github.com>
> [#2372] Move config reload metrics to Coordinator.Reload()

- README.md
> docs(readme): correcting hyperlink text for RFC url

- .circleci/config.yml
- doc/alertmanager-mixin/Makefile
- doc/alertmanager-mixin/README.md
- doc/alertmanager-mixin/alerts.jsonnet
- doc/alertmanager-mixin/alerts.libsonnet
- doc/alertmanager-mixin/config.libsonnet
- doc/alertmanager-mixin/go.mod
- doc/alertmanager-mixin/mixin.libsonnet
Alerts are from https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/ and https://github.com/prometheus/prometheus/pull/4474.
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>
> Beginnings of an Alertmanager mixin.

- config/config.go
I have found out that we still need this for the v1 API (and possibly
elsewhere).
@aSquare14 could you have a look?
> Add JSON marshaling to config.Matchers

- config/config.go
> Call SetDirectory for HTTP clients

- docs/configuration.md
Related issue : #1023 
Related Pull requests : #2434 #2460
> docs for negative matchers for route, inhibition

- CHANGELOG.md
> Add #2276 to release notes

- cmd/alertmanager/main.go
> Fix panic when HA is disabled

- docs/configuration.md
> Add a note about Pushover ready-to-clone app

- README.md
The flag **-p** ist on the wrong position in your example silence query command.
> Fix example silence query parameter

- .circleci/config.yml
- README.md
- docs/configuration.md
> Rename default branch to main

- notify/sns/sns.go
The HTTP client options passed to SNS receiver are ignored because the HTTP client is never passed to the SNS client. This PR fixes it.
> Fix HTTP client options in SNS receiver

- docs/configuration.md
> docs: Fix default value of send_resolved for sns_configs (#2724)

- cli/root.go
Allows connecting to alertmanager instances behind a TLS endpoint that
requires mutual TLS. Conveniently also allows specifying a CA
certificate file for alertmanagers that use trusted roots not in the
system root trust store.
Fixes: https://github.com/prometheus/alertmanager/issues/2652
Signed-off-by: Joe Groocock <me@frebib.net>
> Add client TLS configuration

- doc/alertmanager-mixin/.lint
- doc/alertmanager-mixin/dashboards/overview.libsonnet
There are new rules defined in https://github.com/grafana/dashboard-linter. some of rules are strict. so add them into exclusions.
Signed-off-by: clyang82 <chuyang@redhat.com>
> fix lint error

- config/notifiers.go
- config/notifiers_test.go
This change also adds unit tests for SNS configuration.
> config: delegate Sigv4 validation to the inner type

- docs/configuration.md
> doc:fix comments

- .circleci/config.yml
- Makefile
- scripts/package_assets.sh
Enable frontend consumption by downstreams, like debian and nixos
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
> Package and ship frontend independently

- dispatch/dispatch.go
> Remove unused Marker from Dispatcher struct

- test/with_api_v2/acceptance.go
The CI keeps reporting flakes for our acceptance test around the starting and stopping of the Alertmanagers. While I have an idea of where these failures are coming from, it would be nice to get a confirmation by structuring our error messages a bit better.
e.g. https://app.circleci.com/pipelines/github/prometheus/alertmanager/2753/workflows/983f6fe7-22bf-4fe1-9edd-c3c5a8a41cb0/jobs/12301
> Acceptance Tests: Better error messages

- go.mod
- go.sum
Required to fix https://github.com/prometheus/alertmanager/pull/3066
> Set min version of go.mod to 1.18

- README.md
Updated receiver integrations listed in README.md with links to their landing pages for easier reference and accessibility.
Signed-off-by: sunb3am <57086182+sunb3am@users.noreply.github.com>
> Docs: Updated README.md to include links to receiver integrations

- cli/check_config.go
- cli/template_render.go
- cmd/alertmanager/main.go
- notify/email/email_test.go
- notify/test/test.go
- template/template.go
- template/template_test.go
Change the `template.FromGlob` function to accept also additional options to extend/modify the default Template.
> feat: add template.FromGlobsWithAdditionalFuncs

- docs/configuration.md
> Add missing docs for Discord notifier

- docs/configuration.md
https://github.com/prometheus/alertmanager/pull/2981
https://github.com/prometheus/alertmanager/commit/d4c2048
> Telegram default parse_mode has been changed to HTML

- template/template.go
Fixes #3217
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
> Seperate the template creating functions for as-lib use

- template/template.go
Some feedback from @gotjosh that was missed before https://github.com/prometheus/alertmanager/pull/3278 was closed.
> Fix comments as per Josh's feedback

- cluster/tls_transport_test.go
change hardcode port to random available port
> if 9093/9094 port is in use, test case will fail

- config/config.go
Fix https://github.com/prometheus/alertmanager/pull/3324#discussion_r1312537848
> update msteams configs

- RELEASE.md
A clean copy of #3344 which was previously approved.
> Define a `RELEASE.MD` for the Alertmanager Project

- docs/configuration.md
Some links with examples that would have helped me greatly when setting up alertmanager.
> Add links to concepts inhibition and grouping to docs/configuration.md

- .github/dependabot.yml
Add a monthly dependabot update for NPM packages in the new React UI.
> Enable Dependabot for React UI

- config/config_test.go
- config/notifiers_test.go
- docs/configuration.md
> docs: better descibe `email_config.to` fromat

- docs/clients.md
> Update docs for deprecation and removal of API v1

- ui/Dockerfile
Update to current Node/Debian Docker image.
> Bump UI docker image

- notify/rocketchat/rocketchat.go
Resolves https://github.com/prometheus/alertmanager/issues/4219
> Fix rocketchat channel templating

- docs/alertmanager.md
- docs/alerts_api.md
- docs/configuration.md
- docs/https.md
- docs/management_api.md
- docs/notification_examples.md
- docs/notifications.md
- docs/overview.md
See https://groups.google.com/g/prometheus-developers/c/cwL3cM66Em8
> Standardize doc page title handling
